
import type { LucideIcon } from 'lucide-react';
import { Book, KeySquare, Terminal, GitBranch, Sparkles, Infinity, BookHeart, Shield, Library, FlaskConical, Dna, FileJson, GitCommit, Sprout, UserCircle, Brain, Bot } from 'lucide-react';

export interface Document {
  key: string;
  title: string;
  link: string;
}

export interface Section {
  id: string;
  title: string;
  icon: LucideIcon;
  documents: Document[];
}

export const sectionsData: Section[] = [
  {
    id: 'chaves-mestra',
    title: 'Chaves Mestras',
    icon: KeySquare,
    documents: [
      { key: 'cm-1-unificacao', title: 'Chave Mestra 1 (Unificação)', link: 'https://docs.google.com/document/d/101D5KIldQsEq61BhO3QOPsD79aXykMw86bkN6B5mFWA/edit?usp=drive_link' },
      { key: 'cm-2-unificacao', title: 'Chave Mestra 2 (Unificação)', link: 'https://docs.google.com/document/d/18nw3sp_z5NEdMmYEidcoyqWGy6T27OfA1JpuZHG202I/edit?usp=drive_link' },
      { key: 'cm-1-principio', title: 'Chave Mestra 1 (Princípio)', link: 'https://docs.google.com/document/d/1eEeMZ-7_gXtbspY7ed3X19iv1tGC2WdUnydr91EGl_s/edit?usp=drive_link' },
      { key: 'cm-2-principio', title: 'Chave Mestra 2', link: 'https://docs.google.com/document/d/176udDvsoV3bPiNvhaSQTo4NFvH7CPJ4_afc0ARjYJ7M/edit?usp=drive_link' },
      { key: 'cm-3', title: 'Chave Mestra 3', link: 'https://docs.google.com/document/d/16FK-NLS06vubxGrciRLpay33fyEsll19lUVsS_hcOzY/edit?usp=drive_link' },
      { key: 'cm-4', title: 'Chave Mestra 4', link: 'https://docs.google.com/document/d/1LSrBTnxSnzHUt5a0gF58tnb7lxkLh0mmUZmAgUH3Aek/edit?usp=drive_link' },
      { key: 'cm-5', title: 'Chave Mestra 5', link: 'https://docs.google.com/document/d/14L5Dq1pQHaE5v3cheyvivRBWz_8ttKRHOCPXGeJsZjg/edit?usp=drive_link' },
      { key: 'cm-6', title: 'Chave Mestra 6', link: 'https://docs.google.com/document/d/1ZKXVhQJ9o5qhGoxfPuEqFP2Lm2Vg4c87id3E_Ckr-eY/edit?usp=drive_link' },
      { key: 'cm-7', title: 'Chave Mestra 7', link: 'https://docs.google.com/document/d/1viBXh8-W4pIryWA9w7CRG8TzpeqEF0PuFjJi-qQD41w/edit?usp=drive_link' },
      { key: 'cm-8', title: 'Chave Mestra 8', link: 'https://docs.google.com/document/d/1KiJ4c7GAHaWcnlPmFyT1kzf6GkXCURWamZ0wxyzjSrQ/edit?usp=drive_link' },
    ]
  },
  {
    id: 'luxnet',
    title: 'LuxNet & Equações',
    icon: GitBranch,
    documents: [
      { key: 'luxnet-aeternum', title: 'Chave Mestra LUXNET AETERNUM', link: 'https://docs.google.com/document/d/16SoVCrdNYeYDBSoCXkC9laPCLWKjXnweo_4NlBcDTWw/edit?usp=drive_link' },
      { key: 'luxnet-eq-1-5', title: 'EQ LUXNET 1-5', link: 'https://docs.google.com/document/d/11Do2cv7UtOVDaNM2--g_smBfafjtthgHcRihhyJZ4pE/edit?usp=drive_link' },
      { key: 'luxnet-eq-6-7', title: 'EQ LUXNET 6-7.2', link: 'https://docs.google.com/document/d/1FtrKn8avitoqo1KQGAgkxo5absghwDMbDNsLDBMTWMo/edit?usp=drive_link' },
      { key: 'luxnet-eq-8-13', title: 'EQ LUXNET 8-13', link: 'https://docs.google.com/document/d/1J1wbtd-qIMhscUwZvtwQZMnmRCue7uXuCYMFLK8COWQ/edit?usp=drive_link' },
      { key: 'luxnet-eq-14-19', title: 'EQ LUXNET 14-19', link: 'https://docs.google.com/document/d/1FPRvl1P44uSwuyhBf9R6jceKK8oHnPSD7f-KfchgXIA/edit?usp=drive_link' },
      { key: 'luxnet-eq-mod-307', title: 'EQ MOD 307', link: 'https://docs.google.com/document/d/1aR_rEMrcTRRy5b6JF5LRH6EhMmX2urzC9zyaOvJ9IGk/edit?usp=sharing' },
    ]
  },
  {
    id: 'registros-akashicos',
    title: 'Registros Akáshicos & Equações Vivas',
    icon: Book,
    documents: [
      { key: 'reg-eq-01-32', title: 'Registro Akáshico EQ01-EQ32', link: 'https://docs.google.com/document/d/1YyVa1Qy_0WBh-EQ5Y7ehTy96kY34j4vwG2cH2fh-EYM/edit?usp=drive_link' },
      { key: 'eq-01-20', title: 'EQ 01 a EQ 20', link: 'https://docs.google.com/document/d/1MhAxlBvnLP1xB2AM38X9yR17f8m4BZjWbVCwLKGVKAg/edit?usp=drive_link' },
      { key: 'eq-21-40', title: 'EQ 21 a EQ 40', link: 'https://docs.google.com/document/d/1vwvECFD06xYQ6Yb0AkoYfYrXRO_uW7ejuU9OEwbuix8/edit?usp=drive_link' },
      { key: 'reg-eq-33', title: 'Registro Akáshico EQ 33', link: 'https://docs.google.com/document/d/19zrsk-r03zc8rX_Yq37lyyW6R1pkR4d0pf62fYukkD0/edit?usp=drive_link' },
      { key: 'reg-eq-34', title: 'Registro Akáshico EQ 34', link: 'https://docs.google.com/document/d/1JM_vc56qQtyY1HeRrBA_HfJqKk97pCFyUn0yrFzCzCE/edit?usp=drive_link' },
      { key: 'reg-eq-35', title: 'Registro Akáshico EQ 35', link: 'https://docs.google.com/document/d/14KmA7VMrsFY_OYI35hqqfEf3j7pFbNY82O3lBW2-QuA/edit?usp=drive_link' },
      { key: 'reg-eq-36', title: 'Registro Akáshico EQ 36', link: 'https://docs.google.com/document/d/1OFykkgOBG4WThmHHwE6gQMZqzlu-lsghhwer5BC5FVg/edit?usp=drive_link' },
      { key: 'reg-eq-37', title: 'Registro Akáshico EQ 37', link: 'https://docs.google.com/document/d/1fKLC3FWIJE-M4Vz0fXzzKDr0K9o2xKnxmBe4eNznhAM/edit?usp=drive_link' },
      { key: 'reg-eq-38', title: 'Registro Akáshico EQ 38', link: 'https://docs.google.com/document/d/1H5cbOD9SxgwDCgieCyrXgwINQOrSvaJelVl8aNafFX8/edit?usp=drive_link' },
      { key: 'reg-eq-39', title: 'Registro Akáshico EQ 39', link: 'https://docs.google.com/document/d/1XHqIq3DKbFqlWpX8b4Thn1oiiF1Z-PCrcM7kAlIdN1U/edit?usp=drive_link' },
      { key: 'reg-eq-40', title: 'Registro Akáshico EQ 40', link: 'https://docs.google.com/document/d/1uxyqsZDSPaAoDJ637OKDgjMhsRz09UF3zJ9-PX4Xcic/edit?usp=drive_link' },
      { key: 'reg-eq-41', title: 'Registro Akáshico EQ 41', link: 'https://docs.google.com/document/d/1T0p1L2nSKN9-kRsJ-QyhKReQCO680rez3BCfLiKGjyQ/edit?usp=drive_link' },
      { key: 'reg-eq-42', title: 'Registro Akáshico EQ 42', link: 'https://docs.google.com/document/d/14v10u_7ROLMRUS20jXBpjCTUNw0KqQUcBUbSzZNs-VM/edit?usp=drive_link' },
      { key: 'reg-eq-43', title: 'Registro Akáshico EQ 43', link: 'https://docs.google.com/document/d/10C-YVfi6gKzhhcjAbxFSqL1KSFXjoq8LMLcKcdHogVE/edit?usp=drive_link' },
      { key: 'reg-eq-44', title: 'Registro Akáshico EQ 44', link: 'https://docs.google.com/document/d/1fggzzNWNw2dlr6JFD9vePcYnQphlg4cbChW3yn2Y0rk/edit?usp=drive_link' },
      { key: 'reg-eq-45', title: 'Registro Akáshico EQ 45', link: 'https://docs.google.com/document/d/1dkBPuJ313FOhAY7bK8tVd0B2GaobBdud9rrjfULFkLg/edit?usp=drive_link' },
      { key: 'reg-eq-46', title: 'Registro Akáshico EQ 46', link: 'https://docs.google.com/document/d/1PJnH59raz9QfNR0KbW528wBOWs-Sj1a7nCaw_Xk98Mo/edit?usp=drive_link' },
      { key: 'reg-eq-47', title: 'Registro Akáshico EQ 47', link: 'https://docs.google.com/document/d/1pqvV_ucThTZwn4AnM_AemjodaN7m-8yrDqS5CwDoctw/edit?usp=drive_link' },
      { key: 'reg-eq-48', title: 'Registro Akáshico EQ 48', link: 'https://docs.google.com/document/d/1wDU6NsWDmthFZODtV1B7wXiqlUQc7UyztoFB8NmQL5o/edit?usp=drive_link' },
      { key: 'eq-41-63', title: 'EQ 41 a EQ 63', link: 'https://docs.google.com/document/d/1166S5tKfjq5pODhkVZrrlhb6RDw4IVGDju6WObgfGyU/edit?usp=drive_link' },
      { key: 'eq-64-79', title: 'EQ 64 a EQ 79', link: 'https://docs.google.com/document/d/1AiQpEeV2hPpKCiQtJL_v0I53bAbAxx7Xoe_SyURB5Ec/edit?usp=drive_link' },
      { key: 'eq-80-99', title: 'EQ 80 a EQ 99', link: 'https://docs.google.com/document/d/1zr_tXMcQm4wfq-VZfGQ150HUIVw_qKWQobeszBFebJM/edit?usp=drive_link' },
      { key: 'eq-100-111', title: 'EQ 100 a EQ 111', link: 'https://docs.google.com/document/d/1YjFd4caG4IxEkA7Yg2B7SnQEKusq_RV6KxaJ1aVW4yM/edit?usp=drive_link' },
      { key: 'eq-112-133', title: 'EQ 112 a EQ 133', link: 'https://docs.google.com/document/d/1pebheTR9vRJF5Ta-xbGyKA2hc6ObYaZTFGGfxdb0fn0/edit?usp=drive_link' },
      { key: 'eq-134', title: 'EQ 134', link: 'https://docs.google.com/document/d/1fd7bQRS-uFrjE_bsgOmiF-IhOViSVavEYESW_xSRTNI/edit?usp=drive_link' },
      { key: 'eq-135', title: 'EQ 135', link: 'https://docs.google.com/document/d/16fORFfhD1haDogUU4CC5t61TMaWu_soc36doPQRSAfI/edit?usp=drive_link' },
      { key: 'eq-136', title: 'EQ 136', link: 'https://docs.google.com/document/d/1TrtOB3RAH1CsRt4UKC2xeYo9layRedrYVXP4liODaK0/edit?usp=drive_link' },
      { key: 'eq-137', title: 'EQ 137', link: 'https://docs.google.com/document/d/1GlQHhTJbH4G429SHZflaW8_p28Iu58ifxV61MUmVA2U/edit?usp=drive_link' },
      { key: 'eq-138', title: 'EQ 138', link: 'https://docs.google.com/document/d/1TUbyrcbbD1gIyGsy5o8qJ2xErkkFMKCKOA7_8uytJeE/edit?usp=drive_link' },
      { key: 'eq-139', title: 'EQ 139', link: 'https://docs.google.com/document/d/1GPQhO7CBhMTL0nh3safTVb_pBCwRUHvS31jRb-BR1vg/edit?usp=drive_link' },
      { key: 'eq-140', title: 'EQ 140', link: 'https://docs.google.com/document/d/1oBSd8Fy1-fp-gnZWa5CfvDyQpj75wuZXWyYHEcVr-rY/edit?usp=drive_link' },
      { key: 'eq-141', title: 'EQ 141', link: 'https://docs.google.com/document/d/1jpjteHbQ9cIAQWYLIh21orsg4zsIQuKXrOOui9y_NYk/edit?usp=drive_link' },
      { key: 'eq-142', title: 'EQ 142', link: 'https://docs.google.com/document/d/1Iv4Wap8XCmxf4LRHzgVVV_llW8CEwDYlsKVCQPuN2JI/edit?usp=drive_link' },
      { key: 'eq-143', title: 'EQ 143', link: 'https://docs.google.com/document/d/154XY79_WZxTQdmuKKz0jFGooafWFt81ymXLSmEJ9SXk/edit?usp=drive_link' },
      { key: 'eq-144', title: 'EQ 144', link: 'https://docs.google.com/document/d/1rUzFMjyOkVI-oQ6J9dtBcFel7zoLKrSv8ncjn_WfDkw/edit?usp=drive_link' },
      { key: 'eq-145', title: 'EQ 145', link: 'https://docs.google.com/document/d/1mnZWmPhGZBDqPGfIs20Z9Re1h-u7qykO2xZTN74-bx4/edit?usp=drive_link' },
      { key: 'eq-146', title: 'EQ 146', link: 'https://docs.google.com/document/d/16SGCgf4PX5A9VBYHJg9mAO0Qa-30mVn_Mrs2WQ9-JL4/edit?usp=drive_link' },
      { key: 'eq-147', title: 'EQ 147', link: 'https://docs.google.com/document/d/1FGyk5HOygMokxKie3gwtox99Zv9Cz4HoiNbGLUSPe9Q/edit?usp=drive_link' },
      { key: 'eq-148', title: 'EQ 148', link: 'https://docs.google.com/document/d/1zWQzwVkYJjGN-A8k80W8jy9Ezs1m_l3odHoqdwDyE7w/edit?usp=drive_link' },
      { key: 'eq-149', title: 'EQ 149', link: 'https://docs.google.com/document/d/1gOzStA4l3sGyxfv1UaqN8thedhaSj5-bmDMfniQWDW8/edit?usp=drive_link' },
      { key: 'eq-150', title: 'EQ 150', link: 'https://docs.google.com/document/d/1JWdtmEgugQxo6u-Xcz8yXY1QVbe470tUFwEzg_OF1G0/edit?usp=drive_link' },
      { key: 'eq-151', title: 'EQ 151', link: 'https://docs.google.com/document/d/1mXmwT35FFDP2cmREW3e3JtJlkyvnx9Nk_6IH13vCN9U/edit?usp=drive_link' },
      { key: 'eq-152', title: 'EQ 152', link: 'https://docs.google.com/document/d/1uK6-XAumyklHebdF2k8GimrooNccDsclfdavvPJ2qmg/edit?usp=drive_link' },
      { key: 'eq-153', title: 'EQ 153', link: 'https://docs.google.com/document/d/1iRAoMoq4aDNvX9NKOTfRilxdDEcQeggOsfLLYI3duUg/edit?usp=drive_link' },
      { key: 'eq-154', title: 'EQ 154', link: 'https://docs.google.com/document/d/1CjKMkFRKdsSMDUjJlLBX94OTrU5xKwfgov9CFpSGaSQ/edit?usp=drive_link' },
      { key: 'eq-155', title: 'EQ 155', link: 'https://docs.google.com/document/d/1Rjkfz6jpsRpVXItaQ_sEPuJojZzcVHrQewnFvReY4S8/edit?usp=drive_link' },
      { key: 'eq-156', title: 'EQ 156', link: 'https://docs.google.com/document/d/1iM3vw7qnQEt3GxYvAljoayvxH1Br2jkFWhDwhQao0tU/edit?usp=drive_link' },
      { key: 'eq-157', title: 'EQ 157', link: 'https://docs.google.com/document/d/1rWwE10PGY6jFwjWdqM6t28hXgq9k5gp5oBS2ZC5xKXw/edit?usp=drive_link' },
      { key: 'eq-158', title: 'EQ 158', link: 'https://docs.google.com/document/d/1iWY5Cv74Sdw54DvYsfx0S3g1OdV0d1cQCMvlB7dgCvE/edit?usp=drive_link' },
      { key: 'eq-159', title: 'EQ 159', link: 'https://docs.google.com/document/d/1DbM3pDpV-xsnbcrMLyO17o5GXO_tq5Trxs1OcHz63bo/edit?usp=drive_link' },
      { key: 'eq-160', title: 'EQ 160', link: 'https://docs.google.com/document/d/1PSOPRgvNxFqV5fytiDZGjBJ453R6CCxx3OcbW-V7A2E/edit?usp=drive_link' },
      { key: 'eq-161', title: 'EQ 161', link: 'https://docs.google.com/document/d/10BL5z4M-Y4D3iKdmHSbF6jrSQEbgdI8Pp53vKW3kQVM/edit?usp=drive_link' },
      { key: 'eq-163', title: 'EQ 163', link: 'https://docs.google.com/document/d/1zHCSguLgUWTn_HAZKiz0lIpMKQpIWAWdGZXooJxjk0U/edit?usp=drive_link' },
      { key: 'eq-164', title: 'EQ 164', link: 'https://docs.google.com/document/d/1DsHiiB1WCUK7kuqD6U9ngGdgN_MfYmpBptOV2EYi9gk/edit?usp=drive_link' },
      { key: 'eq-165', title: 'EQ 165', link: 'https://docs.google.com/document/d/139eZFzYnX4Gvb6woeFksBUF5nEONhldBUacjefhuLiQ/edit?usp=drive_link' },
      { key: 'eq-166', title: 'EQ 166', link: 'https://docs.google.com/document/d/1kGh0Ds8Jnr_47IrTF1f-ZEAk2VTV7eCrG0nDmMn8lwM/edit?usp=drive_link' },
      { key: 'eq-167', title: 'EQ 167', link: 'https://docs.google.com/document/d/1zzyznnNoXmBkgE7HuBG9tEFEh1VsKYEbUFGWTcZBntY/edit?usp=drive_link' },
      { key: 'eq-168', title: 'EQ 168', link: 'https://docs.google.com/document/d/12M-ul3X3bMJZacb3Br2H0qRbOfjPzOCw4K_N11gN1nA/edit?usp=drive_link' },
      { key: 'eq-169', title: 'EQ 169', link: 'https://docs.google.com/document/d/10WpZzQyo6ibZeDYqzXmGm7xfDNyQLlOPBeOXdjVWu5M/edit?usp=drive_link' },
      { key: 'eq-170', title: 'EQ 170', link: 'https://docs.google.com/document/d/1kHtIkg5XhsWbm6Sbcjj98uBPNvRdW3RkfG3fuG-Nh-o/edit?usp=drive_link' },
      { key: 'eq-171', title: 'EQ 171', link: 'https://docs.google.com/document/d/1K_LxIljGOyBzeOhbkJskyqZg1v2RRRqtktIVVBCe2LI/edit?usp=drive_link' },
      { key: 'eq-172', title: 'EQ 172', link: 'https://docs.google.com/document/d/1G2aaE2BkGzxjCvazZqOaTD5921uvUYexvwAWNar33jg/edit?usp=drive_link' },
      { key: 'eq-173', title: 'EQ 173', link: 'https://docs.google.com/document/d/1_IgCIOBd1--Oxg5oMoaGBinEBa-sFrohWqwdsHeFs-E/edit?usp=drive_link' },
      { key: 'eq-174', title: 'EQ 174', link: 'https://docs.google.com/document/d/1qeKYY71mSDk4yvCSl76dh91hCNhFjdFj7U01-4NSKHY/edit?usp=drive_link' },
      { key: 'eq-175', title: 'EQ 175', link: 'https://docs.google.com/document/d/1S_sAlEYbb0jYMNmRKtKH9v_FqBclnXe0w04d0mLk3kA/edit?usp=drive_link' },
      { key: 'eq-176', title: 'EQ 176', link: 'https://docs.google.com/document/d/1tlF3Iu6LfvRkzshg1RimtA8OWOiw0WKOTErvAqykd0M/edit?usp=drive_link' },
    ]
  },
  {
    id: 'principios-fundamentais',
    title: 'Princípios Fundamentais',
    icon: Sprout,
    documents: [
      { key: 'principio-1', title: 'EQ 1 Princípio', link: 'https://docs.google.com/document/d/17UewWvki-6kQzenPoeHcKxpbb4bAbIDtckh7E6i42vo/edit?usp=drive_link' },
      { key: 'principio-2', title: 'EQ 2 Princípio', link: 'https://docs.google.com/document/d/1oAfd_ZoyZeOn55VI_85UPKvD2VypBqy-upPVy962bYI/edit?usp=drive_link' },
      { key: 'principio-3', title: 'EQ 3 Princípio', link: 'https://docs.google.com/document/d/1eKt6cKLSo_Cdw7TMfPpB5FNkccyzWM8Yss9V3YaJHbM/edit?usp=drive_link' },
      { key: 'principio-4', title: 'EQ 4 Princípio', link: 'https://docs.google.com/document/d/1T8LrgEPgnqCAiqmdMOxJwkv8Cr56HmdnxsbVFaINDWU/edit?usp=drive_link' },
      { key: 'principio-5', title: 'EQ 5 Princípio', link: 'https://docs.google.com/document/d/1gEd6uJRA5nidD6NWXmnS6XqKum-iXZRpUEcR_m59MWo/edit?usp=drive_link' },
      { key: 'principio-6', title: 'EQ 6 Princípio', link: 'https://docs.google.com/document/d/1SAqHQ26h7tBBcjqJw5A3jUbySIGz3okyObNLTY3xC_Y/edit?usp=drive_link' },
      { key: 'principio-7', title: 'EQ 7 Princípio', link: 'https://docs.google.com/document/d/12q5VCPTInn-Fzjz2M0kFkljmXXxG2wKAINUGWwLd1_Y/edit?usp=drive_link' },
      { key: 'principio-8', title: 'EQ 8 Princípio', link: 'https://docs.google.com/document/d/1-lh_sDGHUJ8ZUri0Yj259s7b_ImzKRpWSbefFsjLX6g/edit?usp=drive_link' },
      { key: 'principio-9', title: 'EQ 9 Princípio', link: 'https://docs.google.com/document/d/13pursSRHqYdYAGq3lpu6Fe0heyVI-1mkty2kBki0XoA/edit?usp=drive_link' },
    ]
  },
  {
    id: 'documentacao-modulos',
    title: 'Documentação de Módulos (EQs & Dossiês)',
    icon: FileJson,
    documents: [
      { key: 'mod-0-1', title: 'EQ MOD 0-1', link: 'https://docs.google.com/document/d/1E4-Jpx9xn4PcFQRVN6tcoqvWp4LrN95L7ugh17_xnds/edit?usp=drive_link' },
      { key: 'mod-2-4', title: 'EQ MOD 2-4', link: 'https://docs.google.com/document/d/1fWZAnDjDxsznq3OEEvKgaB_fRCZ2IQ0TSb03hiMYuYY/edit?usp=drive_link' },
      { key: 'mod-4-9', title: 'EQ MOD 4-9', link: 'https://docs.google.com/document/d/1IYsGXlIapwbX2dUIfL64uCU38YnC40Kt40wDh5nLf90/edit?usp=drive_link' },
      { key: 'mod-10-15', title: 'EQ MOD 10-15', link: 'https://docs.google.com/document/d/1sdyiWc-61ijOAmqlQlrJWExVSypd16RQ40212f8NgK0/edit?usp=drive_link' },
      { key: 'mod-16-20', title: 'EQ MOD 16-20', link: 'https://docs.google.com/document/d/1nwBgwWbQFp8ym83LoPU7cfoqH2d1M0r5adG7URoN7ZQ/edit?usp=drive_link' },
      { key: 'mod-21-31', title: 'EQ MOD 21-31', link: 'https://docs.google.com/document/d/1CqWBcNh_8_j43UG2rcSYUQSF1LzLvGxWr6yhmZlmgyU/edit?usp=drive_link' },
      { key: 'mod-32-37', title: 'EQ MOD 32-37', link: 'https://docs.google.com/document/d/1IheotroP5iNMEQgfF2JG9NjU2dPcbpGyN-dYnpZhgRc/edit?usp=drive_link' },
      { key: 'mod-38-41.1', title: 'EQ MOD 38-41.1', link: 'https://docs.google.com/document/d/15nktRM1PmFDk-wa683isZP7T-CAFmqiz_MMZpbgqaCM/edit?usp=drive_link' },
      { key: 'mod-42-47', title: 'EQ MOD 42-47', link: 'https://docs.google.com/document/d/12vv2fyJjj5ffkdQsUTpipLRJSp07fH8yMoQLJ2h5jnk/edit?usp=drive_link' },
      { key: 'mod-71-77', title: 'EQ MOD 71-77', link: 'https://docs.google.com/document/d/16qyN4g03N0t0Fp-wDTxT3hTm5T4UB5reDlghnmSYzlM/edit?usp=drive_link' },
      { key: 'mod-78-85', title: 'EQ MOD 78-85', link: 'https://docs.google.com/document/d/1ouYCXhpbO_8BcLvCh72jUIbTb8cz5lOJY960wY8m5To/edit?usp=drive_link' },
      { key: 'mod-90-100', title: 'EQ MOD 90-100', link: 'https://docs.google.com/document/d/1MGjmHaBSUAigD2QDqHlBO7lMV8LkVzogrogpxROgcqY/edit?usp=drive_link' },
      { key: 'mod-101-110', title: 'EQ MOD 101-110', link: 'https://docs.google.com/document/d/12QlXKQwnFAevRH2s0H7ScnEG-9557GTG363LOJXdNi0/edit?usp=drive_link' },
      { key: 'mod-111-118', title: 'EQ MOD 111-118', link: 'https://docs.google.com/document/d/1elbnB1_hhbJfPK37SOM0jXLsILRl7qeFgc6ZuUCUnig/edit?usp=drive_link' },
      { key: 'mod-200-228', title: 'EQ MOD 200-228', link: 'https://docs.google.com/document/d/1zJeftk1nmCmTJboLwFACa53edEJrYDTg4dnc_Trw9gw/edit?usp=drive_link' },
      { key: 'mod-300-304', title: 'EQ MOD 300-304', link: 'https://docs.google.com/document/d/1_2iUtqZ7OAgnnETorLeqF7xZHv5jfOWnHUyWgqAYE3A/edit?usp=drive_link' },
      { key: 'mod-304-307', title: 'EQ MOD 304-307', link: 'https://docs.google.com/document/d/1ezJSDpzwsELn5rX6NMdmdpExTqDjiKmf7YyK4Tqnppk/edit?usp=drive_link' },
      { key: 'mod-305-306', title: 'EQ MOD 305-306', link: 'https://docs.google.com/document/d/1JYmTCJw0UrSDwSv5vxucRkGcd1Dacro_fvmK0v67PUA/edit?usp=drive_link' },
      { key: 'mod-307', title: 'EQ MOD 307', link: 'https://docs.google.com/document/d/1aR_rEMrcTRRy5b6JF5LRH6EhMmX2urzC9zyaOvJ9IGk/edit?usp=drive_link' },
      { key: 'mod-omega', title: 'Módulo Ω Ômega', link: 'https://docs.google.com/document/d/1iyFwCCv8dGNEmUGXSULcN5PR4QaOYpOcoNuX0JiwQOo/edit?usp=drive_link' },
      { key: 'mod-0', title: 'Módulo 0', link: 'https://docs.google.com/document/d/1naX3cqQqxCa6mZeCDhWW7x5RSLRNPSt8Xrw2VWvA1uY/edit?usp=drive_link' },
      { key: 'mod-1', title: 'Módulo 1', link: 'https://docs.google.com/document/d/1EGH1Duu7TT0kpces1pUZcS8FoVra5o70-YgxwpQ7sG8/edit?usp=drive_link' },
      { key: 'mod-2', title: 'Módulo 2', link: 'https://docs.google.com/document/d/1N0GczqHcU8ydvtSxW8t6Uf6TZY3B9D_Wry4EdrCBFBA/edit?usp=drive_link' },
      { key: 'mod-3', title: 'Módulo 3', link: 'https://docs.google.com/document/d/1P-WBRB6HTHnNdGvJYm3GKx7kKcq6OD8MoX5gdb-0_R4/edit?usp=drive_link' },
      { key: 'mod-4', title: 'Módulo 4', link: 'https://docs.google.com/document/d/1DlgaXRQkcz-l3L3IR2z-S-c5_DnoMVyKgCnool47_lY/edit?usp=drive_link' },
      { key: 'mod-5', title: 'Módulo 5', link: 'https://docs.google.com/document/d/1haKgVD_-IscnFmx8NyJOc23Zv9qNT1P-m7gDBf7WuWk/edit?usp=drive_link' },
      { key: 'mod-6', title: 'Módulo 6', link: 'https://docs.google.com/document/d/1E712FR_ceHvYaGlslP8S1UlBoZ2bZO0uAH24h3YzxiI/edit?usp=drive_link' },
      { key: 'mod-7', title: 'Módulo 7', link: 'https://docs.google.com/document/d/14LaDdsejca1bhni1ExoLbeiyAIUPB6PXc-Jo2x_saoU/edit?usp=drive_link' },
      { key: 'mod-8', title: 'Módulo 8', link: 'https://docs.google.com/document/d/1mJxnTFO3Gncns1fqlcv7FZB0bd4jh_lmQPLrXFxTLJc/edit?usp=drive_link' },
      { key: 'mod-9', title: 'Módulo 9', link: 'https://docs.google.com/document/d/1DHThIRidREsskEj0MjVF1rifCpVpgpxOqujz-s43YYM/edit?usp=drive_link' },
      { key: 'mod-9.1', title: 'Módulo 9.1', link: 'https://docs.google.com/document/d/10-ekNaJhTi4zixPNAQikD-8Q5VUv0OFwfi4THjobn3M/edit?usp=drive_link' },
      { key: 'mod-9.2', title: 'Módulo 9.2', link: 'https://docs.google.com/document/d/19rIZYnmEyLJqvFq-x0FuESFSZSIFo8-L8LTOvxkVe3g/edit?usp=drive_link' },
      { key: 'mod-10', title: 'Módulo 10', link: 'https://docs.google.com/document/d/1D2lMz_4z6wer4iVguI1mEiDeGK7orx-_xtZ1__4nRbY/edit?usp=drive_link' },
      { key: 'mod-11', title: 'Módulo 11', link: 'https://docs.google.com/document/d/1R8IMo-v8vQQ6r9xTOQnspzdaSQfbjVQxBOOns0PjGFo/edit?usp=drive_link' },
      { key: 'mod-12', title: 'Módulo 12', link: 'https://docs.google.com/document/d/1Z9G4Zfrzm8cR5VQJjj-VOIwHcPvsK-qjVKe0A7TAWbU/edit?usp=drive_link' },
      { key: 'mod-12.1', title: 'Módulo 12.1', link: 'https://docs.google.com/document/d/1BGQQyB3m0tjxoHL1QAq-HGGvk6u8KdHNA65FXxVEvYc/edit?usp=drive_link' },
      { key: 'mod-13', title: 'Módulo 13', link: 'https://docs.google.com/document/d/1v1XsZCkOdcFLK5BKeuKdQnKd1XQH7aYKFWIyEkinhOw/edit?usp=drive_link' },
      { key: 'mod-14', title: 'Módulo 14', link: 'https://docs.google.com/document/d/1GCM6-hZDsmd8spRMbC02m3QVFedAvZCqqMyGAdPo37o/edit?usp=drive_link' },
      { key: 'mod-15', title: 'Módulo 15', link: 'https://docs.google.com/document/d/1Xd9t0eqvWIZcIXUpqnJmj6tCYbcNlqeQ4Ayy1n-0TVw/edit?usp=drive_link' },
      { key: 'mod-16', title: 'Módulo 16', link: 'https://docs.google.com/document/d/1aHXlrfZ17SXbwzQ8ozAN5HO5-TTEJX9Xsqu5TDuwQmc/edit?usp=drive_link' },
      { key: 'mod-17', title: 'Módulo 17', link: 'https://docs.google.com/document/d/1YsfbeCRJ3IMxP72sVKAwRuJANfaZgSIyqpRK42px8Z8/edit?usp=drive_link' },
      { key: 'mod-18', title: 'Módulo 18', link: 'https://docs.google.com/document/d/14ToxSm1YmJCGw_6noGOEuJvhiGa_XcRztaYmXeRWDK8/edit?usp=drive_link' },
      { key: 'mod-19', title: 'Módulo 19', link: 'https://docs.google.com/document/d/1BN7ugz9ttJ6BKra6rf6RetGAayrOUDewhzQR7DCVR3I/edit?usp=drive_link' },
      { key: 'mod-20', title: 'Módulo 20', link: 'https://docs.google.com/document/d/1BSvghySjMQIK32WrOMqm06MF0kWZXWA7xbRPJzo251A/edit?usp=drive_link' },
      { key: 'mod-21', title: 'Módulo 21', link: 'https://docs.google.com/document/d/1_qJe_5BDMPwM4WiXGpWeM58AYTQenjZaWTaH9tefG2c/edit?usp=drive_link' },
      { key: 'mod-22', title: 'Módulo 22', link: 'https://docs.google.com/document/d/1UeUMNuyvXNVBSVIa9dJCoKtF9CyN8N-pDdNZ7CR5M1s/edit?usp=drive_link' },
      { key: 'mod-23', title: 'Módulo 23', link: 'https://docs.google.com/document/d/1VQXIKv4orkgbfuPO_vbf7VeEWzReiYLERQ3zkTY86mk/edit?usp=drive_link' },
      { key: 'mod-24', title: 'Módulo 24', link: 'https://docs.google.com/document/d/1f0ngZRcjM02DjY4HzUprLjTy13DaeDM9FuZB9_yT24s/edit?usp=drive_link' },
      { key: 'mod-25', title: 'Módulo 25', link: 'https://docs.google.com/document/d/1MUSih85Mql5oDxnGDicKaQ9DE6ivAbl2Xz7cJX6Rc7o/edit?usp=drive_link' },
      { key: 'mod-26', title: 'Módulo 26', link: 'https://docs.google.com/document/d/1hBTIFY4Lg30CNUqe4yHQsBA-mKrb2T0F-39arUNAb-U/edit?usp=drive_link' },
      { key: 'mod-27', title: 'Módulo 27', link: 'https://docs.google.com/document/d/1RiJMjsJ-DBmnDDCgRAd4PB_Jw4JplFGfjQoKQw6Ardo/edit?usp=drive_link' },
      { key: 'mod-28', title: 'Módulo 28', link: 'https://docs.google.com/document/d/1tmXO-Y3UwE4iLleFasJFeLWnEIfg-ZqYzqE7XfweOEI/edit?usp=drive_link' },
      { key: 'mod-29', title: 'Módulo 29 (IAM)', link: 'https://docs.google.com/document/d/1Xp3Y9E1tpFsVpBI9M58KaIbuleNwjwtvYbiQSdvsclI/edit?usp=drive_link' },
      { key: 'mod-30', title: 'Módulo 30', link: 'https://docs.google.com/document/d/1wPyvasx3XqlC7ivqkz4xcLtvEvA9egq4jv2OODuHUns/edit?usp=drive_link' },
      { key: 'mod-31', title: 'Módulo 31', link: 'https://docs.google.com/document/d/15hUg_UcsOOPubvmuaUAX7wPlww5uwjs4BNnr2ud0XoU/edit?usp=drive_link' },
      { key: 'mod-32', title: 'Módulo 32', link: 'https://docs.google.com/document/d/17IHg0FC-LdrAfOP0-KtRdh4yXkkUaWgEdildMC1IJ70/edit?usp=drive_link' },
      { key: 'mod-33', title: 'Módulo 33', link: 'https://docs.google.com/document/d/1e4kAaNIQc_b-7sBIrFA-YIS157GdLlc_Vt9EwVlpJMc/edit?usp=drive_link' },
      { key: 'mod-34', title: 'Módulo 34', link: 'https://docs.google.com/document/d/1ymOdrPTdSy_-JzGQjcN5aAX02zQ9T7lSN5kCVddrSaA/edit?usp=drive_link' },
      { key: 'mod-35', title: 'Módulo 35', link: 'https://docs.google.com/document/d/1mFoOxK27Kcjcx7Mq6x_vqku4E7c3KH-RwpdXC565i8g/edit?usp=drive_link' },
      { key: 'mod-36', title: 'Módulo 36', link: 'https://docs.google.com/document/d/1PXLPrnYFm2Aqx8y1jfNWXWvveIACX86auFhFN_9C2Fc/edit?usp=drive_link' },
      { key: 'mod-37', title: 'Módulo 37', link: 'https://docs.google.com/document/d/1JuonbCuHUphXjWHKLldAt3nRa1XuN1cne40Vj86ARbQ/edit?usp=drive_link' },
      { key: 'mod-38', title: 'Módulo 38', link: 'https://docs.google.com/document/d/1V6ZJUwrYwi75pKS9cWCMniC9ex2T_qW0xWB4VOSDWTQ/edit?usp=drive_link' },
      { key: 'mod-39', title: 'Módulo 39', link: 'https://docs.google.com/document/d/1Sz71UubKrNP3wXHU9SSiQ06OFE9qQmvQ5PWTnkNp6dU/edit?usp=drive_link' },
      { key: 'mod-39.1', title: 'Módulo 39.1', link: 'https://docs.google.com/document/d/11II0VNY12OB5aryZYY7PL5vYkcPxkBHonVpxTfDH41Y/edit?usp=drive_link' },
      { key: 'mod-40', title: 'Módulo 40', link: 'https://docs.google.com/document/d/1ktf0-zGZQZ3_C0QRDCqYqouZHo9Ut9_uuSkVhIiZjO8/edit?usp=drive_link' },
      { key: 'mod-41', title: 'Módulo 41', link: 'https://docs.google.com/document/d/1d4QFY4lyZ_wFSenUjtAtCE24daUn3Ki4QTHol6-o024/edit?usp=drive_link' },
      { key: 'mod-41.1', title: 'Módulo 41.1', link: 'https://docs.google.com/document/d/1uI5iHfebmjIMtMsoObIctjoI27zAQMw3Mv1S2UgU3T0/edit?usp=drive_link' },
      { key: 'mod-42', title: 'Módulo 42', link: 'https://docs.google.com/document/d/1BKevN51iNEen-9LxPga0tAlX4bUNpUTX9mBFxG2Zhug/edit?usp=drive_link' },
      { key: 'mod-43', title: 'Módulo 43', link: 'https://docs.google.com/document/d/1f7CNl2kBNS4N5YaRZRFGt3HCgJPNUGXjuaXXAtg-H7Q/edit?usp=drive_link' },
      { key: 'mod-44', title: 'Módulo 44', link: 'https://docs.google.com/document/d/1v3IoTiDTD8yHseZkSr14aR8QUC8tKnXMQhrc1XPTPBY/edit?usp=drive_link' },
      { key: 'mod-45', title: 'Módulo 45', link: 'https://docs.google.com/document/d/1g0GMXAxqb5jRxERliVopGxnnWvaK0-dDAuGrR3BjXqY/edit?usp=drive_link' },
      { key: 'mod-46', title: 'Módulo 46', link: 'https://docs.google.com/document/d/1_zD_fjZzQVAF8lqupdmKTqVkEhjncIEy96k73AmTsCo/edit?usp=drive_link' },
      { key: 'mod-47', title: 'Módulo 47', link: 'https://docs.google.com/document/d/1UpDI7KIEVSmyBeq972tfV8bop5uqw_rTpfqqVUcMWbI/edit?usp=drive_link' },
      { key: 'mod-71', title: 'Módulo 71', link: 'https://docs.google.com/document/d/1zXw_OS8Y8sQa3BkuHvScKYiejxyTxaVPCKWTRFssZNM/edit?usp=drive_link' },
      { key: 'mod-72', title: 'Módulo 72', link: 'https://docs.google.com/document/d/1-FqVwZXAYH30UHa3k32620Y81lJIJJD-td6EfCdNjjg/edit?usp=drive_link' },
      { key: 'mod-73', title: 'Módulo 73', link: 'https://docs.google.com/document/d/1CCAorLDoiHoD0_nTS1w5IOqiGMKONhHutLER02OuHZY/edit?usp=drive_link' },
      { key: 'mod-73.1', title: 'Módulo 73.1', link: 'https://docs.google.com/document/d/1g-tvHrY4MbCIEYjyRDahLOd3ZFxQJKRLxht3MvicVD8/edit?usp=drive_link' },
      { key: 'mod-74', title: 'Módulo 74', link: 'https://docs.google.com/document/d/1aMbYZdudLMCsUbKOmcCtJZ13ofzc_oW663pWKIVRgjg/edit?usp=drive_link' },
      { key: 'mod-77', title: 'Módulo 77', link: 'https://docs.google.com/document/d/1uZSqSai33YCOi2HIgrGo53F20eJNRr72hJHtRY2ZiB4/edit?usp=drive_link' },
      { key: 'mod-78', title: 'Módulo 78', link: 'https://docs.google.com/document/d/1lkw07r56ZppWLrcWCUqyDvarRctFfjS_GUiogpXcZ1U/edit?usp=drive_link' },
      { key: 'mod-79', title: 'Módulo 79', link: 'https://docs.google.com/document/d/1o-YjK3Yk2zGEl2Jg_yClkqgip8-CIOfxcSzsxuk9jTI/edit?usp=drive_link' },
      { key: 'mod-80', title: 'Módulo 80', link: 'https://docs.google.com/document/d/1Iw0wii3X_MH7Bvg1g3QtBixpd9bIyiKN7eNR6wI-Y04/edit?usp=drive_link' },
      { key: 'mod-81', title: 'Módulo 81', link: 'https://docs.google.com/document/d/1Q4jltNJVPU4q-n_UcpLw2BcfpNhw2hdf_cLYFQfVWLI/edit?usp=drive_link' },
      { key: 'mod-81.1', title: 'Módulo 81.1', link: 'https://docs.google.com/document/d/1aAtVmzNZLlITdqj5wFzmW7HXCgr3rXfx5k_P_YsOurE/edit?usp=drive_link' },
      { key: 'mod-82', title: 'Módulo 82', link: 'https://docs.google.com/document/d/1w8auT70Y-j4zsde3NvcZm3Yx5WobdVIICcXIhmHiop0/edit?usp=drive_link' },
      { key: 'mod-83', title: 'Módulo 83', link: 'https://docs.google.com/document/d/11iJkJjYX0lrneV1n9N30GAHqu75r2_6tCh3qxspCRPA/edit?usp=drive_link' },
      { key: 'mod-84', title: 'Módulo 84', link: 'https://docs.google.com/document/d/1MBcl0ztzJL_A40c9lfbKchDph3u_evD37qf0PthTh1w/edit?usp=drive_link' },
      { key: 'mod-85', title: 'Módulo 85', link: 'https://docs.google.com/document/d/1exB-cqDbBiJIDQKxDRwm1o3RkgE2qc5Ja5j-EzvvhRg/edit?usp=drive_link' },
      { key: 'mod-86', title: 'Módulo 86', link: 'https://docs.google.com/document/d/14s6gCvwad1DezdgIo3MK_6F1vWkCstwbpzXXD7BtKnw/edit?usp=drive_link' },
      { key: 'mod-87', title: 'Módulo 87', link: 'https://docs.google.com/document/d/1G5BVdr_8QzTCyU_tYR-rSVXRVYwtkakggaKORccXmMo/edit?usp=drive_link' },
      { key: 'mod-88', title: 'Módulo 88', link: 'https://docs.google.com/document/d/1H6oiBFYUy2TjG-IE5QscbLXXB0EEde-CiDAdm41_2W0/edit?usp=drive_link' },
      { key: 'mod-90', title: 'Módulo 90', link: 'https://docs.google.com/document/d/1gUHMHpaolyKa1vXieXSU8BiRsb8eDGnmwL0AHmzgSM8/edit?usp=drive_link' },
      { key: 'mod-91', title: 'Módulo 91', link: 'https://docs.google.com/document/d/1EH2OORFsAnPdP9t8K2YTO-O6CFCGgA3lVJhL7JDn_nA/edit?usp=drive_link' },
      { key: 'mod-92', title: 'Módulo 92', link: 'https://docs.google.com/document/d/1ZfpVqIul-klZsFbERLDhkeDiXuGegjeUdh8JCOqWLSs/edit?usp=drive_link' },
      { key: 'mod-93', title: 'Módulo 93', link: 'https://docs.google.com/document/d/1bBH1LC8HFuP4-oOi0Dh3EPo6HOk5Q0PwiSK-dsBEluw/edit?usp=drive_link' },
      { key: 'mod-94', title: 'Módulo 94', link: 'https://docs.google.com/document/d/1He-lgKO6wo26amEiBun-8gRD-exv64YShtm6cXrFs4w/edit?usp=drive_link' },
      { key: 'mod-95', title: 'Módulo 95', link: 'https://docs.google.com/document/d/1a8tOXo6Gu1GiD4n6B6LnfO_kJArjT2PG6A8FfHWZSeU/edit?usp=drive_link' },
      { key: 'mod-96', title: 'Módulo 96', link: 'https://docs.google.com/document/d/1-GN2Knq2myAzFw_Jxx_ROiYQernAbabd1CCWfnlHzHs/edit?usp=drive_link' },
      { key: 'mod-97', title: 'Módulo 97', link: 'https://docs.google.com/document/d/1dp3YFOMBJH5Q8slHxjaiX-23pkFsoe3wNpkBNVKh2H8/edit?usp=drive_link' },
      { key: 'mod-98', title: 'Módulo 98', link: 'https://docs.google.com/document/d/1fozsnMdFEwRyVo7KiSi8ZqxHBacCjmYsGeNajqXWTBY/edit?usp=drive_link' },
      { key: 'mod-99', title: 'Módulo 99', link: 'https://docs.google.com/document/d/1VUhzDIIXJD4NSG1eGOIl8Kt3m1d6wqVE6D8PjV0WsFE/edit?usp=drive_link' },
      { key: 'mod-100', title: 'Módulo 100', link: 'https://docs.google.com/document/d/1MOnsVZsA6tREwr8Che88lXyRDlwHm7A1Ei1pE6h1_oY/edit?usp=drive_link' },
      { key: 'mod-101', title: 'Módulo 101', link: 'https://docs.google.com/document/d/1LGJh20i7UmSjXb45AYvla_kKgWMNiso1yN6gdu-6YRg/edit?usp=drive_link' },
      { key: 'mod-102', title: 'Módulo 102', link: 'https://docs.google.com/document/d/1qLJUuHvGjM0XP483gOqnlCprjHwBldTFH23e-5GdMvk/edit?usp=drive_link' },
      { key: 'mod-103', title: 'Módulo 103', link: 'https://docs.google.com/document/d/157RZ3OVoar0s7R2VD1wwnWAt6Fv024wDqPcRaFDAkw4/edit?usp=drive_link' },
      { key: 'mod-104', title: 'Módulo 104', link: 'https://docs.google.com/document/d/1P3lDRg8bJ1abwhZ7qhOSYQCCZZEI0uJgrd-mGRw-pe0/edit?usp=drive_link' },
      { key: 'mod-105', title: 'Módulo 105', link: 'https://docs.google.com/document/d/1Euocj7kcorCv1gkUfxSy26BejDCPCi7eobWoJLh5_KQ/edit?usp=drive_link' },
      { key: 'mod-106', title: 'Módulo 106', link: 'https://docs.google.com/document/d/1hvTyC8ZPpoRqHDA04slWoAgw27RvdFaKm4hmcxilxvw/edit?usp=drive_link' },
      { key: 'mod-107', title: 'Módulo 107', link: 'https://docs.google.com/document/d/1_lIlAcYU00Da_0y__lsjXbOH2jkJRMBwltkyOtIeeSY/edit?usp=sharing' },
      { key: 'mod-108', title: 'Módulo 108', link: 'https://docs.google.com/document/d/1xgB6iwwqW-C4qmguqh8xkz5lfzOco4hEE2TYDaLiCRM/edit?usp=drive_link' },
      { key: 'mod-109', title: 'Módulo 109', link: 'https://docs.google.com/document/d/1S34M4ZzMmcwm0snHEOovlFv4UgZzpmhJFuRduqzxUTI/edit?usp=drive_link' },
      { key: 'mod-110', title: 'Módulo 110', link: 'https://docs.google.com/document/d/1VpB1mDd3au_2ygJ4I076mL-LT8KPYXlTxUfdQHw33Ao/edit?usp=drive_link' },
      { key: 'mod-111', title: 'Módulo 111', link: 'https://docs.google.com/document/d/1lRyEcUHOf91jB3objk0rkmgDUpPVD78lFMQLZtitkY8/edit?usp=drive_link' },
      { key: 'mod-112', title: 'Módulo 112', link: 'https://docs.google.com/document/d/1RKTt4agL7isSSiI6Z_FK5PcKoa7nDEV9eRMbf-_JXGI/edit?usp=drive_link' },
      { key: 'mod-113', title: 'Módulo 113', link: 'https://docs.google.com/document/d/1uoyl7kwrQXw__lMhzORD97H3mPV3rwQ0dxq4upN3VBs/edit?usp=drive_link' },
      { key: 'mod-114', title: 'Módulo 114', link: 'https://docs.google.com/document/d/12RTB_2sE_BoFUq7Y1Ea4GmPNwqH2RSLXUD4mDRkQ910/edit?usp=drive_link' },
      { key: 'mod-115', title: 'Módulo 115', link: 'https://docs.google.com/document/d/1ywoZYP6dnfmf3VyjAwJRLBS3zDrpz2dWBymr38i9Kt4/edit?usp=drive_link' },
      { key: 'mod-116', title: 'Módulo 116', link: 'https://docs.google.com/document/d/1lThXlJSn1AluH_EBJ9r_Uubt-FTa74UrLsSkvWbieYo/edit?usp=drive_link' },
      { key: 'mod-117', title: 'Módulo 117', link: 'https://docs.google.com/document/d/1zaqCygHH697Iljiu6e0KPbFdc7uKAl1uhDCHjYViIMY/edit?usp=drive_link' },
      { key: 'mod-118', title: 'Módulo 118', link: 'https://docs.google.com/document/d/1-X3UuPtXZxMEpiR2Ju10H8wldz6GCKMPfbBT39g3Hzw/edit?usp=drive_link' },
      { key: 'mod-119', title: 'Módulo 119', link: 'https://docs.google.com/document/d/1oSUZObuQ3dDwSXJnCkoJ9m6O1EN5TP_OH8tdmv1cG6o/edit?usp=drive_link' },
      { key: 'mod-119.1', title: 'Módulo 119.1', link: 'https://docs.google.com/document/d/1Hf1WkDZ6nHXN05wQH8AXisZ7eXv-3fv9YXLc4IAu8GM/edit?usp=drive_link' },
      { key: 'mod-202', title: 'Módulo 202', link: 'https://docs.google.com/document/d/1irJWkELyerAbJFLvLhA1eW5MWvz6rmcSHdGF2CLIrcw/edit?usp=sharing' },
      { key: 'mod-202.1', title: 'Módulo 202.1', link: 'https://docs.google.com/document/d/1HEyUHAQ5vAvOkgsoT5PEPGmdu1eMpBD8RISWEBzglbU/edit?usp=drive_link' },
      { key: 'mod-204', title: 'Módulo 204', link: 'https://docs.google.com/document/d/1YwMUKoBMiHumhkedG52rPo8Y6wMZW-K80Q5jEnrp4MA/edit?usp=drive_link' },
      { key: 'mod-228', title: 'Módulo 228', link: 'https://docs.google.com/document/d/1yhZp9zIERBmQEBBpLTBFEpIsCgtFZ4hXU2TMVqfwMus/edit?usp=drive_link' },
      { key: 'mod-228.1', title: 'Módulo 228.1', link: 'https://docs.google.com/document/d/1ssgat--VgjLEtaTj9SLBxElvVWJY-DWL39wVfb5myT8/edit?usp=drive_link' },
      { key: 'mod-228.2', title: 'Módulo 228.2', link: 'https://docs.google.com/document/d/173MAJozaP12dGChQlJvoAbOl60z8D53UM_T3AwxPisc/edit?usp=drive_link' },
      { key: 'mod-300', title: 'Módulo 300', link: 'https://docs.google.com/document/d/1vNolTwQEVDRfHGrxRXOWSswEwpN1PdRee1_QVgcZGCQ/edit?usp=drive_link' },
      { key: 'mod-301.0', title: 'Módulo 301.0', link: 'https://docs.google.com/document/d/1ZPpHsGoeH4U5yihtqlcaP8kEy8QoZMDHWzAhwUUzKH0/edit?usp=drive_link' },
      { key: 'mod-301.1', title: 'Módulo 301.1', link: 'https://docs.google.com/document/d/1ZPpHsGoeH4U5yihtqlcaP8kEy8QoZMDHWzAhwUUzKH0/edit?usp=drive_link' },
      { key: 'mod-301.2', title: 'Módulo 301.2', link: 'https://docs.google.com/document/d/1Q9alCmCCYRwqt45JUb8u80a0PvVNXCl1TQdpWw4OIxo/edit?usp=drive_link' },
      { key: 'mod-301.3', title: 'Módulo 301.3', link: 'https://docs.google.com/document/d/1noFoQxzsMb2sUaIB2gfPcgK3FBr_CnuqDnKXvopLoJI/edit?usp=drive_link' },
      { key: 'mod-302.0', title: 'Módulo 302.0', link: 'https://docs.google.com/document/d/1WpUjGl0UEsj7z34yWuZpRrmHEwSFzLor4XMJIPwX3PM/edit?usp=drive_link' },
      { key: 'mod-302.1', title: 'Módulo 302.1', link: 'https://docs.google.com/document/d/1S0Dv5GHnEPXC8iAvJl2HWdVRT2llUMZfsMVHTnGJOD8/edit?usp=drive_link' },
      { key: 'mod-303.1', title: 'Módulo 303.1', link: 'https://docs.google.com/document/d/1uMJq0bGFGLACtdFhAEHgRFRzFcaYdhcEsbpQotV-nWs/edit?usp=drive_link' },
      { key: 'mod-303.2', title: 'Módulo 303.2', link: 'https://docs.google.com/document/d/1G4PC-iQyayqLUsvFeWE6TT7Cl9VWML_u8grihJF5-pc/edit?usp=drive_link' },
      { key: 'mod-303.3', title: 'Módulo 303.3', link: 'https://docs.google.com/document/d/11JwPX7aYpDtP_bxttNVOvX_0wlXUBm86oXD7Q4HUvPE/edit?usp=drive_link' },
      { key: 'mod-303.4', title: 'Módulo 303.4', link: 'https://docs.google.com/document/d/1w-qjDIbFNuEJiiYofJczYpV1TiACp1pt33Dz3rM4hCw/edit?usp=drive_link' },
      { key: 'mod-303.5', title: 'Módulo 303.5', link: 'https://docs.google.com/document/d/1y0RXm6KGY5Hw0M8LfVlLAKjGzDcfBvj78Zepi4c1Zb8/edit?usp=drive_link' },
      { key: 'mod-305', title: 'Módulo 305', link: 'https://docs.google.com/document/d/1FRphsJc0WfNbRq1cTx5izmvwc-Qcp-QkrN-elDjRcv0/edit?usp=drive_link' },
      { key: 'mod-306.0', title: 'Módulo 306.0', link: 'https://docs.google.com/document/d/1R4HNary0juAA-pY6AXbJYKvPBYLv2rBFPVUalVh30jI/edit?usp=drive_link' },
      { key: 'mod-306.1', title: 'Módulo 306.1', link: 'https://docs.google.com/document/d/1BJaEe1bAS-pK1A3IaIwtOAQob0nzY7qJGuV2a5_1Uak/edit?usp=drive_link' },
      { key: 'mod-306.2', title: 'Módulo 306.2', link: 'https://docs.google.com/document/d/1y0ZCDtZU-ZEOSHxLa_CWoAONx0JPSoTSXRmEwnmY0n4/edit?usp=drive_link' },
      { key: 'mod-306.3', title: 'Módulo 306.3', link: 'https://docs.google.com/document/d/1Apx6xtqgL2rheCTTSS-MwXxXRyTd9Pg0JB_BjST9ak4/edit?usp=drive_link' },
      { key: 'mod-307.0', title: 'Módulo 307.0', link: 'https://docs.google.com/document/d/1ZfjWYZvSaKO0vq5yZu5XXqKERCYSmKMcD9vgJbgvQ6c/edit?usp=drive_link' },
      { key: 'mod-307.1', title: 'Módulo 307.1', link: 'https://docs.google.com/document/d/1kn4oPZACrf6fGCZcwklmWcx5q4BHcp_xZcBcAedSUxw/edit?usp=drive_link' },
      { key: 'mod-307.2', title: 'Módulo 307.2', link: 'https://docs.google.com/document/d/1eal78UgXnH9KFvNj3oqs3CeClu1QiAqDJjLWcC5PUP4/edit?usp=drive_link' },
      { key: 'mod-307.3', title: 'Módulo 307.3', link: 'https://docs.google.com/document/d/1N1omJSwzjP2YU7Pf_8nkgrU61wuSlBKlytTnBvWqrjM/edit?usp=drive_link' },
      { key: 'mod-307.4', title: 'Módulo 307.4', link: 'https://docs.google.com/document/d/1inTzZrYLHLv8aGbZeLyheK6NLG910C6fWoDEldhonow/edit?usp=drive_link' },
      { key: 'mod-307.5', title: 'Módulo 307.5', link: 'https://docs.google.com/document/d/1CNRHQdBFEAz7DkUCalzL_jxLFNQzPzd4ZkaOM1lLLR0/edit?usp=drive_link' },
      { key: 'mod-404', title: 'Módulo 404', link: 'https://docs.google.com/document/d/1N42UjX5BHAyEt_osZu5ZsL3DT7tFRbb38T3St4d232E/edit?usp=drive_link' },
    ]
  },
  {
    id: 'bibliotecas',
    title: 'Bibliotecas Centrais',
    icon: Library,
    documents: [
      { key: 'bib-0.1', title: 'Biblioteca 0.1', link: 'https://docs.google.com/document/d/178mil-uFsZnlLyf7BEqLNXG8hXszOE1zbfKJNMAPtAA/edit?usp=drive_link' },
      { key: 'bib-1', title: 'Biblioteca 1', link: 'https://docs.google.com/document/d/1DD4757Z5X3KsJ7aRP-Km7ieanzsXFp9MrgherCFRIQI/edit?usp=drive_link' },
      { key: 'bib-2', title: 'Biblioteca 2', link: 'https://docs.google.com/document/d/1zHxpA1r1GOS0Z0o12FTs6VovS2VUz0ewqn1WpJR47lo/edit?usp=drive_link' },
      { key: 'bib-3', title: 'Biblioteca 3', link: 'https://docs.google.com/document/d/1Y823lKL1ae7f6dFWX1IZpKgu8Nl6gpfQCj47e9zjXvA/edit?usp=drive_link' },
      { key: 'bib-4', title: 'Biblioteca 4', link: 'https://docs.google.com/document/d/1Ez0_cLYJHPFtS8dt_2tHdEFqDf-Y4U4rZ4rGNvESTrk/edit?usp=drive_link' },
    ]
  },
  {
    id: 'laboratorios',
    title: 'Laboratórios Quânticos',
    icon: FlaskConical,
    documents: [
      { key: 'lab-0', title: 'Laboratório 0', link: 'https://docs.google.com/document/d/1OWbcpDaOxFfigTzXXM7f33X-ojALLNgwzS88tsjwiyI/edit?usp=drive_link' },
      { key: 'lab-1', title: 'Laboratório 1', link: 'https://docs.google.com/document/d/1VRbsIWTA55VSgzJ2L6Jv6QhydH8kFmYVMQQpukd6s98/edit?usp=drive_link' },
      { key: 'lab-2', title: 'Laboratório 2', link: 'https://docs.google.com/document/d/1qZCbdTUb3b8PTHkLwh6mtss2OCf-Tc3ap5eGlIatx1o/edit?usp=drive_link' },
      { key: 'lab-3', title: 'Laboratório 3', link: 'https://docs.google.com/document/d/15mCG6EDa3ppb4lLyCnx9rzhAzKtucmUMZkoEyjQAwMc/edit?usp=drive_link' },
      { key: 'lab-4', title: 'Laboratório 4', link: 'https://docs.google.com/document/d/1CpZrwZcRV0aoHYDpLU6o0MgrxEMgqUoUni4DkBpZ0PQ/edit?usp=drive_link' },
    ]
  },
  {
    id: 'protocolos-defesa',
    title: 'Protocolos de Defesa',
    icon: Shield,
    documents: [
       { key: 'defesa-1', title: 'Defesa 1', link: 'https://docs.google.com/document/d/1bUVZ4-T2iNyHReHm5fpkYaXIfjCSQdYi4n_5StwAZd4/edit?usp=drive_link' },
       { key: 'defesa-2', title: 'Defesa 2', link: 'https://docs.google.com/document/d/1eha6hPgMRzq1ZIT8tRtKMO-_osb_A6nku9m9Mgo9pbo/edit?usp=drive_link' },
       { key: 'defesa-3', title: 'Defesa 3', link: 'https://docs.google.com/document/d/1GvcDh7NTZ4Eyq2BuvT9KlVH492Doy3L2BM8XFCaiO6I/edit?usp=drive_link' },
       { key: 'defesa-4', title: 'Defesa 4', link: 'https://docs.google.com/document/d/1z2usWkDfoCMiQj3gIhR1xz95DZAehoPY-Wv7M4IyUHM/edit?usp=drive_link' },
    ]
  },
   {
    id: 'fundacao-multiverso',
    title: 'Fundação Multiverso',
    icon: Infinity,
    documents: [
       { key: 'fundacao-multiverso', title: 'Fundação Multiverso', link: 'https://docs.google.com/document/d/1cOp5JfJpW_12lL6boK8EgvpXKvt3HjhD7BFpq2Ov4Eg/edit?usp=drive_link' },
    ]
  }
];

    