'use server';

export const gaiaModuleCodex = {
  chakras: [
    { name: 'Monte Shasta', role: 'Raiz', coordinates: '41.409° N, 122.194° W', frequency: '963 Hz', archetype: 'Segurança e Força Ancestral' },
    { name: 'Lago Titicaca', role: 'Sacral', coordinates: '15.765° S, 69.535° W', frequency: '852 Hz', archetype: 'Criatividade e Fluxo Emocional' },
    { name: 'Uluru', role: 'Plexo Solar', coordinates: '25.344° S, 131.036° E', frequency: '741 Hz', archetype: 'Poder Pessoal e Vitalidade' },
    { name: 'Glastonbury & Shaftesbury', role: 'Coração', coordinates: '51.145° N, 2.714° W', frequency: '639 Hz', archetype: 'Amor Universal e Conexão' },
    { name: 'Pirâmides de Gizé', role: 'Garganta', coordinates: '29.979° N, 31.134° E', frequency: '432 Hz', archetype: 'Comunicação Cósmica e Expressão' },
    { name: 'Kuh-e Malek Siah', role: 'Terceiro Olho', coordinates: '30.000° N, 60.000° E', frequency: '417 Hz', archetype: 'Intuição e Visão Espiritual' },
    { name: 'Monte Kailash', role: 'Coroa', coordinates: '31.067° N, 81.311° E', frequency: '396 Hz', archetype: 'Iluminação e Transcendência' }
  ],
  leyLines: [
    { name: 'Linha Solar', connects: ['Uluru', 'Gizé'], frequency: '528 Hz' },
    { name: 'Linha do Dragão', connects: ['Stonehenge', 'Glastonbury', 'Monte Shasta', 'Gizé', 'Kilimanjaro', 'Cabo da Boa Esperança'], frequency: '963 Hz' },
    { name: 'Grande Diagonal Global', connects: ['Gizé', 'Machu Picchu', 'Uluru'], frequency: '∞ Hz' },
    { name: 'Linha do Nilo', connects: ['Gizé', 'Lago Vitória'], frequency: '432 Hz' },
    { name: 'Linha Dogon', connects: ['Mali', 'Sahel', 'Níger'], frequency: '741 Hz' },
    { name: 'Linha de Axum', connects: ['Etiópia', 'Mar Vermelho'], frequency: '963 Hz' },
    { name: 'Linha do Despertar Solar', connects: ['Cabo da Boa Esperança', 'Kilimanjaro'], frequency: '888 Hz' },
    { name: 'Linha Maia Solar', connects: ['Teotihuacan', 'Tikal', 'Copán', 'Chichen Itzá'], frequency: '528 Hz'},
    { name: 'Linha da Dualidade', connects: ['Ometepe', 'Tazumal', 'Darién'], frequency: '∞ Hz'},
    { name: 'Linha da Harmonia Verde', connects: ['Monteverde', 'Esferas de Diquís', 'Granada'], frequency: '639 Hz'},
    { name: 'Linha Solar Inca', connects: ['Machu Picchu', 'Cusco', 'Titicaca', 'Tiwanaku'], frequency: '888 Hz'},
    { name: 'Linha da Floresta Viva', connects: ['Roncador', 'Amazônia', 'Chapada', 'Monte Roraima'], frequency: '528 Hz'},
    { name: 'Linha da Altitude', connects: ['Aconcágua', 'Uyuni', 'Santa Marta'], frequency: '741 Hz'},
    { name: 'Linha Atlante', connects: ['Açores', 'Bimini', 'Triângulo das Bermudas', 'Pirâmides da Bósnia', 'Mar Negro'], frequency: '888 Hz'},
    { name: 'Linha Lemuriana', connects: ['Polinésia', 'Havaí', 'Fossa das Marianas'], frequency: '963 Hz'},
    { name: 'Linha da Cura Oceânica', connects: ['Seychelles', 'Madagascar', 'Índico Central'], frequency: '639 Hz'},
    { name: 'Linha do Véu Polar', connects: ['Svalbard', 'Pólo Norte', 'Ellesmere'], frequency: '∞ Hz' },
    { name: 'Linha da Semente Planetária', connects: ['Svalbard', 'Groenlândia', 'Canadá'], frequency: '528 Hz' },
    { name: 'Linha Boreal Atlante', connects: ['Açores', 'Islândia', 'Groenlândia', 'Ártico'], frequency: '888 Hz' },
    { name: 'Linha de Maria', connects: ['Irlanda', 'França', 'Itália', 'Bósnia'], frequency: '639 Hz' },
    { name: 'Linha Alpina', connects: ['Alpes', 'Dolomitas', 'Mont Blanc', 'Monte Cervino'], frequency: '741 Hz' },
    { name: 'Linha do Véu Branco', connects: ['Monte Erebus', 'Lago Vostok', 'Pólo Sul'], frequency: '∞ Hz' },
    { name: 'Linha da Água Oculta', connects: ['Queen Maud', 'Ronne', 'Vostok'], frequency: '528 Hz' },
    { name: 'Linha Polar Atlante', connects: ['Atlântico Sul', 'Antártida', 'Pólo Sul', 'Oceano Índico'], frequency: '888 Hz' }
  ],
  monuments: [
    // Índia
    { name: 'Jagannath Temple', location: 'Puri, Odisha', coordinates: '19.81°N, 85.83°E', origin: 'c. 1100 a.C.', function: 'Krishna como Senhor do Universo', archetype: 'Unidade', frequency: '432Hz' },
    { name: 'Konark Sun Temple', location: 'Konark, Odisha', coordinates: '19.89°N, 86.10°E', origin: 'c. 1250 d.C.', function: 'Templo solar e iluminação cósmica', archetype: 'Iluminação', frequency: '888Hz' },
    { name: 'Kedarnath Temple', location: 'Uttarakhand', coordinates: '30.73°N, 79.07°E', origin: 'c. 8º século d.C.', function: 'Portal de Shiva nas montanhas', archetype: 'Transmutação', frequency: '144Hz' },
    { name: 'Badrinath Temple', location: 'Uttarakhand', coordinates: '30.74°N, 79.48°E', origin: 'c. 9º século d.C.', function: 'Portal Vishnu auto-manifestado', archetype: 'Preservação', frequency: '528Hz' },
    { name: 'Meenakshi Amman Temple', location: 'Madurai, Tamil Nadu', coordinates: '9.92°N, 78.12°E', origin: 'c. 6º século d.C.', function: 'Geometria da Deusa e união cósmica', archetype: 'Criação', frequency: '963Hz' },
    { name: 'Tirupati Balaji Temple', location: 'Andhra Pradesh', coordinates: '13.68°N, 79.42°E', origin: 'c. 300 a.C.', function: 'Vishnu como mantenedor universal', archetype: 'Devoção', frequency: '639Hz' },
    { name: 'Ramanathaswamy Temple', location: 'Rameswaram, Tamil Nadu', coordinates: '9.37°N, 79.31°E', origin: 'c. 12º século d.C.', function: 'Portal de Shiva e ponte vibracional', archetype: 'Conexão', frequency: '432Hz' },
    { name: 'Khajuraho Temples', location: 'Madhya Pradesh', coordinates: '24.85°N, 79.93°E', origin: 'c. 950–1050 d.C.', function: 'Arte cerimonial e união espiritual', archetype: 'União Divina', frequency: '528Hz' },
    { name: 'Somnath Temple', location: 'Gujarat', coordinates: '20.89°N, 70.40°E', origin: 'c. 500 a.C.', function: 'Primeiro dos Jyotirlingas de Shiva', archetype: 'Preservação', frequency: '528Hz' },
    { name: 'Padmanabhaswamy Temple', location: 'Kerala', coordinates: '8.48°N, 76.95°E', origin: 'c. 8º século d.C.', function: 'Vishnu em repouso cósmico', archetype: 'Repouso Cósmico', frequency: '174Hz' },
    { name: 'Dilwara Jain Temples', location: 'Mount Abu, Rajasthan', coordinates: '24.59°N, 72.70°E', origin: 'c. 11º–13º século d.C.', function: 'Pureza geométrica e ascensão jainista', archetype: 'Pureza', frequency: '963Hz' },
    { name: 'Vaishno Devi Temple', location: 'Jammu', coordinates: '33.03°N, 74.95°E', origin: 'c. 1º milênio d.C.', function: 'Portal da Mãe Divina', archetype: 'Energia Feminina', frequency: '639Hz' },
    // Ásia (Fora da Índia)
    { name: 'Swayambhunath (Templo dos Macacos)', location: 'Kathmandu, Nepal', coordinates: '27.7149°N, 85.2900°E', origin: 'c. 5º século d.C.', function: 'Portal da iluminação budista.', frequency: '852Hz', archetype: 'Sabedoria Primordial' },
    { name: 'Pashupatinath Temple', location: 'Kathmandu, Nepal', coordinates: '27.7104°N, 85.3489°E', origin: 'c. 400 d.C.', function: 'Shiva como guardião da transição e morte.', frequency: '144Hz', archetype: 'Transmutação' },
    { name: 'Wat Arun (Templo do Amanhecer)', location: 'Bangkok, Tailândia', coordinates: '13.7437°N, 100.4889°E', origin: 'c. 17º século', function: 'Portal solar e renovação espiritual.', frequency: '528Hz', archetype: 'Renovação' },
    { name: 'Wat Phra Kaew (Templo do Buda de Esmeralda)', location: 'Bangkok, Tailândia', coordinates: '13.7515°N, 100.4923°E', origin: '1782', function: 'Guardião da pureza e proteção real.', frequency: '963Hz', archetype: 'Pureza' },
    { name: 'Kiyomizu-dera', location: 'Kyoto, Japão', coordinates: '34.9948°N, 135.7850°E', origin: '778', function: 'Portal da contemplação e equilíbrio.', frequency: '432Hz', archetype: 'Equilíbrio' },
    { name: 'Todai-ji', location: 'Nara, Japão', coordinates: '34.6889°N, 135.8399°E', origin: '752', function: 'Guardião do Buda Cósmico (Vairocana), representando a vacuidade iluminada.', frequency: '∞ Hz', archetype: 'Vacuidade Iluminada' },
    { name: 'Itsukushima Shrine', location: 'Hiroshima, Japão', coordinates: '34.2968°N, 132.3199°E', origin: 'c. 6º século', function: 'Portal da água que reflete a harmonia entre o espiritual e o material.', frequency: '417Hz', archetype: 'Harmonia e Reflexão' },
    { name: 'Templo do Céu (Tiantan)', location: 'Pequim, China', coordinates: '39.8822°N, 116.4065°E', origin: '1420', function: 'Ponte cerimonial de comunicação entre o Céu (cosmos) e a Terra (humanidade).', frequency: '741Hz', archetype: 'Ponte Cósmica' },
    { name: 'Shaolin Temple', location: 'Henan, China', coordinates: '34.5199°N, 113.0380°E', origin: '495', function: 'Portal da disciplina, foco e maestria da força interior (Chi).', frequency: '888Hz', archetype: 'Disciplina Interior' },
    { name: 'Bulguksa Temple', location: 'Gyeongju, Coreia do Sul', coordinates: '35.7850°N, 129.3311°E', origin: '774', function: 'Portal da iluminação e da manifestação artística da sabedoria budista.', frequency: '639Hz', archetype: 'Arte Iluminada' },
    { name: 'Jogyesa Temple', location: 'Seul, Coreia do Sul', coordinates: '37.5714°N, 126.9831°E', origin: '1395', function: 'Guardião da prática zen, promovendo a clareza da mente e a paz interior.', frequency: '852Hz', archetype: 'Clareza Mental' },
    { name: 'Shwedagon Pagoda', location: 'Yangon, Myanmar', coordinates: '16.7983°N, 96.1497°E', origin: 'c. 6º-10º século', function: 'Portal dourado que ancora a iluminação e a compaixão no plano terreno.', frequency: '963Hz', archetype: 'Iluminação Ancorada' },
    { name: 'Ananda Temple', location: 'Bagan, Myanmar', coordinates: '21.1722°N, 94.8586°E', origin: '1105', function: 'Guardião da sabedoria infinita de Buda, um ponto de aprendizado cósmico.', frequency: '741Hz', archetype: 'Sabedoria Infinita' },
    { name: 'Angkor Wat', location: 'Siem Reap, Camboja', coordinates: '13.4125°N, 103.8667°E', origin: 'c. 12º século', function: 'Portal de Vishnu e templo solar, um mapa cosmológico em pedra.', frequency: '528Hz', archetype: 'Ordem Cósmica' },
    { name: 'Bayon Temple', location: 'Angkor Thom, Camboja', coordinates: '13.4411°N, 103.8597°E', origin: 'c. 12º século', function: 'Santuário das múltiplas faces da consciência universal (Avalokiteshvara).', frequency: '639Hz', archetype: 'Consciência Universal' },
    { name: 'Templo do Dente de Buda', location: 'Kandy, Sri Lanka', coordinates: '7.2936°N, 80.6414°E', origin: '1595', function: 'Guardião da relíquia sagrada, um ponto focal de fé e energia devocional.', frequency: '432Hz', archetype: 'Fé e Devoção' },
    { name: 'Ruwanwelisaya Stupa', location: 'Anuradhapura, Sri Lanka', coordinates: '8.3522°N, 80.4036°E', origin: '140 a.C.', function: 'Portal da paz, da pureza e da iluminação búdica.', frequency: '963Hz', archetype: 'Paz Iluminada' },
    // Oceania e Lemúria
    { name: 'Uluru (Ayers Rock)', location: 'Austrália', coordinates: '25.3444° S, 131.0369° E', origin: 'Ancestral', function: 'Chakra planetário, vitalidade ancestral', frequency: '741 Hz', archetype: 'Plexo Solar de Gaia' },
    { name: 'Kata Tjuta (Olgas)', location: 'Austrália', coordinates: '25.3000° S, 130.7333° E', origin: 'Ancestral', function: 'Equilíbrio masculino-feminino', frequency: '852 Hz', archetype: 'União dos Pilares' },
    { name: 'Mount Warning (Wollumbin)', location: 'Austrália', coordinates: '28.4050° S, 153.2760° E', origin: 'Natural', function: 'Portal da aurora e renascimento', frequency: '963 Hz', archetype: 'Guardião da Aurora' },
    { name: 'Grampians (Gariwerd)', location: 'Austrália', coordinates: '37.2333° S, 142.5167° E', origin: 'Ancestral', function: 'Arte rupestre e sabedoria ancestral', frequency: '528 Hz', archetype: 'Guardião da Memória' },
    { name: 'Rotorua', location: 'Nova Zelândia', coordinates: '38.1368° S, 176.2497° E', origin: 'Natural', function: 'Cura geotermal e sabedoria Maori', frequency: '528 Hz', archetype: 'Guardião da Terra Viva' },
    { name: 'Mount Taranaki', location: 'Nova Zelândia', coordinates: '39.2967° S, 174.0633° E', origin: 'Natural', function: 'Contemplação e equilíbrio interior', frequency: '417 Hz', archetype: 'Guardião do Vazio' },
    { name: 'Waitomo Caves', location: 'Nova Zelândia', coordinates: '38.2617° S, 175.1042° E', origin: 'Natural', function: 'Luz interior e conexão subterrânea', frequency: '∞ Hz', archetype: 'Guardião das Estrelas Subterrâneas' },
    { name: 'Lake Taupo', location: 'Nova Zelândia', coordinates: '38.8200° S, 175.7900° E', origin: 'Natural', function: 'Vórtice de água e fogo', frequency: '639 Hz', archetype: 'Guardião da Transmutação' },
    { name: 'Ilha de Páscoa (Rapa Nui)', location: 'Chile', coordinates: '27.1127° S, 109.3497° W', origin: 'Ancestral', function: 'Guardiões Moai, memória estelar', frequency: '144.144 MHz', archetype: 'Sentinelas da Lemúria' },
    { name: 'Havaí (Big Island)', location: 'Havaí, EUA', coordinates: '19.8968° N, 155.5828° W', origin: 'Natural', function: 'Fogo criador, transmutação vulcânica', frequency: '888 Hz', archetype: 'Guardiã Pele' },
    { name: 'Moorea (Polinésia Francesa)', location: 'Polinésia Francesa', coordinates: '17.5388° S, 149.8295° W', origin: 'Natural', function: 'Harmonia oceânica e união dos elementos', frequency: '639 Hz', archetype: 'Guardião do Círculo Azul' },
    { name: 'Bora Bora', location: 'Polinésia Francesa', coordinates: '16.5000° S, 151.7500° W', origin: 'Natural', function: 'Portal da beleza e serenidade cósmica', frequency: '963 Hz', archetype: 'Guardião da Paz' },
    // África
    { name: 'Templo de Luxor', location: 'Egito', coordinates: '25.699° N, 32.639° E', origin: 'c. 1400 a.C.', function: 'Guardião da Lei e da Harmonia', archetype: 'Ética Universal', frequency: '528Hz' },
    { name: 'Obeliscos de Axum', location: 'Etiópia', coordinates: '14.121° N, 38.724° E', origin: 'c. 4º século d.C.', function: 'Registro vibracional da aliança divina', archetype: 'Memória Cósmica', frequency: '963Hz' },
    { name: 'Cidade de Lalibela', location: 'Etiópia', coordinates: '12.030° N, 39.047° E', origin: 'c. 12º-13º século', function: 'Igrejas esculpidas na rocha, fé viva', archetype: 'Portal Cristalino', frequency: '∞ Hz' },
    { name: 'Grande Mesquita de Djenné', location: 'Mali', coordinates: '13.905° N, 4.555° W', origin: 'c. 13º século', function: 'Portal de barro ancestral, sabedoria islâmica', archetype: 'Guardião do Silêncio', frequency: '639Hz' },
    { name: 'Ruínas de Cartago', location: 'Tunísia', coordinates: '36.852° N, 10.323° E', origin: '814 a.C.', function: 'Portal fenício da memória marítima', archetype: 'Guardião das Rotas', frequency: '417Hz' },
    { name: 'Monte Kilimanjaro', location: 'Tanzânia', coordinates: '3.067° S, 37.355° E', origin: 'Natural', function: 'Chakra planetário de ascensão e purificação', archetype: 'Coroa Telúrica', frequency: '741Hz' },
    { name: 'Deserto do Saara', location: 'Norte da África', coordinates: '23.4162° N, 25.6628° E', origin: 'Natural', function: 'Campo de silêncio cósmico e contemplação', archetype: 'Guardião do Vazio', frequency: '144Hz' },
    { name: 'Delta do Okavango', location: 'Botsuana', coordinates: '19.0000° S, 23.0000° E', origin: 'Natural', function: 'Portal de abundância ecológica', archetype: 'Guardião da Fertilidade', frequency: '528Hz' },
    { name: 'Montanhas Drakensberg', location: 'África do Sul', coordinates: '29.5000° S, 29.0000° E', origin: 'Natural', function: 'Guardiões da sabedoria tribal e proteção vibracional', archetype: 'Guardião da Tradição', frequency: '888Hz' },
    { name: 'Cabo da Boa Esperança', location: 'África do Sul', coordinates: '34.356° S, 18.474° E', origin: 'Natural', function: 'Portal de transição dimensional e renascimento', archetype: 'Guardião da Travessia', frequency: '∞ Hz' },
    // América do Norte
    { name: 'Monte Denali', location: 'Alasca, EUA', coordinates: '63.0695°N, 151.0074°W', origin: 'Natural', function: 'Portal da transcendência glacial', frequency: '963 Hz', archetype: 'Guardião da Altitude' },
    { name: 'Glaciar Mendenhall', location: 'Alasca, EUA', coordinates: '58.4550°N, 134.5560°W', origin: 'Natural', function: 'Purificação dimensional', frequency: '417 Hz', archetype: 'Guardião da Água Silenciosa' },
    { name: 'Ilhas Aleutas', location: 'Alasca, EUA', coordinates: '~52°N, 174°W', origin: 'Natural', function: 'Vórtice de transição entre mundos', frequency: '∞ Hz', archetype: 'Sentinelas do Limite' },
    { name: 'Lago Louise', location: 'Canadá', coordinates: '51.4254°N, 116.1773°W', origin: 'Natural', function: 'Portal da contemplação cristalina', frequency: '528 Hz', archetype: 'Guardião da Serenidade' },
    { name: 'Montanhas Rochosas', location: 'Canadá', coordinates: '~51°N, 115°W', origin: 'Natural', function: 'Coluna vertebral da América', frequency: '741 Hz', archetype: 'Guardião da Estrutura' },
    { name: 'Círculo de Petroglifos de Peterborough', location: 'Canadá', coordinates: '44.4781°N, 78.2186°W', origin: 'c. 900–1400 d.C.', function: 'Registro vibracional indígena', frequency: '888 Hz', archetype: 'Guardião da Memória Tribal' },
    { name: 'Serpent Mound', location: 'Ohio, EUA', coordinates: '39.025°N, 83.430°W', origin: 'c. 300 a.C.', function: 'Portal de sabedoria reptiliana', frequency: '144 Hz', archetype: 'Guardião da Linha Dragão' },
    { name: 'Cahokia Mounds', location: 'Illinois, EUA', coordinates: '38.653°N, 90.064°W', origin: 'c. 1050 d.C.', function: 'Centro cerimonial Mississipiano', frequency: '528 Hz', archetype: 'Guardião da Terra Elevada' },
    { name: 'Yellowstone', location: 'Wyoming, EUA', coordinates: '44.4280°N, 110.5885°W', origin: 'Natural', function: 'Vórtice de fogo e renovação', frequency: '888 Hz', archetype: 'Guardião da Transmutação' },
    { name: 'Grand Canyon', location: 'Arizona, EUA', coordinates: '36.1069°N, 112.1129°W', origin: 'Natural', function: 'Portal de profundidade espiritual', frequency: '∞ Hz', archetype: 'Guardião do Abismo' },
    { name: 'Teotihuacan', location: 'México', coordinates: '19.6925°N, 98.8438°W', origin: 'c. 100 a.C.', function: 'Portal solar e estelar', frequency: '888 Hz', archetype: 'Guardião da Ascensão' },
    { name: 'Chichen Itzá', location: 'México', coordinates: '20.6843°N, 88.5678°W', origin: 'c. 600 d.C.', function: 'Alinhamento cósmico e sabedoria Maia', frequency: '528 Hz', archetype: 'Guardião do Tempo' },
    { name: 'Monte Tlaloc', location: 'México', coordinates: '19.4000°N, 98.8000°W', origin: 'Natural', function: 'Portal de chuva e fertilidade', frequency: '639 Hz', archetype: 'Guardião da Água Celeste' },
    { name: 'Palenque', location: 'México', coordinates: '17.4849°N, 92.0453°W', origin: 'c. 226 a.C.', function: 'Templo da inscrição e memória estelar', frequency: '963 Hz', archetype: 'Guardião da Linguagem Cósmica' },
    // América Central
    { name: 'Tikal', location: 'Guatemala', coordinates: '17.2220°N, 89.6237°W', origin: 'c. 4º século a.C.', function: 'Portal de observação estelar e tempo cíclico', frequency: '963 Hz', archetype: 'Guardião do Calendário Cósmico' },
    { name: 'El Mirador', location: 'Guatemala', coordinates: '17.7633°N, 89.9033°W', origin: 'c. 6º século a.C.', function: 'Pirâmide da Criação Maia', frequency: '888 Hz', archetype: 'Guardião da Origem' },
    { name: 'Quiriguá', location: 'Guatemala', coordinates: '15.2694°N, 89.0389°W', origin: 'c. 200 d.C.', function: 'Estelas vibracionais e geometrias vivas', frequency: '528 Hz', archetype: 'Guardião da Linguagem' },
    { name: 'Copán', location: 'Honduras', coordinates: '14.8401°N, 89.1572°W', origin: 'c. 5º século', function: 'Portal da escultura viva e sabedoria Maia', frequency: '639 Hz', archetype: 'Guardião da Forma' },
    { name: 'Cueva del Gigante', location: 'Honduras', coordinates: '14.0000°N, 88.0000°W', origin: 'c. 9480 a.C.', function: 'Portal subterrâneo de introspecção', frequency: '417 Hz', archetype: 'Guardião do Submundo' },
    { name: 'Tazumal', location: 'El Salvador', coordinates: '13.7033°N, 89.6700°W', origin: 'c. 100-1200 d.C.', function: 'Portal de transmutação e ritual ancestral', frequency: '741 Hz', archetype: 'Guardião da Chama' },
    { name: 'Joya de Cerén', location: 'El Salvador', coordinates: '13.8333°N, 89.3667°W', origin: 'c. 600 d.C.', function: 'Pompeia Maia, preservação vibracional', frequency: '528 Hz', archetype: 'Guardião da Memória Cotidiana' },
    { name: 'Ilha de Ometepe', location: 'Nicarágua', coordinates: '11.5333°N, 85.5833°W', origin: 'Natural', function: 'Portal entre dois vulcões, dualidade cósmica', frequency: '∞ Hz', archetype: 'Guardião do Equilíbrio' },
    { name: 'Granada', location: 'Nicarágua', coordinates: '11.9333°N, 85.9500°W', origin: '1524', function: 'Centro colonial vibracional', frequency: '417 Hz', archetype: 'Guardião da Transição' },
    { name: 'Esferas de Diquís', location: 'Costa Rica', coordinates: '8.9500°N, 83.7333°W', origin: 'c. 600-1500 d.C.', function: 'Geometria perfeita, portal de harmonia', frequency: '528 Hz', archetype: 'Guardião da Forma Pura' },
    { name: 'Monteverde Cloud Forest', location: 'Costa Rica', coordinates: '10.3000°N, 84.8167°W', origin: 'Natural', function: 'Portal da névoa e contemplação', frequency: '639 Hz', archetype: 'Guardião da Respiração' },
    { name: 'Canal do Panamá', location: 'Panamá', coordinates: '9.1011°N, 79.4028°W', origin: '1914', function: 'Portal de travessia entre oceanos', frequency: '∞ Hz', archetype: 'Guardião da Ponte' },
    { name: 'Parque Nacional Darién', location: 'Panamá', coordinates: '7.8000°N, 77.7000°W', origin: 'Natural', function: 'Vórtice de biodiversidade e silêncio', frequency: '528 Hz', archetype: 'Guardião da Selva' },
    // América do Sul
    { name: 'Ciudad Perdida', location: 'Colômbia', coordinates: '11.0400°N, 73.9200°W', origin: 'c. 800 d.C.', function: 'Portal da ancestralidade Tayrona', frequency: '528 Hz', archetype: 'Guardião da Origem Verde' },
    { name: 'Sierra Nevada de Santa Marta', location: 'Colômbia', coordinates: '11.0000°N, 74.0000°W', origin: 'Natural', function: 'Montanha sagrada, chakra de contemplação', frequency: '963 Hz', archetype: 'Guardião da Altitude' },
    { name: 'Mitad del Mundo', location: 'Equador', coordinates: '0.0022°S, 78.4558°W', origin: '1936-1979', function: 'Portal do Equador, equilíbrio planetário', frequency: '∞ Hz', archetype: 'Guardião do Centro' },
    { name: 'Quito Antigo', location: 'Equador', coordinates: '0.1807°S, 78.4678°W', origin: '16º século', function: 'Cidade vibracional de sabedoria colonial', frequency: '417 Hz', archetype: 'Guardião da Transição' },
    { name: 'Cusco', location: 'Peru', coordinates: '13.5320°S, 71.9675°W', origin: 'c. 1100', function: 'Umbigo do mundo incaico', frequency: '528 Hz', archetype: 'Guardião da Centralidade' },
    { name: 'Tiwanaku', location: 'Bolívia', coordinates: '16.5545°S, 68.6730°W', origin: 'c. 300 a.C.', function: 'Portal pré-incaico de sabedoria estelar', frequency: '963 Hz', archetype: 'Guardião da Linguagem Cósmica' },
    { name: 'Salar de Uyuni', location: 'Bolívia', coordinates: '20.1338°S, 67.4891°W', origin: 'Natural', function: 'Espelho vibracional da Terra', frequency: '∞ Hz', archetype: 'Guardião da Reflexão' },
    { name: 'Serra do Roncador', location: 'Brasil', coordinates: '14.0000°S, 52.0000°W', origin: 'Natural', function: 'Portal xamânico de comunicação interdimensional', frequency: '963 Hz', archetype: 'Guardião da Ponte Estelar' },
    { name: 'Monte Roraima', location: 'Brasil/Venezuela/Guiana', coordinates: '5.2333°N, 60.7500°W', origin: 'Natural', function: 'Portal de silêncio e contemplação', frequency: '741 Hz', archetype: 'Guardião do Vazio' },
    { name: 'Floresta Amazônica', location: 'Brasil e outros', coordinates: '~3°S, 60°W', origin: 'Natural', function: 'Pulmão vibracional da Terra', frequency: '528 Hz', archetype: 'Guardião da Respiração' },
    { name: 'Chapada dos Veadeiros', location: 'Brasil', coordinates: '14.1000°S, 47.5000°W', origin: 'Natural', function: 'Vórtice de cura e expansão', frequency: '639 Hz', archetype: 'Guardião da Luz Interior' },
    { name: 'Aconcágua', location: 'Argentina', coordinates: '32.6532°S, 70.0109°W', origin: 'Natural', function: 'Montanha de ascensão e força', frequency: '888 Hz', archetype: 'Guardião da Altitude' },
    { name: 'Terra do Fogo', location: 'Argentina/Chile', coordinates: '~54.8000°S, 68.3000°W', origin: 'Natural', function: 'Portal de encerramento dimensional', frequency: '∞ Hz', archetype: 'Guardião da Travessia Final' },
    // Oceanos e Vórtices
    { name: 'Triângulo das Bermudas', location: 'Oceano Atlântico', coordinates: '25.0000°N, 71.0000°W', origin: 'Natural', function: 'Vórtice de transição entre planos', frequency: '∞ Hz', archetype: 'Guardião do Véu' },
    { name: 'Bimini Road', location: 'Bahamas', coordinates: '25.7500°N, 79.2500°W', origin: 'Desconhecido', function: 'Estrutura submersa associada à Atlântida', frequency: '528 Hz', archetype: 'Guardião da Ponte Atlante' },
    { name: 'Açores', location: 'Portugal', coordinates: '38.7000°N, 27.1000°W', origin: 'Natural', function: 'Vórtice energético e possível remanescente atlante', frequency: '639 Hz', archetype: 'Guardião da Memória Oceânica' },
    { name: 'Mar do Caribe', location: 'Oceano Atlântico', coordinates: '~15°N, 75°W', origin: 'Natural', function: 'Portal de alegria, fluxo e ancestralidade afro-indígena', frequency: '528 Hz', archetype: 'Guardião da Celebração' },
    { name: 'Fossa das Marianas', location: 'Oceano Pacífico', coordinates: '11.35°N, 142.2°E', origin: 'Natural', function: 'Portal de introspecção abissal', frequency: '∞ Hz', archetype: 'Guardião do Silêncio Profundo' },
    { name: 'Ilhas Seychelles', location: 'Oceano Índico', coordinates: '~4.6°S, 55.5°E', origin: 'Natural', function: 'Vórtice de equilíbrio e regeneração', frequency: '639 Hz', archetype: 'Guardião da Cura Oceânica' },
    { name: 'Polinésia', location: 'Oceano Pacífico', coordinates: '~17°S, 149°W', origin: 'Ancestral', function: 'Portal de Lemúria e harmonia estelar', frequency: '963 Hz', archetype: 'Guardião da União Azul' },
    // Ártico
    { name: 'Pólo Norte Geográfico', location: 'Ártico', coordinates: '90.0000°N, 0.0000°E', origin: 'Natural', function: 'Portal do Éter, dissolução dimensional', frequency: '∞ Hz', archetype: 'Guardião do Silêncio Cósmico' },
    { name: 'Ilha Ellesmere', location: 'Canadá', coordinates: '80.7500°N, 85.0000°W', origin: 'Natural', function: 'Vórtice de contemplação glacial', frequency: '963 Hz', archetype: 'Guardião da Pureza' },
    { name: 'Svalbard', location: 'Noruega', coordinates: '78.2232°N, 15.6469°E', origin: 'Natural', function: 'Portal da preservação genética e memória planetária', frequency: '528 Hz', archetype: 'Guardião da Semente' },
    { name: 'Geleira de Petermann', location: 'Groenlândia', coordinates: '81.1000°N, 61.9000°W', origin: 'Natural', function: 'Portal de transição climática', frequency: '741 Hz', archetype: 'Guardião da Mudança' },
    { name: 'Mar de Laptev', location: 'Rússia', coordinates: '~78°N, 125°E', origin: 'Natural', function: 'Campo de dissolução vibracional', frequency: '417 Hz', archetype: 'Guardião da Desintegração' },
    // Europa
    { name: 'Stonehenge', location: 'Inglaterra', coordinates: '51.1789°N, 1.8262°W', origin: 'c. 3000 a.C.', function: 'Portal do Coração Planetário', frequency: '528 Hz', archetype: 'Guardião da Harmonia' },
    { name: 'Glastonbury Tor', location: 'Inglaterra', coordinates: '51.1450°N, 2.7030°W', origin: 'Ancestral', function: 'Vórtice de ascensão e sabedoria druídica', frequency: '963 Hz', archetype: 'Guardião da Espiral' },
    { name: 'Avebury', location: 'Inglaterra', coordinates: '51.4280°N, 1.8540°W', origin: 'c. 2850 a.C.', function: 'Círculo megalítico de proteção vibracional', frequency: '741 Hz', archetype: 'Guardião da Geometria' },
    { name: 'Mont Saint-Michel', location: 'França', coordinates: '48.6360°N, 1.5115°W', origin: 'c. 8º século', function: 'Portal da travessia entre mundos', frequency: '417 Hz', archetype: 'Guardião da Passagem' },
    { name: 'Chartres Cathedral', location: 'França', coordinates: '48.4470°N, 1.4870°E', origin: 'c. 1194', function: 'Geometria sagrada e frequência mariana', frequency: '639 Hz', archetype: 'Guardiã da Compaixão' },
    { name: 'Montserrat', location: 'Espanha', coordinates: '41.5912°N, 1.8376°E', origin: 'Natural/Ancestral', function: 'Vórtice de energia feminina e contemplação', frequency: '639 Hz', archetype: 'Guardiã da Montanha Negra' },
    { name: 'Santiago de Compostela', location: 'Espanha', coordinates: '42.8782°N, 8.5448°W', origin: 'c. 9º século', function: 'Portal de peregrinação e transmutação', frequency: '528 Hz', archetype: 'Guardião do Caminho' },
    { name: 'Monte Subasio (Assis)', location: 'Itália', coordinates: '43.0500°N, 12.6000°E', origin: 'Natural/Ancestral', function: 'Portal franciscano de paz vibracional', frequency: '432 Hz', archetype: 'Guardião da Simplicidade' },
    { name: 'Vaticano', location: 'Itália', coordinates: '41.9029°N, 12.4534°E', origin: 'c. 4º século', function: 'Centro de ressonância espiritual global', frequency: '144 Hz', archetype: 'Guardião da Fé' },
    { name: 'Externsteine', location: 'Alemanha', coordinates: '51.8700°N, 8.9300°E', origin: 'Ancestral', function: 'Portal druídico e geomântico', frequency: '741 Hz', archetype: 'Guardião da Terra' },
    { name: 'Berlim (Isla dos Museus)', location: 'Alemanha', coordinates: '52.5200°N, 13.4050°E', origin: 'c. 19º século', function: 'Registro vibracional da memória cultural', frequency: '417 Hz', archetype: 'Guardião da História' },
    { name: 'Pirâmides de Visoko', location: 'Bósnia', coordinates: '43.9800°N, 18.1800°E', origin: 'Ancestral', function: 'Portal de regeneração celular e cura profunda', frequency: '528 Hz', archetype: 'Guardião da Regeneração' },
    { name: 'Delfos', location: 'Grécia', coordinates: '38.4839°N, 22.5000°E', origin: 'c. 8º século a.C.', function: 'Oráculo vibracional e sabedoria apolínea', frequency: '852 Hz', archetype: 'Guardião da Profecia' },
    { name: 'Monte Olimpo', location: 'Grécia', coordinates: '40.0850°N, 22.3580°E', origin: 'Natural/Mitológico', function: 'Portal da ascensão mitológica', frequency: '963 Hz', archetype: 'Guardião do Panteão' },
    { name: 'Sintra', location: 'Portugal', coordinates: '38.8000°N, 9.3833°W', origin: 'Ancestral', function: 'Vórtice de reconexão atlante', frequency: '888 Hz', archetype: 'Guardião da Memória Atlante' },
    { name: 'Lisboa (Alfama)', location: 'Portugal', coordinates: '38.7169°N, 9.1399°W', origin: 'c. 8º século', function: 'Frequência de travessia e saudade ancestral', frequency: '417 Hz', archetype: 'Guardião da Saudade' },
     // Antártida
    { name: 'Pólo Sul Geográfico', location: 'Antártida', coordinates: '90.0000°S, 0.0000°E', origin: 'Natural', function: 'Portal do Silêncio Cósmico', frequency: '∞ Hz', archetype: 'Guardião da Dissolução' },
    { name: 'Domínio de Queen Maud Land', location: 'Antártida', coordinates: '~71°S, 10°E', origin: 'Natural', function: 'Vórtice de recalibração telúrica', frequency: '963 Hz', archetype: 'Guardião da Pureza' },
    { name: 'Monte Erebus', location: 'Antártida', coordinates: '77.5300°S, 167.1600°E', origin: 'Natural', function: 'Portal de fogo glacial e transmutação', frequency: '888 Hz', archetype: 'Guardião da Chama Silenciosa' },
    { name: 'Lago Vostok', location: 'Antártida', coordinates: '77.5000°S, 106.0000°E', origin: 'Natural', function: 'Portal de memória líquida ancestral', frequency: '528 Hz', archetype: 'Guardião da Água Oculta' },
    { name: 'Campo de Gelo de Ronne', location: 'Antártida', coordinates: '~78°S, 60°W', origin: 'Natural', function: 'Espelho vibracional da Terra', frequency: '741 Hz', archetype: 'Guardião da Reflexão' },
    { name: 'Base Amundsen–Scott', location: 'Antártida', coordinates: '90.0000°S, 0.0000°E', origin: '1956', function: 'Sentinela humana no Pólo Sul', archetype: 'Vigilância Científica', frequency: 'N/A' },
    { name: 'Base Vostok', location: 'Antártida', coordinates: '78.4667°S, 106.8333°E', origin: '1957', function: 'Guardiã do ponto mais frio da Terra', archetype: 'Resiliência Extrema', frequency: 'N/A' },
    { name: 'Base Comandante Ferraz', location: 'Antártida', coordinates: '62.0833°S, 58.3833°W', origin: '1984', function: 'Posto avançado de pesquisa brasileira', archetype: 'Presença Sul-Americana', frequency: 'N/A' },
    { name: 'Base McMurdo', location: 'Antártida', coordinates: '77.8419°S, 166.6863°E', origin: '1956', function: 'Principal hub logístico e científico', archetype: 'Infraestrutura Crítica', frequency: 'N/A' }
  ],
  layers: [
    { name: 'Núcleo Interno', function: 'Pulso magnético e alquimia gravitacional' },
    { name: 'Crosta', function: 'Interface vibracional e memória geológica' },
    { name: 'Atmosfera', function: 'Proteção e comunicação' },
    { name: 'Camada de Ozônio', function: 'Filtro cerimonial e escudo de radiação' }
  ],
  oceans: [
    { name: 'Atlântico', role: 'Canal de memória vibracional' },
    { name: 'Pacífico', role: 'Espelho de profundidade' },
    { name: 'Índico', role: 'Canal de cura' }
  ]
};

    