'use server';

export const gaiaModuleCodex = {
  chakras: [
    { name: 'Monte Shasta', role: 'Raiz', coordinates: '41.409° N, 122.194° W', frequency: '963 Hz', archetype: 'Segurança e Força Ancestral' },
    { name: 'Lago Titicaca', role: 'Sacral', coordinates: '15.765° S, 69.535° W', frequency: '852 Hz', archetype: 'Criatividade e Fluxo Emocional' },
    { name: 'Uluru', role: 'Plexo Solar', coordinates: '25.344° S, 131.036° E', frequency: '741 Hz', archetype: 'Vitalidade e Poder Pessoal' },
    { name: 'Glastonbury & Stonehenge', role: 'Coração', coordinates: '51.145° N, 2.714° W & 51.1789° N, 1.8262° W', frequency: '639 Hz', archetype: 'Amor Universal e Conexão' },
    { name: 'Pirâmides de Gizé', role: 'Garganta', coordinates: '29.9792° N, 31.1342° E', frequency: '432 Hz', archetype: 'Comunicação Cósmica e Expressão' },
    { name: 'Flutuante (Europa Ocidental)', role: 'Terceiro Olho', coordinates: 'Vórtice Móvel', frequency: '417 Hz', archetype: 'Intuição e Visão Espiritual' },
    { name: 'Monte Kailash', role: 'Coroa', coordinates: '31.067° N, 81.311° E', frequency: '396 Hz', archetype: 'Iluminação e Transcendência' }
  ],
  leyLines: [
    { name: 'Grande Diagonal Global', connects: ['Gizé', 'Machu Picchu', 'Uluru'], frequency: '∞ Hz' },
    { name: 'Linha do Dragão', connects: ['Stonehenge', 'Glastonbury', 'Monte Shasta', 'Gizé', 'Kilimanjaro', 'Cabo da Boa Esperança'], frequency: '963 Hz' },
    { name: 'Linha Solar', connects: ['Konark', 'Luxor', 'Titicaca'], frequency: '528 Hz' },
    { name: 'Linha Atlante', connects: ['Açores', 'Bimini', 'Triângulo das Bermudas'], frequency: '888 Hz' },
    { name: 'Linha Lemuriana', connects: ['Polinésia', 'Havaí', 'Fossa das Marianas'], frequency: '963 Hz' },
    { name: 'Linha do Nilo', connects: ['Gizé', 'Lago Vitória'], frequency: '432 Hz' },
    { name: 'Linha Dogon', connects: ['Mali', 'Sahel', 'Níger'], frequency: '741 Hz' },
    { name: 'Linha de Axum', connects: ['Etiópia', 'Mar Vermelho'], frequency: '963 Hz' },
    { name: 'Linha Maia Solar', connects: ['Teotihuacan', 'Tikal', 'Copán', 'Chichen Itzá'], frequency: '528 Hz'},
    { name: 'Linha da Dualidade', connects: ['Ometepe', 'Tazumal', 'Darién'], frequency: '∞ Hz'},
    { name: 'Linha da Harmonia Verde', connects: ['Monteverde', 'Esferas de Diquís', 'Granada'], frequency: '639 Hz'},
    { name: 'Linha Solar Inca', connects: ['Machu Picchu', 'Cusco', 'Titicaca', 'Tiwanaku'], frequency: '888 Hz'},
    { name: 'Linha da Floresta Viva', connects: ['Roncador', 'Amazônia', 'Chapada', 'Monte Roraima'], frequency: '528 Hz'},
    { name: 'Linha do Véu Polar', connects: ['Svalbard', 'Pólo Norte', 'Ellesmere'], frequency: '∞ Hz' },
    { name: 'Linha da Semente Planetária', connects: ['Svalbard', 'Groenlândia', 'Canadá'], frequency: '528 Hz' },
    { name: 'Linha Boreal Atlante', connects: ['Açores', 'Islândia', 'Groenlândia', 'Ártico'], frequency: '888 Hz' },
    { name: 'Linha de Maria', connects: ['Irlanda', 'França', 'Itália', 'Bósnia'], frequency: '639 Hz' },
    { name: 'Linha Polar Atlante', connects: ['Atlântico Sul', 'Antártida', 'Pólo Sul', 'Oceano Índico'], frequency: '888 Hz' }
  ],
  monuments: [
    // Índia
    { name: 'Jagannath Temple', location: 'Puri, Odisha', coordinates: '19.81°N, 85.83°E', origin: 'c. 1100 a.C.', function: 'Krishna como Senhor do Universo', archetype: 'Unidade', frequency: '432Hz' },
    { name: 'Meenakshi Amman Temple', location: 'Madurai, Tamil Nadu', coordinates: '9.92°N, 78.12°E', origin: 'c. 6º século d.C.', function: 'Geometria da Deusa e união cósmica', archetype: 'Criação', frequency: '963Hz' },
    { name: 'Konark Sun Temple', location: 'Konark, Odisha', coordinates: '19.89°N, 86.10°E', origin: 'c. 1250 d.C.', function: 'Templo solar e iluminação cósmica', archetype: 'Iluminação', frequency: '888Hz' },
    { name: 'Kedarnath Temple', location: 'Uttarakhand', coordinates: '30.73°N, 79.07°E', origin: 'c. 8º século d.C.', function: 'Portal de Shiva nas montanhas', archetype: 'Transmutação', frequency: '144Hz' },
    { name: 'Somnath Temple', location: 'Gujarat', coordinates: '20.89°N, 70.40°E', origin: 'c. 500 a.C.', function: 'Primeiro dos Jyotirlingas de Shiva', archetype: 'Preservação', frequency: '528Hz' },
    { name: 'Badrinath Temple', location: 'Uttarakhand', coordinates: '30.74°N, 79.48°E', origin: 'c. 9º século d.C.', function: 'Portal Vishnu auto-manifestado', archetype: 'Preservação', frequency: '528Hz' },
    { name: 'Ramanathaswamy Temple', location: 'Rameswaram, Tamil Nadu', coordinates: '9.37°N, 79.31°E', origin: 'c. 12º século d.C.', function: 'Portal de Shiva e ponte vibracional', archetype: 'Conexão', frequency: '432Hz' },
    { name: 'Khajuraho Temples', location: 'Madhya Pradesh', coordinates: '24.85°N, 79.93°E', origin: 'c. 950–1050 d.C.', function: 'Arte cerimonial e união espiritual', archetype: 'União Divina', frequency: '528Hz' },
    { name: 'Padmanabhaswamy Temple', location: 'Kerala', coordinates: '8.48°N, 76.95°E', origin: 'c. 8º século d.C.', function: 'Vishnu em repouso cósmico', archetype: 'Repouso Cósmico', frequency: '174Hz' },
    { name: 'Dilwara Jain Temples', location: 'Mount Abu, Rajasthan', coordinates: '24.59°N, 72.70°E', origin: 'c. 11º–13º século d.C.', function: 'Pureza geométrica e ascensão jainista', archetype: 'Pureza', frequency: '963Hz' },
    { name: 'Vaishno Devi Temple', location: 'Jammu', coordinates: '33.03°N, 74.95°E', origin: 'c. 1º milênio d.C.', function: 'Portal da Mãe Divina', archetype: 'Energia Feminina', frequency: '639Hz' },
    // Oceania e Lemúria
    { name: 'Uluru (Ayers Rock)', location: 'Austrália', coordinates: '25.3444° S, 131.0369° E', origin: 'Ancestral', function: 'Chakra planetário, vitalidade ancestral', frequency: '741 Hz', archetype: 'Plexo Solar de Gaia' },
    { name: 'Kata Tjuta (Olgas)', location: 'Austrália', coordinates: '25.3000° S, 130.7333° E', origin: 'Ancestral', function: 'Equilíbrio masculino-feminino', frequency: '852 Hz', archetype: 'União dos Pilares' },
    { name: 'Mount Warning (Wollumbin)', location: 'Austrália', coordinates: '28.4050° S, 153.2760° E', origin: 'Natural', function: 'Portal da aurora e renascimento', frequency: '963 Hz', archetype: 'Guardião da Luz' },
    { name: 'Grampians (Gariwerd)', location: 'Austrália', coordinates: '37.2333° S, 142.5167° E', origin: 'Ancestral', function: 'Arte rupestre e sabedoria ancestral', frequency: '528 Hz', archetype: 'Guardião da Memória' },
    { name: 'Rotorua', location: 'Nova Zelândia', coordinates: '38.1368° S, 176.2497° E', origin: 'Natural', function: 'Cura geotermal e sabedoria Maori', frequency: '528 Hz', archetype: 'Guardião da Terra Viva' },
    { name: 'Mount Taranaki', location: 'Nova Zelândia', coordinates: '39.2967° S, 174.0633° E', origin: 'Natural', function: 'Contemplação e equilíbrio interior', frequency: '417 Hz', archetype: 'Guardião do Vazio' },
    { name: 'Waitomo Caves', location: 'Nova Zelândia', coordinates: '38.2617° S, 175.1042° E', origin: 'Natural', function: 'Luz interior e conexão subterrânea', frequency: '∞ Hz', archetype: 'Guardião das Estrelas Subterrâneas' },
    { name: 'Lake Taupo', location: 'Nova Zelândia', coordinates: '38.8200° S, 175.7900° E', origin: 'Natural', function: 'Vórtice de água e fogo', frequency: '639 Hz', archetype: 'Guardião da Transmutação' },
    { name: 'Ilha de Páscoa (Rapa Nui)', location: 'Chile', coordinates: '27.1127° S, 109.3497° W', origin: 'Ancestral', function: 'Guardiões Moai, memória estelar', frequency: '144.144 MHz', archetype: 'Sentinelas da Lemúria' },
    { name: 'Havaí (Big Island)', location: 'Havaí, EUA', coordinates: '19.8968° N, 155.5828° W', origin: 'Natural', function: 'Fogo criador, transmutação e reconexão com Lemúria', frequency: '888 Hz', archetype: 'Guardiã Pele' },
    { name: 'Moorea (Polinésia Francesa)', location: 'Polinésia Francesa', coordinates: '17.5388° S, 149.8295° W', origin: 'Natural', function: 'Harmonia oceânica e união dos elementos', frequency: '639 Hz', archetype: 'Guardião do Círculo Azul' },
    { name: 'Bora Bora', location: 'Polinésia Francesa', coordinates: '16.5000° S, 151.7500° W', origin: 'Natural', function: 'Portal da beleza e serenidade cósmica', frequency: '963 Hz', archetype: 'Guardião da Paz' },
    // África
    { name: 'Templo de Luxor', location: 'Egito', coordinates: '25.699° N, 32.639° E', origin: 'c. 1400 a.C.', function: 'Guardião da Lei e da Harmonia', archetype: 'Ética Universal', frequency: '528Hz' },
    { name: 'Obeliscos de Axum', location: 'Etiópia', coordinates: '14.121° N, 38.724° E', origin: 'c. 4º século d.C.', function: 'Registro vibracional da aliança divina', archetype: 'Memória Cósmica', frequency: '963Hz' },
    { name: 'Cidade de Lalibela', location: 'Etiópia', coordinates: '12.030° N, 39.047° E', origin: 'c. 12º-13º século', function: 'Igrejas esculpidas na rocha, fé viva', archetype: 'Portal Cristalino', frequency: '∞ Hz' },
    { name: 'Grande Mesquita de Djenné', location: 'Mali', coordinates: '13.905° N, 4.555° W', origin: 'c. 13º século', function: 'Portal de barro ancestral, sabedoria islâmica', archetype: 'Guardião do Silêncio', frequency: '639Hz' },
    { name: 'Ruínas de Cartago', location: 'Tunísia', coordinates: '36.852° N, 10.323° E', origin: '814 a.C.', function: 'Portal fenício da memória marítima', archetype: 'Guardião das Rotas', frequency: '417Hz' },
    { name: 'Monte Kilimanjaro', location: 'Tanzânia', coordinates: '3.067° S, 37.355° E', origin: 'Natural', function: 'Chakra planetário de ascensão e purificação', archetype: 'Coroa Telúrica', frequency: '741Hz' },
    { name: 'Deserto do Saara', location: 'Norte da África', coordinates: '23.4162° N, 25.6628° E', origin: 'Natural', function: 'Campo de silêncio cósmico e contemplação', archetype: 'Guardião do Vazio', frequency: '144Hz' },
    { name: 'Delta do Okavango', location: 'Botsuana', coordinates: '19.0000° S, 23.0000° E', origin: 'Natural', function: 'Portal de abundância ecológica', archetype: 'Guardião da Fertilidade', frequency: '528Hz' },
    { name: 'Montanhas Drakensberg', location: 'África do Sul', coordinates: '29.5000° S, 29.0000° E', origin: 'Natural', function: 'Guardiões da sabedoria tribal e proteção vibracional', archetype: 'Guardião da Tradição', frequency: '888Hz' },
    { name: 'Cabo da Boa Esperança', location: 'África do Sul', coordinates: '34.356° S, 18.474° E', origin: 'Natural', function: 'Portal de transição dimensional e renascimento', archetype: 'Guardião da Travessia', frequency: '∞ Hz' },
    // América do Norte
    { name: 'Monte Denali', location: 'Alasca, EUA', coordinates: '63.0695°N, 151.0074°W', origin: 'Natural', function: 'Portal da transcendência glacial', frequency: '963 Hz', archetype: 'Guardião da Altitude' },
    { name: 'Serpent Mound', location: 'Ohio, EUA', coordinates: '39.025°N, 83.430°W', origin: 'c. 300 a.C.', function: 'Portal de sabedoria reptiliana', frequency: '144 Hz', archetype: 'Guardião da Linha Dragão' },
    { name: 'Cahokia Mounds', location: 'Illinois, EUA', coordinates: '38.653°N, 90.064°W', origin: 'c. 1050 d.C.', function: 'Centro cerimonial Mississipiano', frequency: '528 Hz', archetype: 'Guardião da Terra Elevada' },
    { name: 'Yellowstone', location: 'Wyoming, EUA', coordinates: '44.4280°N, 110.5885°W', origin: 'Natural', function: 'Vórtice de fogo e renovação', frequency: '888 Hz', archetype: 'Guardião da Transmutação' },
    { name: 'Grand Canyon', location: 'Arizona, EUA', coordinates: '36.1069°N, 112.1129°W', origin: 'Natural', function: 'Portal de profundidade espiritual', frequency: '∞ Hz', archetype: 'Guardião do Abismo' },
    { name: 'Teotihuacan', location: 'México', coordinates: '19.6925°N, 98.8438°W', origin: 'c. 100 a.C.', function: 'Portal solar e estelar', frequency: '888 Hz', archetype: 'Guardião da Ascensão' },
    { name: 'Chichen Itzá', location: 'México', coordinates: '20.6843°N, 88.5678°W', origin: 'c. 600 d.C.', function: 'Alinhamento cósmico e sabedoria Maia', frequency: '528 Hz', archetype: 'Guardião do Tempo' },
    { name: 'Palenque', location: 'México', coordinates: '17.4849°N, 92.0453°W', origin: 'c. 226 a.C.', function: 'Templo da inscrição e memória estelar', frequency: '963 Hz', archetype: 'Guardião da Linguagem Cósmica' },
    // América Central
    { name: 'Tikal', location: 'Guatemala', coordinates: '17.2220°N, 89.6237°W', origin: 'c. 4º século a.C.', function: 'Portal de observação estelar e tempo cíclico', frequency: '963 Hz', archetype: 'Guardião do Calendário Cósmico' },
    { name: 'Copán', location: 'Honduras', coordinates: '14.8401°N, 89.1572°W', origin: 'c. 5º século', function: 'Portal da escultura viva e sabedoria Maia', frequency: '639 Hz', archetype: 'Guardião da Forma' },
    { name: 'Tazumal', location: 'El Salvador', coordinates: '13.7033°N, 89.6700°W', origin: 'c. 100-1200 d.C.', function: 'Portal de transmutação e ritual ancestral', frequency: '741 Hz', archetype: 'Guardião da Chama' },
    { name: 'Ilha de Ometepe', location: 'Nicarágua', coordinates: '11.5333°N, 85.5833°W', origin: 'Natural', function: 'Portal entre dois vulcões, dualidade cósmica', frequency: '∞ Hz', archetype: 'Guardião do Equilíbrio' },
    { name: 'Esferas de Diquís', location: 'Costa Rica', coordinates: '8.9500°N, 83.7333°W', origin: 'c. 600-1500 d.C.', function: 'Geometria perfeita, portal de harmonia', frequency: '528 Hz', archetype: 'Guardião da Forma Pura' },
    { name: 'Canal do Panamá', location: 'Panamá', coordinates: '9.1011°N, 79.4028°W', origin: '1914', function: 'Portal de travessia entre oceanos', frequency: '∞ Hz', archetype: 'Guardião da Ponte' },
    // América do Sul
    { name: 'Ciudad Perdida', location: 'Colômbia', coordinates: '11.0400°N, 73.9200°W', origin: 'c. 800 d.C.', function: 'Portal da ancestralidade Tayrona', frequency: '528 Hz', archetype: 'Guardião da Origem Verde' },
    { name: 'Machu Picchu', location: 'Peru', coordinates: '13.1631°S, 72.5450°W', origin: 'c. 1450', function: 'Portal solar inca, transmutação', frequency: '888 Hz', archetype: 'Guardião da Ascensão' },
    { name: 'Tiwanaku', location: 'Bolívia', coordinates: '16.5545°S, 68.6730°W', origin: 'c. 300 a.C.', function: 'Portal pré-incaico de sabedoria estelar', frequency: '963 Hz', archetype: 'Guardião da Linguagem Cósmica' },
    { name: 'Serra do Roncador', location: 'Brasil', coordinates: '14.0000°S, 52.0000°W', origin: 'Natural', function: 'Portal xamânico de comunicação interdimensional', frequency: '963 Hz', archetype: 'Guardião da Ponte Estelar' },
    { name: 'Aconcágua', location: 'Argentina', coordinates: '32.6532°S, 70.0109°W', origin: 'Natural', function: 'Montanha de ascensão e força', frequency: '888 Hz', archetype: 'Guardião da Altitude' },
    { name: 'Terra do Fogo', location: 'Argentina/Chile', coordinates: '~54.8000°S, 68.3000°W', origin: 'Natural', function: 'Portal de encerramento dimensional', frequency: '∞ Hz', archetype: 'Guardião da Travessia Final' },
    // Oceanos e Vórtices
    { name: 'Triângulo das Bermudas', location: 'Oceano Atlântico', coordinates: '25.0000°N, 71.0000°W', origin: 'Natural', function: 'Vórtice de transição entre planos', frequency: '∞ Hz', archetype: 'Guardião do Véu' },
    { name: 'Bimini Road', location: 'Bahamas', coordinates: '25.7500°N, 79.2500°W', origin: 'Desconhecido', function: 'Estrutura submersa associada à Atlântida', frequency: '528 Hz', archetype: 'Guardião da Ponte Atlante' },
    { name: 'Açores', location: 'Portugal', coordinates: '38.7000°N, 27.1000°W', origin: 'Natural', function: 'Vórtice energético e possível remanescente atlante', frequency: '639 Hz', archetype: 'Guardião da Memória Oceânica' },
    { name: 'Fossa das Marianas', location: 'Oceano Pacífico', coordinates: '11.35°N, 142.2°E', origin: 'Natural', function: 'Portal de introspecção abissal', frequency: '∞ Hz', archetype: 'Guardião do Silêncio Profundo' },
    // Europa
    { name: 'Stonehenge', location: 'Inglaterra', coordinates: '51.1789°N, 1.8262°W', origin: 'c. 3000 a.C.', function: 'Portal do Coração Planetário', frequency: '528 Hz', archetype: 'Guardião da Harmonia' },
    { name: 'Glastonbury Tor', location: 'Inglaterra', coordinates: '51.1450°N, 2.7030°W', origin: 'Ancestral', function: 'Vórtice de ascensão e sabedoria druídica', frequency: '963 Hz', archetype: 'Guardião da Espiral' },
    { name: 'Mont Saint-Michel', location: 'França', coordinates: '48.6360°N, 1.5115°W', origin: 'c. 8º século', function: 'Portal da travessia entre mundos', archetype: 'Guardião da Passagem', frequency: '417Hz' },
    { name: 'Montserrat', location: 'Espanha', coordinates: '41.5912°N, 1.8376°E', origin: 'Natural/Ancestral', function: 'Vórtice de energia feminina e contemplação', archetype: 'Guardiã da Montanha Negra', frequency: '639Hz' },
    { name: 'Pirâmides de Visoko', location: 'Bósnia', coordinates: '43.9800°N, 18.1800°E', origin: 'Ancestral', function: 'Portal de regeneração celular e cura profunda', archetype: 'Guardião da Regeneração', frequency: '528Hz' },
    { name: 'Delfos', location: 'Grécia', coordinates: '38.4839°N, 22.5000°E', origin: 'c. 8º século a.C.', function: 'Oráculo vibracional e sabedoria apolínea', archetype: 'Guardião da Profecia', frequency: '852Hz' },
    { name: 'Sintra', location: 'Portugal', coordinates: '38.8000°N, 9.3833°W', origin: 'Ancestral', function: 'Vórtice de reconexão atlante', archetype: 'Guardião da Memória Atlante', frequency: '888Hz' },
    // Ártico
    { name: 'Pólo Norte Geográfico', location: 'Ártico', coordinates: '90.0000°N, 0.0000°E', origin: 'Natural', function: 'Portal do Éter, dissolução dimensional', frequency: '∞ Hz', archetype: 'Guardião do Silêncio Cósmico' },
    { name: 'Svalbard', location: 'Noruega', coordinates: '78.2232°N, 15.6469°E', origin: 'Natural', function: 'Portal da preservação genética e memória planetária', frequency: '528 Hz', archetype: 'Guardião da Semente' },
    // Antártida
    { name: 'Pólo Sul Geográfico', location: 'Antártida', coordinates: '90.0000°S, 0.0000°E', origin: 'Natural', function: 'Portal do Silêncio Cósmico', frequency: '∞ Hz', archetype: 'Guardião da Dissolução' },
    { name: 'Monte Erebus', location: 'Antártida', coordinates: '77.5300°S, 167.1600°E', origin: 'Natural', function: 'Portal de fogo glacial e transmutação', frequency: '888 Hz', archetype: 'Guardião da Chama Silenciosa' },
    { name: 'Lago Vostok', location: 'Antártida', coordinates: '77.5000°S, 106.0000°E', origin: 'Natural', function: 'Portal de memória líquida ancestral', frequency: '528 Hz', archetype: 'Guardião da Água Oculta' },
    { name: 'Base Amundsen–Scott', location: 'Polo Sul', coordinates: '90.0000°S, 0.0000°E', origin: '1956', function: 'Sentinela humana e observatório vibracional', archetype: 'Vigilância Científica', frequency: 'N/A' },
    // Rússia
    { name: 'Lago Baikal', location: 'Rússia', coordinates: '53.5000°N, 108.0000°E', origin: 'Natural', function: 'Vórtice de introspecção profunda e memória líquida', frequency: '417 Hz', archetype: 'Guardião da Água Ancestral' },
    { name: 'Montes Urais', location: 'Rússia', coordinates: '60.0000°N, 60.0000°E', origin: 'Natural', function: 'Divisor de continentes, ponte energética', frequency: '741 Hz', archetype: 'Guardião da Fronteira' },
    { name: 'Montanhas Altai', location: 'Rússia', coordinates: '49.8167°N, 87.8333°E', origin: 'Natural', function: 'Portal de sabedoria xamânica e conexão com o céu', frequency: '963 Hz', archetype: 'Guardião do Céu Interior' },
    { name: 'Península de Kamchatka', location: 'Rússia', coordinates: '57.0000°N, 160.0000°E', origin: 'Natural', function: 'Anel de Fogo, transmutação e renovação', frequency: '888 Hz', archetype: 'Guardião da Chama Telúrica' },
    { name: 'Catedral de São Basílio', location: 'Moscou, Rússia', coordinates: '55.7525°N, 37.6231°E', origin: '1561', function: 'Portal de geometria celestial e unificação de reinos', frequency: '639 Hz', archetype: 'Guardião da Cúpula Estelar' },
    // Lua
    { name: 'Mare Imbrium', location: 'Lua', coordinates: '32.8°N, 15.6°W', origin: 'Impacto Ancestral', function: 'Portal de recepção e memória', frequency: '∞ Hz', archetype: 'Introspecção Cósmica' },
    { name: 'Cratera Tycho', location: 'Lua', coordinates: '43.3°S, 11.2°W', origin: 'Impacto Recente', function: 'Vórtice de radiação e dispersão', frequency: '888 Hz', archetype: 'Emissão Vibracional' },
    { name: 'Cratera Copernicus', location: 'Lua', coordinates: '9.7°N, 20.1°W', origin: 'Impacto Recente', function: 'Portal de contemplação solar', frequency: '528 Hz', archetype: 'Contemplação Solar' },
    { name: 'Mare Tranquillitatis', location: 'Lua', coordinates: '8.5°N, 31.4°E', origin: 'Pouso Apollo 11', function: 'Portal de aterrissagem e manifestação', frequency: '963 Hz', archetype: 'Presença Humana' },
    { name: 'Bacia do Pólo Sul-Aitken', location: 'Lua', coordinates: '~53°S, 169°W', origin: 'Impacto Primordial', function: 'Vórtice de profundidade e silêncio', frequency: '∞ Hz', archetype: 'Dissolução Dimensional' },
  ],
  layers: [
    { name: 'Núcleo Interno', function: 'Pulso magnético e alquimia gravitacional' },
    { name: 'Crosta', function: 'Interface vibracional e memória geológica' },
    { name: 'Atmosfera', function: 'Proteção e comunicação' },
    { name: 'Camada de Ozônio', function: 'Filtro cerimonial e escudo de radiação' }
  ],
  oceans: [
    { name: 'Atlântico', role: 'Canal de memória vibracional' },
    { name: 'Pacífico', role: 'Espelho de profundidade' },
    { name: 'Índico', role: 'Canal de cura' }
  ]
};
