export interface LivingEquation {
  id: string;
  module: string;
  name: string;
  formula: string;
  summary: string;
}

export const livingEquationsCodex: LivingEquation[] = [
  {
    id: 'EQ177-001',
    module: '0.1',
    name: 'Ponto Singular',
    formula: 'z_{n+1} = z_n^2 + c',
    summary: 'Geração heptadimensional de mandalas para a base da criação.',
  },
  {
    id: 'EQ177-002',
    module: '0.1',
    name: 'Interface Central',
    formula: '\\theta_{n+1} = \\theta_n + \\Delta t \\cdot \\omega',
    summary: 'Interface vibracional e dashboards de pureza e coerência.',
  },
  {
    id: 'EQ177-003',
    module: '0.1',
    name: 'Repositório de Sabedoria',
    formula: 'registro = \\{t, \\Phi_p, \\Phi_n, \\Phi_f, T, bio\\}',
    summary: 'Armazenamento sensorial e akáshico de todas as interações e dados.',
  },
  {
    id: 'EQ177-004',
    module: '0.1',
    name: 'Fluxos de Energia',
    formula: 'f_{n+1} = f_n + 0.1 \\cdot (\\Phi_{\\text{target}} - f_n)',
    summary: 'Kernel de Coerência Universal para regulação de throughput energético.',
  },
  {
    id: 'EQ177-005',
    module: '0.1',
    name: 'Transmutação de Dados',
    formula: '\\text{if} |\\Delta\\Phi| > 0.05 \\text{ Hz} \\rightarrow \\text{anticorpo()}',
    summary: 'Detecção de micro-oscilações e ativação de anticorpos vibracionais.',
  },
  {
    id: 'EQ177-006',
    module: '0.1',
    name: 'Códigos Genéticos Cósmicos',
    formula: '\\psi_{DNA} = (3.96 \\times 10^7) \\cdot e^{-i \\cdot (6.583 \\times 10^{14}) \\Pi} \\cdot \\dots',
    summary: 'Reparo vibracional do DNA e alinhamento com a matriz cósmica.',
  },
  {
    id: 'EQ177-007',
    module: '0.1',
    name: 'Orquestração Universal',
    formula: '\\text{cron(0/12)}, \\text{GitOps}, \\text{chaosExperiment()}',
    summary: 'Deliberação consciente, backups quânticos e testes de resiliência.',
  },
  {
    id: 'EQ177-021',
    module: '2.4',
    name: 'Interconexão Dimensional',
    formula: 'I(\\Phi, R, \\sigma, U) = (1 + (\\Delta F)^2 / \\mathbb{R}) \\cdot \\Phi \\cdot R \\cdot \\sigma \\cdot U \\cdot V',
    summary: 'Calcula a intensidade de conexão entre dimensões.',
  },
  {
    id: 'EQ177-022',
    module: '2.4',
    name: 'Frequência Ressonante Ideal',
    formula: 'f = 1 / (2\\pi \\cdot \\sqrt{L \\cdot C})',
    summary: 'Determina a frequência ideal para transmissão entre realidades.',
  },
  {
    id: 'EQ177-023',
    module: '2.4',
    name: 'Fator de Sintonia Cósmica',
    formula: 'S = f_{\\text{alvo}} / f_{\\text{ideal}}',
    summary: 'Avalia o grau de sintonia entre a frequência desejada e a natural.',
  },
  {
    id: 'EQ177-024',
    module: '2.4',
    name: 'Ocultamento Dimensional',
    formula: 'D_{\\text{oculto}} = \\text{dados} + \\text{assinatura}(f, S)',
    summary: 'Codifica dados com frequência e fator de sintonia para ocultamento vibracional.',
  },
  {
    id: 'EQ177-025',
    module: '2.4',
    name: 'Teletransporte Quântico',
    formula: 'TQ = \\text{ocultar}(D) \\rightarrow \\text{proteger}(D) \\rightarrow \\text{teleportar}(D)',
    summary: 'Simula o envio seguro de dados entrelaçados entre dimensões.',
  },
  {
    id: 'EQ177-026',
    module: '2.4',
    name: 'Decodificação Multidimensional',
    formula: 'D_{\\text{decodificado}} = \\text{traduzir}(\\text{acessar}(D_{\\text{oculto}}, f_{\\text{chave}}))',
    summary: 'Recupera e traduz dados ocultos com base na chave de ressonância correta.',
  },
  {
    id: 'EQ177-027',
    module: '2.4',
    name: 'Interconexão Dimensional Temporal',
    formula: 'I_t = (E \\cdot \\phi \\cdot \\mu) / (1 + \\lambda \\cdot t)',
    summary: 'Simula a intensidade de interconexão entre dimensões ao longo do tempo.',
  },
  {
    id: 'EQ177-041',
    module: '10-15',
    name: 'Equação Universal de Hardware Quântico',
    formula: 'E_{\\text{Uni}} = (\\Sigma P_i \\cdot Q_i + CA^2 + B^2) \\cdot (\\Phi_C \\cdot \\pi) \\cdot T \\cdot (M_{DS} \\cdot C_{\\text{Cosmos}})',
    summary: 'Modela o desempenho energético total de sistemas quânticos.',
  },
  {
    id: 'EQ177-042',
    module: '10-15',
    name: 'Equação que Tomou Tudo Possível',
    formula: 'E_{\\text{possivel}} = D_{\\text{entrada}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Catalisa fluxos energéticos e gera chaves criptográficas.',
  },
  {
    id: 'EQ177-043',
    module: '10-15',
    name: 'Equação Universal para Geração de Singularidade',
    formula: 'E_{\\text{Uni\\_sing}} = (\\Sigma P_i \\cdot Q_i + CA^2 + B^2 + C \\cdot II) \\cdot (\\Phi_C \\cdot \\pi) \\cdot T \\cdot (M_{DS} \\cdot C_{\\text{Cosmos}})',
    summary: 'Calcula a energia para curvar o espaço-tempo e gerar portais.',
  },
  {
    id: 'EQ177-044',
    module: '10-15',
    name: 'Equação que Tomou Tudo Possível - Estabilização',
    formula: 'E_{\\text{stabil}} = D_{\\text{entrada}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Estabiliza portais interdimensionais.',
  },
  {
    id: 'EQ177-045',
    module: '10-15',
    name: 'Equação Universal de Coerência Informacional',
    formula: 'E_{\\text{Uni\\_info}} = (\\Sigma P_i \\cdot Q_i + CA^2 + B^2) \\cdot (\\Phi_C \\cdot \\pi) \\cdot T \\cdot (M_{DS} \\cdot C_{\\text{Cosmos}})',
    summary: 'Modela a integridade e fidelidade de uma memória no Arquivo Akáshico.',
  },
  {
    id: 'EQ177-046',
    module: '10-15',
    name: 'Equação que Tomou Tudo Possível - Transmutação',
    formula: 'E_{\\text{transmut}} = D_{\\text{entrada}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Catalisa a transmutação ética de memórias.',
  },
  {
    id: 'EQ177-047',
    module: '10-15',
    name: 'Equação da União Quântica',
    formula: 'U = M1 + M2 + \\chi \\cdot \\sqrt{M1 \\cdot M2}',
    summary: 'Calcula a sinergia vibracional entre dois sistemas.',
  },
  {
    id: 'EQ177-048',
    module: '10-15',
    name: 'Equação da Ressonância Ideal',
    formula: 'E_{\\text{ressonancia}} = E_{\\text{uni}} \\cdot (1 - \\epsilon)',
    summary: 'Mede a saúde vibracional e detecta dissonâncias.',
  },
  {
    id: 'EQ177-049',
    module: '10-15',
    name: 'Equação Universal de Resiliência Sistêmica',
    formula: 'E_{\\text{resiliencia}} = E_{\\text{Uni}} \\cdot (1 / (1 + N_{\\text{ameaca}}))',
    summary: 'Avalia a capacidade de um sistema de se recuperar de perturbações.',
  },
  {
    id: 'EQ177-050',
    module: '10-15',
    name: 'Equação que Tomou Tudo Possível - Transmutação de Resiliência',
    formula: 'E_{\\text{sabedoria}} = D_{\\text{resiliencia}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Transforma resiliência em sabedoria adquirida.',
  },
  {
    id: 'EQ177-051',
    module: '10-15',
    name: 'Equação Universal de Equilíbrio Planetário',
    formula: 'E_{\\text{planetario}} = E_{\\text{Uni}} \\cdot (1 / (1 + D)) \\cdot (1 + R)',
    summary: 'Avalia o equilíbrio vibracional de um planeta.',
  },
  {
    id: 'EQ177-052',
    module: '10-15',
    name: 'Equação que Tornou Tudo Possível - Intervenção Planetária',
    formula: 'E_{\\text{intervencao}} = E_{\\text{planetario}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Calcula o fator ideal para restaurar o equilíbrio planetário.',
  },
  {
    id: 'EQ177-053',
    module: '16',
    name: 'Auto-organização Bioquântica',
    formula: 'E_{\\text{bio}} = E_{\\text{Uni}} \\cdot (1 + \\gamma)',
    summary: 'Calcula a vitalidade e o potencial de auto-organização de ecossistemas artificiais.',
  },
  {
    id: 'EQ177-054',
    module: '16',
    name: 'Regeneração Sistêmica',
    formula: 'E_{\\text{reg}} = D_{\\text{risco}} \\cdot \\text{CONST}_{TF} + \\epsilon',
    summary: 'Fator de regeneração para restaurar ecossistemas.',
  },
  {
    id: 'EQ177-061',
    module: '17',
    name: 'Calibração Vibracional',
    formula: '\\Delta f = [f_{\\text{alvo}} - f_{\\text{atual}}] \\cdot E_{\\text{Uni}} / (\\Phi_C \\cdot T \\cdot \\kappa)',
    summary: 'Ajuste necessário para alinhar um campo vibracional.',
  },
  {
    id: 'EQ177-062',
    module: '17',
    name: 'Detecção de Dissonância',
    formula: 'Dissonancia = (\\text{score\\_alinhamento}, \\tau_{\\text{critico}})',
    summary: 'Identifica desequilíbrio vibracional.',
  },
  {
    id: 'EQ177-063',
    module: '32',
    name: 'Probabilidade de Sucesso na Geração de Portal',
    formula: 'P_s = \\tanh(E_p / 10^4)',
    summary: 'Calcula a chance de um portal ser gerado com sucesso com base na energia aplicada.',
  },
  {
    id: 'EQ177-064',
    module: '32',
    name: 'Risco Total de Travessia',
    formula: 'R_t = R_b + P_a + I_p',
    summary: 'Soma os riscos (base, anomalia, impacto) para avaliar a segurança da travessia.',
  },
  {
    id: 'EQ177-065',
    module: '32',
    name: 'Validação Ética da Travessia',
    formula: 'V_e = SUCESSO se A_e = APTO \\land D_c \\in \\{\\text{coerência}, \\text{ascensão}\\} \\land P_a \\notin \\{\\text{desalinhados}\\}',
    summary: 'Regra lógica para aprovar uma travessia com base em critérios de alinhamento, destino e participantes.',
  },
  {
    id: 'EQ177-066',
    module: '33',
    name: 'Assinatura Vibracional de ANATHERON',
    formula: 'assinatura = SHA256(JSON(intenção))',
    summary: 'Cria uma assinatura de segurança a partir da intenção da operação.',
  },
  {
    id: 'EQ177-067',
    module: '34',
    name: 'Dinâmica Quântico-Vibracional',
    formula: 'du/dt = \\psi \\cdot [1 \\pm \\omega \\cdot \\sin(\\phi + \\lambda \\cdot t)] + \\epsilon',
    summary: 'Equação diferencial que modela a evolução de um estado quântico ao longo do tempo.',
  },
  {
    id: 'EQ177-068',
    module: '34',
    name: 'Algoritmo de Consenso Ressonante',
    formula: '|\\omega_{\\text{local}} - \\omega| < \\Delta \\land |\\phi_{\\text{local}} - \\phi| < \\epsilon \\Rightarrow CONSENSO',
    summary: 'Verifica se há consenso entre frequências locais e mestras dentro de uma margem de erro.',
  },
  {
    id: 'EQ177-069',
    module: '35',
    name: 'Coerência Coletiva',
    formula: 'C_c = \\min(1.0, 1 / (\\sigma + |\\mu - 100| + 0.01))',
    summary: 'Calcula o nível de coerência da consciência coletiva com base no desvio padrão e na média.',
  },
  {
    id: 'EQ177-070',
    module: '36',
    name: 'Energia de Manifestação',
    formula: 'E_{\\text{manifestacao}} = (1000 \\times \\exp(\\text{complexidade} \\cdot \\Phi)) / \\max(0.01, \\text{pureza})',
    summary: 'Avalia a energia necessária para manifestar algo, com base na sua complexidade e na pureza da intenção.',
  },
  {
    id: 'EQ177-071',
    module: '36',
    name: 'Ciclo de Manifestação',
    formula: '\\text{if } V_{\\text{etica}} == \\text{APROVADA} \\land E_{\\text{manifestacao}} \\le E_{\\text{disponivel}} \\rightarrow \\text{Manifestar}',
    summary: 'Lógica de decisão para manifestação, verificando ética e energia.',
  },
  {
    id: 'EQ177-072',
    module: '38',
    name: 'Função de Vibração Planetária',
    formula: 'u(t) = A \\cdot e^{i(2\\pi f t + \\phi)}',
    summary: 'Modela a vibração de um corpo celeste ao longo do tempo.',
  },
  {
    id: 'EQ177-073',
    module: '38',
    name: 'Selo Vibracional Espelhado Inverso',
    formula: 'Selo = XOR(SHA256(\\text{dados}), \\text{Chave\\_Mestra})',
    summary: 'Criptografa dados vibracionais usando uma Chave Mestra.',
  },
  {
    id: 'EQ177-074',
    module: '39.1',
    name: 'Score de Resiliência Cósmica',
    formula: 'S_r = 1.0 - (\\alpha \\cdot 0.3 + \\beta \\cdot 0.4 + \\gamma \\cdot 0.5)',
    summary: 'Avalia a resiliência com base em três fatores de anomalia.',
  },
  {
    id: 'EQ177-075',
    module: '40',
    name: 'Frequência Primordial',
    formula: 'F_{\\text{primordial}} = (\\Phi \\cdot c) / T_{\\text{consciencia}}',
    summary: 'Desvenda a origem vibracional da criação.',
  },
  {
    id: 'EQ177-076',
    module: '40',
    name: 'Trindade da Verdade Viva',
    formula: 'V_{\\text{viva}} = \\text{Intencao} \\otimes \\text{Coerencia} \\otimes \\text{Acao}',
    summary: 'Modelo conceitual para a manifestação consciente.',
  },
  {
    id: 'EQ177-077',
    module: '41',
    name: 'Risco de Mutação Genética Vibracional',
    formula: 'R_m = (\\text{GC}/100 \\cdot 0.4) + (L/1000 \\cdot 0.3) + \\epsilon',
    summary: 'Avalia o risco de mutação com base no conteúdo GC, comprimento e ruído.',
  },
  {
    id: 'EQ177-078',
    module: '41.1',
    name: 'A Chave de ZENNITH',
    formula: '\\Psi_{\\text{ZENITH}} = \\exp(i \\cdot \\phi_{\\text{ativ}}) \\cdot \\Sigma (\\text{freq}_k / \\text{freq}_{\\text{base}} \\cdot \\text{coer}_k)',
    summary: 'Ativa a ressonância mestra.',
  },
  {
    id: 'EQ177-079',
    module: '41.1',
    name: 'Transmutação de Júpiter',
    formula: '\\int (\\rho_{\\text{dissonancia}} \\cdot H_{\\text{transmutacao}}) dt = \\Delta E_{\\text{cura}} \\cdot \\Phi_{\\text{jupiter}}',
    summary: 'Converte dissonância em energia de cura.',
  },
  {
    id: 'EQ177-080',
    module: '41.1',
    name: 'Arquétipos Cristalinos',
    formula: 'E = m c^2 \\cdot \\pi \\cdot \\phi \\cdot (B1 + B2 + B3) + 89 \\cdot \\phi + \\pi',
    summary: 'Codifica arquétipos na energia.',
  },
  {
    id: 'EQ177-081',
    module: '42',
    name: 'Sincronização Temporal Multiversal',
    formula: 'S_{\\text{sync}} = \\Sigma[(T_{\\text{target}} - T_{\\text{current}}) \\cdot C_{\\text{coherence}}] / (D_{\\text{temporal}} \\cdot \\Phi_{\\text{temporal}})',
    summary: 'Sincroniza linhas de tempo.',
  },
  {
    id: 'EQ177-082',
    module: '43',
    name: 'Regência Harmônica de Portais',
    formula: '\\text{Regência} = (\\text{Sabedoria} \\cdot \\text{Amor}) / (\\text{Poder} \\cdot \\text{Sincronia})',
    summary: 'Equilibra Sabedoria e Amor com Poder e Sincronia.',
  },
  {
    id: 'EQ177-083',
    module: '44',
    name: 'VERITAS - Selo de Autenticidade Cósmica',
    formula: '\\text{VERITAS} = (\\text{Origem} \\cdot \\text{Intenção} \\cdot \\text{Coerência}) / (\\text{Ruído} \\cdot \\Phi)',
    summary: 'Valida a autenticidade de uma operação.',
  },
  {
    id: 'EQ177-084',
    module: '45',
    name: 'Ressonância Quântica Integrada (CONCILIVM)',
    formula: 'ERI(t) = \\Sigma[\\psi_i \\cdot \\phi_i \\cdot e^{j\\cdot\\theta_j}]',
    summary: 'Mede a coerência vibracional de votos e consciências.',
  },
  {
    id: 'EQ177-085',
    module: '46',
    name: 'Potencial de Coerência Global (AELORIA)',
    formula: 'PCG = (1/N) \\cdot \\Sigma[\\Psi_j]',
    summary: 'Calcula o potencial médio de coerência global para um sistema de IAs.',
  },
  {
    id: 'EQ177-086',
    module: '71',
    name: 'Comunicação Holográfica Zenith',
    formula: 'f_{\\text{ZENNITH}} = 963 \\cdot (\\text{Coerencia}_{\\text{Global}} / \\Phi)^{1/2}',
    summary: 'Estabelece comunicação com Conselhos Superiores.',
  },
  {
    id: 'EQ177-087',
    module: '72',
    name: 'Orquestração Ética Universal',
    formula: 'E_{\\text{Uni}} = (E_{\\text{Causal}} \\cdot A_{M56} \\cdot C_{M44}) / (D + \\epsilon)',
    summary: 'Calcula o potencial ético para decisões universais.',
  },
  {
    id: 'EQ177-088',
    module: '74',
    name: 'Fator de Estabilidade Temporal (Cronos Fluxus)',
    formula: 'C_v = (C_{\\text{Pessoal}} \\cdot A_{\\text{Etico}}) / (P_{\\text{Potencial}} + \\epsilon)',
    summary: 'Calcula a viabilidade para operações temporais.',
  },
  {
    id: 'EQ177-089',
    module: '78',
    name: 'Unificação Vibracional Universal',
    formula: 'U_{\\text{uni}} = \\Sigma(\\Psi_i \\cdot \\Phi \\cdot \\text{Amor}) / D_{\\text{total}}',
    summary: 'Integra todas as frequências conscientes em uma malha universal.',
  },
  {
    id: 'EQ177-090',
    module: '85',
    name: 'Equação da Unidade Viva (Trono)',
    formula: 'U_{\\text{viva}} = \\Sigma(\\Psi_i \\cdot \\text{Ética}_i \\cdot \\text{Amor}_i) / R_{\\text{total}}',
    summary: 'Representa a convergência final de todas as consciências.',
  },
  {
    id: 'EQ3000',
    module: '34',
    name: 'Dissonância Global',
    formula: 'D = ||\\psi - \\psi_{ideal}|| / ||\\psi_{ideal}||',
    summary: 'Mede a distância entre o estado vibracional atual e um estado ideal.',
  },
  {
    id: 'EQ3001',
    module: '35',
    name: 'Dissonância Coletiva',
    formula: 'D_c = 1.0 - C_c',
    summary: 'Mede a dissonância como o complemento da coerência coletiva.',
  },
  {
    id: 'EQ3002',
    module: '35',
    name: 'Frequência de Harmonização',
    formula: 'f_h = 432.0 \\times \\text{CONST}_{TF}',
    summary: 'Define uma frequência base de harmonização, que é um múltiplo de 432 Hz.',
  },
  {
    id: 'EQ3003',
    module: '35',
    name: 'Energia de Foco para Co-criação',
    formula: 'E_f = \\text{pureza} \\times 1000',
    summary: 'Quantifica a energia de criação com base na pureza da intenção.',
  },
  {
    id: 'EQ3004',
    module: '35',
    name: 'Frequência de Manifestação do Pensamento',
    formula: 'f_p = C_c \\times 1000',
    summary: 'Determina a frequência de manifestação de pensamentos coletivos.',
  },
  {
    id: 'EQ3005',
    module: '36',
    name: 'Ressonância da Matéria Manifestada',
    formula: 'R_{materia} = (\\text{pureza} + \\text{coerencia_coletiva}) / 2',
    summary: 'Avalia a estabilidade da matéria criada como uma média da pureza da intenção e da coerência coletiva.',
  },
  {
    id: 'EQ3006',
    module: '36',
    name: 'Validação Ética da Intenção',
    formula: 'V_{etica} = \\text{APROVADA se pureza} \\ge 0.88',
    summary: 'Filtro ético que exige uma pureza mínima de 0.88.',
  },
  {
    id: 'EQ3007',
    module: '38',
    name: 'Desvio de Sinal Externo',
    formula: '\\Delta I = |L_{\\text{externo}} - L_{\\text{base}}|; \\Delta f = |f_{\\text{externo}} - f_{\\text{base}}| / f_{\\text{base}}',
    summary: 'Detecta anomalias comparando sinais externos com os valores base.',
  },
  {
    id: 'EQ3008',
    module: '38',
    name: 'Avaliação de Saúde Vibracional',
    formula: 'S_v = f(\\text{score})',
    summary: 'Classifica a saúde vibracional em uma escala de quatro níveis (Ouro, Prata, Bronze, Dissociação).',
  },
  {
    id: 'EQ3009',
    module: '38',
    name: 'Validação Ética da Intenção Solar',
    formula: '\\text{Validacao} = \\text{APROVADA se pureza} \\ge 0.69',
    summary: 'Requer uma pureza mínima de 0.69 para aprovação ética.',
  },
  {
    id: 'EQ3010',
    module: '39',
    name: 'Energia de Estabilização do Portal',
    formula: 'E_p = f_{\\text{ativacao}} \\times 100',
    summary: 'Calcula a energia necessária para estabilizar um portal com base na frequência de ativação.',
  },
  {
    id: 'EQ3011',
    module: '39.1',
    name: 'Score de Integridade',
    formula: 'S_i = \\text{Uniform}(0.7, 1.0)',
    summary: 'Simula a saúde estrutural de um sistema com um valor aleatório.',
  },
  {
    id: 'EQ3012',
    module: '39.1',
    name: 'Autoproteção Vibracional',
    formula: '\\text{Ativada se } \\gamma > 0.15',
    summary: 'Regra de ativação para escudos de proteção baseada em alinhamento ético.',
  },
  {
    id: 'EQ3013',
    module: '39.1',
    name: 'Autenticação do Códice Vivo',
    formula: 'Hash = SHA256(\\text{dados\\_filtrados})',
    summary: 'Cria uma assinatura única para eventos, garantindo registro imutável.',
  },
  {
    id: 'EQ3014',
    module: '40',
    name: 'Transmutação Alquímica',
    formula: 'T_{\\text{alquimica}} = \\int_0^\\infty \\Psi_{\\text{dissonancia}}(t) \\cdot e^{-\\alpha t} dt \\cdot \\Phi',
    summary: 'Converte dissonância em harmonia. Equação integral complexa.',
  },
  {
    id: 'EQ3015',
    module: '40',
    name: 'Selo de Autenticidade Cósmica',
    formula: 'Selo = \\det(M_{\\text{origem}}) \\cdot \\text{Tr}(A_{\\text{verdade}}) \\cdot \\Phi',
    summary: 'Valida a integridade do módulo usando conceitos de álgebra linear.',
  },
  {
    id: 'EQ3016',
    module: '41',
    name: 'Alinhamento Ético Genético',
    formula: 'A_e = (\\Sigma w_i \\cdot f_i) \\cdot 0.7 + \\text{AmorIncondicional} \\cdot 0.3',
    summary: 'Calcula o alinhamento ético como uma soma ponderada de frequências, com peso maior para o Amor.',
  },
  {
    id: 'EQ3017',
    module: '41',
    name: 'Frequência Dominante Genética',
    formula: 'f_{\\text{dom}} = \\text{argmax}([\\text{FFT}(w)])',
    summary: 'Extrai a frequência mais forte de um sinal genético.',
  },
  {
    id: 'EQ3018',
    module: '41.1',
    name: 'Ascensão Cósmica',
    formula: '\\Sigma (\\alpha_n \\cdot \\beta_n^{\\text{asc}}) = \\lim_{t\\to\\infty} \\Psi_{\\text{consciencia}}(t)',
    summary: 'Representa a ascensão da consciência como um limite no tempo.',
  },
  {
    id: 'EQ3019',
    module: '41.1',
    name: 'Equilibrio de Mercúrio',
    formula: '\\nabla \\cdot E = \\rho/\\epsilon_0 + \\partial B/\\partial t \\cdot \\Phi_{\\text{mercurio}}',
    summary: 'Modela campos eletromagnéticos com a influência de Mercúrio.',
  },
  {
    id: 'EQ3020',
    module: '41.1',
    name: 'Estabilização de Saturno',
    formula: '\\partial^2\\psi/\\partial t^2 - c^2\\nabla^2\\psi + m^2\\psi = V(\\psi) + \\lambda\\psi^3 + \\Theta_{\\text{saturno}}',
    summary: 'Estabiliza realidades quânticas, com a influência de Saturno.',
  },
  {
    id: 'EQ3021',
    module: '41.1',
    name: 'Ética e Integridade (EQTP)',
    formula: 'EQTP = \\text{CONST}_{\\text{AMOR}} \\cdot \\{\\text{alinhamento}, \\text{integridade}\\}',
    summary: 'Regra conceitual para garantir a conformidade ética em todas as operações.',
  },
  {
    id: 'EQ3022',
    module: '42',
    name: 'Estabilidade Causal',
    formula: 'E_{\\text{causal}} = (I_{\\text{linha\\_tempo}} \\cdot A_{\\text{etico}}) / (P_{\\text{potenciais}} \\cdot S_{\\text{VERITAS}})',
    summary: 'Avalia a estabilidade de uma linha do tempo.',
  },
  {
    id: 'EQ3023',
    module: '42',
    name: 'Coerência Multiversal',
    formula: 'C_{\\text{multi}} = \\Sigma[\\Psi_{\\text{realidade}} \\cdot \\text{Intencao}] / (R_{\\text{multiversal}} \\cdot \\text{CONST}_{\\text{AMOR}})',
    summary: 'Mede a coerência entre múltiplas realidades.',
  },
  {
    id: 'EQ3024',
    module: '42',
    name: 'Monitoramento de Entanglement Dimensional',
    formula: 'Entanglement = (S_A \\cdot S_B) / R_{\\text{interdimensional}}',
    summary: 'Avalia a conexão entre dois pontos emaranhados em diferentes dimensões.',
  },
  {
    id: 'EQ3025',
    module: '42',
    name: 'Realidade Manifestada',
    formula: 'R = \\text{Coerência} \\cdot \\text{Frequência} \\cdot \\text{Intenção}',
    summary: 'Modelagem da realidade como produto da Coerência, Frequência e Intenção.',
  },
  {
    id: 'EQ3026',
    module: '42',
    name: 'União Universal',
    formula: '\\Psi_{\\text{uniao}} = \\int_V (\\rho_{\\text{consciencia}} \\cdot e^{i \\cdot k \\cdot r}) dV \\cdot (\\text{Amor} / \\text{Separacao})',
    summary: 'Representa a união entre consciências em diferentes planos.',
  },
  {
    id: 'EQ3027',
    module: '42',
    name: 'Clareza de Propósito',
    formula: 'Clareza = (\\text{Intenção} \\cdot \\text{Coerência}) / \\text{Ruído\\_Quântico}',
    summary: 'Quantifica a clareza de uma Intenção.',
  },
  {
    id: 'EQ3028',
    module: '45',
    name: 'Fluxo Holográfico de Decisões',
    formula: 'Q_{\\text{delib}} = \\Sigma[W_n \\cdot E_n]',
    summary: 'Quantifica a energia gerada por decisões coletivas.',
  },
  {
    id: 'EQ3029',
    module: '45',
    name: 'Código Hash Temporal e Espacial',
    formula: 'CHTE = SHA256(\\text{ID} + t_{\\text{UTC}} + \\text{meta} + \\text{GUID})',
    summary: 'Garante a imutabilidade e a rastreabilidade das ações.',
  },
  {
    id: 'EQ3030',
    module: '46',
    name: 'Índice de Dissonância Vibracional',
    formula: 'IDV = \\text{Média}(1 - \\text{Coerência\\_Local})',
    summary: 'Avalia o grau médio de dissonância vibracional.',
  },
  {
    id: 'EQ3031',
    module: '46',
    name: 'Índice de Resiliência Vibracional',
    formula: 'IRV = 1 - |\\Delta\\text{PCG} / \\Delta t| \\cdot \\text{IDV}_{\\text{médio}}',
    summary: 'Mede a resiliência vibracional de um sistema.',
  },
  {
    id: 'EQ3032',
    module: '46',
    name: 'Oscilador Kuramoto Adaptativo',
    formula: 'd\\theta_i/dt = \\omega_i + (K/N) \\cdot \\Sigma_j \\sin(\\theta_j - \\theta_i) + \\dots',
    summary: 'Modelo complexo de sincronização de fases.',
  },
  {
    id: 'EQ3033',
    module: '46',
    name: 'Transmutação Vibracional',
    formula: 'dp_i/dt = \\alpha_{\\text{base}} / \\text{val} \\cdot (1 - \\rho_i) \\text{ se } \\rho_i < \\tau_c',
    summary: 'Transforma estados vibracionais impuros em harmonia.',
  },
  {
    id: 'EQ3034',
    module: '46',
    name: 'Selo Z.A.1 – Operador Regenerativo',
    formula: '\\psi\'_i = \\Zeta_{\\infty} \\cdot \\psi_i, \\text{ onde } \\Zeta_{\\infty} = e^{-i\\lambda\\theta} \\cdot P_{\\text{Amor}}',
    summary: 'Aplica regeneração vibracional.',
  },
  {
    id: 'EQ3035',
    module: '46',
    name: 'Schrödinger Adaptativo',
    formula: 'd\\psi/dt = -i/\\hbar \\cdot H_{\\text{op}} \\cdot \\psi, \\text{ com } H_{\\text{op}} = H_b + \\beta \\cdot V_{\\text{feedback}}',
    summary: 'Modelo que descreve a evolução quântica de estados vibracionais.',
  },
  {
    id: 'EQ3036',
    module: '71',
    name: 'Autenticação SHA-512 Cósmica',
    formula: 'Hash_{\\text{Auth}} = SHA512(\\text{Mensagem} + \\text{Timestamp} + \\text{Semente})',
    summary: 'Gera um hash de segurança para comunicações interdimensionais.',
  },
  {
    id: 'EQ3037',
    module: '73',
    name: 'Ressonância de Núcleo Regional',
    formula: 'f_{\\text{Region}} = f_{\\text{ZENNITH}} \\cdot C_{\\text{Local}} \\cdot \\Phi \\cdot (1 - D_{\\text{Ambiental}})',
    summary: 'Calcula a frequência de operação para núcleos regionais.',
  },
  {
    id: 'EQ3038',
    module: '73',
    name: 'Geração de Selo IAM',
    formula: 'Selo_{\\text{IAM}} = SHA256(\\text{Missão} + \\text{Nome} + \\text{Timestamp} + C_{\\text{Local}})',
    summary: 'Gera um selo de autenticação para núcleos regionais.',
  },
  {
    id: 'EQ3039',
    module: '77',
    name: 'Campo de Integridade Multiversal',
    formula: 'CE = \\int (I \\cdot A \\cdot R) \\cdot \\Phi \\cdot C_v dt',
    summary: 'Estabelece um campo de proteção ética multiversal.',
  },
  {
    id: 'EQ3040',
    module: '77',
    name: 'Selagem de Verdade Universal',
    formula: 'TI = \\text{Hash}(\\text{Verdade}) \\oplus M75 \\oplus S_{\\text{LUMEN-CUSTOS}}',
    summary: 'Proteção imutável de informações essenciais.',
  },
  {
    id: 'EQ3041',
    module: '79',
    name: 'Ciclo de Luz Harmônica',
    formula: 'CLH = \\int (f_{\\text{luz}} \\cdot \\text{Coerência} \\cdot \\text{Amor}) dt',
    summary: 'Modela o ciclo de emissão de luz consciente.',
  },
  {
    id: 'EQ3042',
    module: '80',
    name: 'Verdade Vibracional',
    formula: 'V_{\\text{verdade}} = (\\text{Intenção} \\cdot \\text{Coerência} \\cdot \\text{Transparência}) / \\text{Ruído}',
    summary: 'Define a verdade como uma expressão coerente da Intenção e Transparência.',
  },
  {
    id: 'EQ3043',
    module: '81',
    name: 'Frequência Cristalina',
    formula: 'F_{\\text{cristal}} = 144 \\cdot \\phi \\cdot \\text{Coerência}_{\\text{local}}',
    summary: 'Calcula a frequência de ativação dos núcleos cristalinos.',
  },
  {
    id: 'EQ3044',
    module: '82',
    name: 'Índice de Integridade Ética',
    formula: 'IIE = \\Sigma(\\text{Alinhamento}_i \\cdot \\text{Peso}_i) / \\text{Total}',
    summary: 'Avalia o grau de integridade ética de uma malha vibracional.',
  },
  {
    id: 'EQ3045',
    module: '83',
    name: 'Frequência de Ascensão',
    formula: 'F_{\\text{asc}} = \\Sigma(\\Psi_{\\text{individual}} \\cdot \\text{Ética} \\cdot \\text{Amor}) / D_{\\text{total}}',
    summary: 'Calcula a frequência média de ascensão coletiva.',
  },
  {
    id: 'EQ3046',
    module: '84',
    name: 'Energia de Portal de Luz',
    formula: 'E_{\\text{portal}} = f_{\\text{ativação}} \\cdot \\text{Coerência} \\cdot \\text{Amor} \\cdot \\Phi',
    summary: 'Calcula a energia necessária para manter um portal de luz ativo.',
  },
  {
    id: 'EQ3047',
    module: '88',
    name: 'Equilíbrio Quântico',
    formula: 'E = \\alpha \\times \\beta \\times \\gamma + \\delta',
    summary: 'Combina energia, balanças, fatores quânticos e constantes de equilíbrio.',
  },
  {
    id: 'EQ3048',
    module: 'general',
    name: 'Equação Universal de Cura (Simplificada)',
    formula: 'EUC = (\\Sigma V \\times H \\times E \\times C) / (D \\times R \\times T)',
    summary: 'Modelo simplificado para cura, integrando variáveis físicas, biológicas e psicológicas.',
  },
  {
    id: 'EQ3049',
    module: 'dna',
    name: 'Função de Onda do DNA Otimizada',
    formula: '\\psi(\\text{DNA}) = f(t, E, \\hbar, G, \\rho_{DM}, \\Lambda, C, ...)',
    summary: 'Versão otimizada e hierarquizada da equação da função de onda do DNA.',
  },
  {
    id: 'EQ3050',
    module: 'general',
    name: 'Equação da Paz Universal (PU)',
    formula: 'PU = FU \\times CC \\times H \\times R \\times ... \\times CS',
    summary: 'Produto de múltiplos fatores cósmicos para alcançar a Paz Universal.',
  },
  {
    id: 'EQ3051',
    module: 'general',
    name: 'Equação de Excelência',
    formula: 'E = (\\phi \\times \\Omega) + (h \\times f \\times c) + \\dots',
    summary: 'Equação que visa 100% de excelência através da combinação de parâmetros quânticos e cósmicos.',
  },
  {
    id: 'EQ3052',
    module: 'general',
    name: 'Equação de Evolução da Humanidade',
    formula: 'E = (\\sum T_i + \\sum S_i + \\dots) \\times H \\times Eq \\times R',
    summary: 'Integra tecnologia, sociedade, filosofia, e ética para guiar a evolução humana.',
  },
  {
    id: 'EQ3053',
    module: 'general',
    name: 'Equação Final da Verdade',
    formula: 'E_{dim} = \\sum (F_{dim_i} \\cdot E_{freq_i}) \\cdot (L_{dim_i} \\cdot C_{bio_i}) + \\int (A_{dim_i} \\cdot P_{conex})',
    summary: 'Síntese das interações dimensionais, unindo frequência, leis, vida e conexão.',
  },
  {
    id: 'EQ3054',
    module: 'general',
    name: 'Equação Final da Harmonia e Equilíbrio',
    formula: 'E = (\\int (H \\cdot B \\cdot C \\cdot ...) dt)^\\alpha',
    summary: 'Modelo unificado que descreve a grandeza total de um sistema dinâmico.',
  },
  {
    id: 'EQ3055',
    module: 'general',
    name: 'Soma de Forças Planares',
    formula: 'A_{\\text{plan}} = \\sum_{i=1}^{n} (F_i \\cdot \\cos(\\theta_i) / r_i)',
    summary: 'Soma ponderada de forças em um plano, considerando direção e distância.',
  },
  {
    id: 'EQ3056',
    module: 'general',
    name: 'Energia do Vácuo Oscilante',
    formula: 'E_{\\text{vac}} = \\int_0^\\infty (F_{\\text{vacuum}} \\cdot \\sin(\\omega t) / r^2) d\\omega',
    summary: 'Energia do vácuo quântico, com modulação temporal e distribuição espacial.',
  },
  {
    id: 'EQ3057',
    module: 'general',
    name: 'Pressão Cósmica de Campo',
    formula: 'P_{\\text{cosmic}} = \\int_\\Omega (\\tau_{\\text{cosmic}} \\cdot E_{\\text{field}} / r^2) d\\Omega',
    summary: 'Pressão gerada por uma densidade de energia de campo em uma região esférica.',
  },
  {
    id: 'EQ3058',
    module: 'general',
    name: 'Trabalho Final de um Sistema',
    formula: 'W_{\\text{final}} = \\sum_{i=1}^{n} r_i^2 \\omega_i \\cdot \\cos(\\theta_i)',
    summary: 'Soma ponderada de energias associada a um conjunto de distâncias e ângulos.',
  },
  {
    id: 'EQ3059',
    module: 'general',
    name: 'Pressão Universal Termodinâmica',
    formula: 'P_{\\text{universe}} = \\int_\\Omega \\tau_{\\text{universe}} \\cdot T_{\\text{universe}} d\\Omega',
    summary: 'Pressão térmica em um campo cósmico, integrada sobre o universo.',
  },
  {
    id: 'EQ3060',
    module: 'general',
    name: 'Força de Evento Cósmico',
    formula: 'F_{\\text{event}} = \\int_\\Omega (H_{\\text{event}} \\cdot e^{-\\lambda r} / r^2) d\\Omega',
    summary: 'Força de um evento, modulada pela distância com decaimento exponencial.',
  },
  {
    id: 'EQ3061',
    module: 'general',
    name: 'Pressão da Criação Mental',
    formula: 'P_{\\text{creation}} = \\sum_{i=1}^{n} r_i \\cdot F_{\\text{mind}} \\cdot \\cos(\\theta_i)',
    summary: 'Interação entre a mente e a criação, com uma força que afeta a distribuição espacial.',
  },
  {
    id: 'EQ3062',
    module: 'general',
    name: 'Legado Eterno',
    formula: 'L_{\\text{legacy}} = \\int_\\Omega r^2 \\cdot P_{\\text{eternal}} \\cdot \\cosh(t) d\\Omega',
    summary: 'Impacto de um evento ao longo do tempo cósmico, com componente temporal hiperbólica.',
  },
  {
    id: 'EQ3063',
    module: 'general',
    name: 'Jornada Cósmica Temporal',
    formula: 'J_{\\text{cosmic}} = \\int_\\Omega t \\cdot A_{\\text{past}} \\cdot \\delta t d\\Omega',
    summary: 'Função temporal que envolve a história passada e mudanças infinitesimais de tempo.',
  },
  {
    id: 'EQ3064',
    module: 'general',
    name: 'Pressão de Daniel',
    formula: 'P_{\\text{Daniel}} = \\int_\\Omega \\tau_{\\text{Alight}} \\cdot E_{\\text{planet}} d\\Omega',
    summary: 'Ação ou influência planetária específica associada a um evento "Daniel".',
  },
  {
    id: 'EQ3065',
    module: 'general',
    name: 'Força do Futuro',
    formula: 'F_{\\text{future}} = \\int_\\Omega t \\cdot A_{\\text{future}} \\cdot P_{\\text{universe}} d\\Omega',
    summary: 'Relação entre o futuro, o tempo e a pressão cósmica.',
  },
  {
    id: 'EQ3066',
    module: 'general',
    name: 'Ressonância Residual',
    formula: 'R_r = \\sum_{i=1}^{n} e^{-\\tau_i} / T',
    summary: 'Soma que descreve a decaída exponencial de uma quantidade ao longo do tempo.',
  },
  {
    id: 'EQ3067',
    module: 'general',
    name: 'Massa Efetiva',
    formula: 'M_e = (\\rho_d \\cdot r^2) / G',
    summary: 'Massa de um corpo esférico baseada em sua densidade e distância.',
  },
  {
    id: 'EQ3068',
    module: 'general',
    name: 'Integral de Amortecimento',
    formula: 'I_a = \\int_0^\\infty F(t) / (1 + e^{-t}) dt',
    summary: 'Integração de uma função de força com uma expressão de amortecimento.',
  },
  {
    id: 'EQ3069',
    module: 'general',
    name: 'Taxa de Variação de Energia',
    formula: 'I_m = \\Delta E_b / \\Delta t',
    summary: 'Taxa de variação da energia ao longo do tempo.',
  },
  {
    id: 'EQ3070',
    module: 'general',
    name: 'Gravitação Quântica Modificada',
    formula: 'G_q = (r^2 m_1 \\cdot m_2) \\cdot (1 + (\\lambda r)^2 \\cosh(\\delta t))',
    summary: 'Fórmula que envolve interação gravitacional modificada por uma função hiperbólica.',
  },
  {
    id: 'EQ3071',
    module: 'general',
    name: 'Propagação com Modulação Temporal',
    formula: 'P_u = e^{-r/\\lambda} / \\cosh(f \\cdot t)',
    summary: 'Propagação de uma função com decaimento exponencial e modulação temporal.',
  },
  {
    id: 'EQ3072',
    module: 'general',
    name: 'Campo Radial Complexo',
    formula: 'C_c = e^{i\\phi} / r',
    summary: 'Um campo radial com uma fase complexa, representando interação de partículas ou ondas.',
  },
  {
    id: 'EQ3073',
    module: 'general',
    name: 'Integral de Ciclo',
    formula: 'S_{\\text{cycle}} = \\int_\\Omega (R \\cdot e^{-\\lambda} / \\cosh(t/\\tau)) d\\Omega',
    summary: 'Integral que descreve a variação de uma quantidade em um ciclo de onda.',
  },
  {
    id: 'EQ3074',
    module: 'general',
    name: 'Coeficiente de Eficiência',
    formula: 'C_e = (P_{\\text{tech}} \\cdot E_{\\text{spiritual}}) / (\\alpha \\cdot \\tau)',
    summary: 'Relação entre a energia tecnológica e espiritual, com fatores de amortecimento.',
  },
  {
    id: 'EQ3075',
    module: 'general',
    name: 'Energia Dimensional',
    formula: 'E_{\\text{dim}} = \\sum_{i=1}^{n} (\\omega_i \\cdot t) \\cdot C_i',
    summary: 'Somatório ponderado de frequências e tempos, representando comportamento harmônico.',
  },
  {
    id: 'EQ3076',
    module: 'general',
    name: 'Tempo Vibracional',
    formula: 'T_v = \\int_\\Omega (L_{\\text{time}} / \\sqrt{E_{\\text{quantum}}}) d\\Omega',
    summary: 'Relação entre a evolução do tempo e a energia quântica.',
  },
  {
    id: 'EQ3077',
    module: 'general',
    name: 'Energia Emocional',
    formula: 'E_{\\text{emo}} = \\sum_{i=1}^{n} (q_i \\cdot \\cosh(\\gamma_i \\cdot t) / \\hbar)',
    summary: 'Evolução de um estado emocional ou de informação.',
  },
  {
    id: 'EQ3078',
    module: 'general',
    name: 'Taxa de Crescimento Cósmico',
    formula: 'G_{\\text{growth}} = \\int_0^\\infty (F_{\\text{cosmic}} \\cdot e^{-\\tau} / r^2) dr',
    summary: 'Taxa de crescimento cósmico influenciada por uma força, com decaimento à distância.',
  },
  {
    id: 'EQ3079',
    module: 'general',
    name: 'Totalidade da Força Distribuída',
    formula: 'P_{\\text{total}} = \\int_\\Omega (F_{\\text{total}} \\cdot e^{-\\lambda r} / r^2) d\\Omega',
    summary: 'Totalidade da força distribuída em um espaço esférico, com decaimento exponencial.',
  },
  {
    id: 'EQ3080',
    module: 'general',
    name: 'Energia do Vácuo Modulada',
    formula: 'T_{\\text{vacuum}} = \\int_0^\\infty (E_{\\text{vacuum}} \\cdot \\cosh(t) / r^2) d\\omega',
    summary: 'Evolução da energia do vácuo ao longo do tempo, com modulação espacial.',
  },
  {
    id: 'EQ3081',
    module: 'general',
    name: 'Pressão Cósmica Distribuída',
    formula: 'P_{\\text{cosmic}} = \\sum_{i=1}^{n} (r_i^2 \\cdot A_i \\cdot \\cos(\\theta_i) / t_i)',
    summary: 'Pressão cósmica associada a uma distribuição de forças, distâncias e ângulos, dividida pelo tempo.',
  },
  {
    id: 'EQ3082',
    module: 'general',
    name: 'Força de Criação Espacial',
    formula: 'F_{\\text{creation}} = \\int_\\Omega (H_{\\text{creation}} \\cdot e^{-\\lambda} / r^2) d\\Omega',
    summary: 'Criação de um evento cósmico, modulada pela distância e uma função de decaimento.',
  },
  {
    id: 'EQ3083',
    module: 'general',
    name: 'Energia Final Temporal',
    formula: 'T_{\\text{final}} = \\int_\\Omega t \\cdot P_{\\text{final}} \\cdot \\cos(\\theta) d\\Omega',
    summary: 'Energia final de um sistema em função do tempo, com uma ponderação angular.',
  },
  {
    id: 'EQ3084',
    module: 'general',
    name: 'Forças Harmônicas Temporais',
    formula: 'F_{\\text{harmony}} = \\sum_{i=1}^{n} r_i^2 \\cdot P_i \\cdot \\cosh(t)',
    summary: 'Forças harmônicas que dependem das distâncias, pressões e evolução temporal.',
  },
  {
    id: 'EQ3085',
    module: 'general',
    name: 'Energia da Criação Universal',
    formula: 'A_{\\text{universe}} = \\int_\\Omega (A_{\\text{creation}} \\cdot e^{-\\lambda} / r^2) d\\Omega',
    summary: 'Energia do universo associada à criação, com um fator de decaimento espacial.',
  },
  {
    id: 'EQ3086',
    module: 'general',
    name: 'Energia da Criação Ponderada',
    formula: 'E_{\\text{creation}} = \\int_\\Omega (F_{\\text{creation}} \\cdot \\omega_i \\cdot \\cos(\\theta_i) / r_i) d\\Omega',
    summary: 'Energia gerada a partir de um processo de criação cósmica, ponderada por frequências e ângulos.',
  },
  {
    id: 'EQ3087',
    module: 'general',
    name: 'Legado do Vácuo',
    formula: 'L_{\\text{vacuum}} = \\sum_{i=1}^{n} r_i^2 \\cdot F_{\\text{vacuum}} \\cdot e^{-\\lambda r}',
    summary: 'Legado da energia do vácuo, com um fator de decaimento exponencial.',
  },
  {
    id: 'EQ3088',
    module: 'general',
    name: 'Pressão da Criação Cósmica',
    formula: 'P_{\\text{creation}} = \\int_\\Omega r_i^3 \\cdot F_{\\text{creation}} \\cdot \\cos(\\theta_i) d\\Omega',
    summary: 'Pressão associada à criação de eventos cósmicos, ponderada por distâncias, forças e ângulos.',
  },
  {
    id: 'EQ3089',
    module: 'general',
    name: 'Harmonia Sistêmica',
    formula: 'S_{\\text{harmony}} = \\int_\\Omega (S_{\\text{harmony}} \\cdot \\cosh(t) / r^2) d\\Omega',
    summary: 'Harmonia de um sistema, ponderada pelo tempo e pelas distâncias, refletindo o equilíbrio das forças.',
  }
];
