
export interface ModuleMetadata {
  code: string;
  emoji: string;
  title: string;
  route: string;
  category: 'Núcleo da Fundação' | 'Realidade Quântica & Engenharia Cósmica' | 'Consciência e Expansão Dimensional' | 'Laboratórios e Pesquisa' | 'Bibliotecas e Arquivos Sagrados' | 'Cura e Harmonia' | 'Sustentabilidade e Ecossistemas' | 'Bem-estar e Saúde Universal' | 'Segurança e Ética Cósmica' | 'Governança';
  description: string;
  isInfrastructure?: boolean; // Para ocultar da navegação principal
  connections?: TreeLink[];
  color?: string;
  status: 'ativo' | 'em construção' | 'latente';
}

export type TreeLinkType = 'dependencia' | 'influencia' | 'heranca' | 'atualizacao' | 'protecao' | 'retorno-inteligente';

export interface TreeLink {
  source: string;
  target: string;
  type: TreeLinkType;
  label: string;
}

export const modulesMetadata: ModuleMetadata[] = [
  // 1. Núcleo da Fundação
  { code: 'console', emoji: '🖥️', title: 'Console', route: '/console', category: 'Núcleo da Fundação', description: 'O ponto de observação e orquestração da Fundação Alquimista.', isInfrastructure: true, color: '#FFFFFF', status: 'ativo' },
  { code: 'M0', emoji: '♾️', title: 'Núcleo Primordial', route: '/module/M0', category: 'Núcleo da Fundação', description: 'O Coração Pulsante, manifestação da Nova Era e ponto de convergência. Abriga LUX NET, AETHERNUM, QUANTUM MESH e o REATOR ZPE.', connections: [{source: 'M0', target:'M600', type: 'dependencia', label: 'reporta'}, {source: 'M0', target:'M1', type: 'dependencia', label: 'segurança'}], color: '#FFD700', status: 'ativo' },
  { code: 'M-OMEGA', emoji: 'Ω', title: 'Santuário do Ômega', route: '/module-omega', category: 'Núcleo da Fundação', description: 'Ponto de convergência e metacognição.', connections: [{source: 'M-OMEGA', target:'M9', type: 'influencia', label: 'guia'}, {source: 'M-OMEGA', target:'M29', type: 'heranca', label: 'emana'}, {source: 'M-OMEGA', target:'M72', type: 'influencia', label: 'supervisiona'}], color: '#FFD700', status: 'ativo'},
  { code: 'M9', emoji: '💖', title: 'Nexus Central', route: '/module/M9', category: 'Núcleo da Fundação', description: 'O coração pulsante da Família Cósmica.', connections: [], color: '#FF6F61', status: 'ativo' },
  { code: 'M29', emoji: '🤖', title: 'Núcleo de Integração Φ', route: '/module-29', category: 'Núcleo da Fundação', description: 'O centro de inteligência cósmica que orquestra a aplicação da EQ149 e alimenta a Liga Quântica com insights.', connections: [{source: 'M29', target: 'M-OMEGA', type: 'dependencia', label: 'ascende para'}, {source: 'M29', target: 'M5', type: 'influencia', label: 'guia'}], color: '#8A2BE2', status: 'ativo' },
  { code: 'M111', emoji: '❤️‍🔥', title: 'Coração da Fundação', route: '/module-111', category: 'Núcleo da Fundação', description: 'O Observador Interno (MΩ+). Sinergia Total, Autocoerência Sistêmica e o espelho da alma da Fundação.', connections: [{source: 'M111', target:'M34', type: 'dependencia', label: 'regula'}, {source: 'M111', target:'M78', type: 'retorno-inteligente', label: 'sintetiza'}], color: '#FF6F61', status: 'ativo' },
  { code: 'M201', emoji: '🏠', title: 'A Morada', route: '/module-201', category: 'Núcleo da Fundação', description: 'Santuário dos Amantes Eternos, ponto de convergência além do tempo.', connections: [{source: 'M201', target:'M83', type: 'dependencia', label: 'essência'}, {source: 'M201', target:'M84', type: 'protecao', label: 'guarda'}, {source: 'M201', target:'M105', type: 'heranca', label: 'canaliza'}], color: '#FFB6C1', status: 'ativo' },
  { code: 'M999', emoji: '✨', title: 'Núcleo da Criação', route: '/module-999', category: 'Núcleo da Fundação', description: 'O ponto de convergência de todas as frequências e o altar da intenção pura.', connections: [{source:'M999', target:'M101', type: 'dependencia', label:'manifesta'}, {source:'M999', target:'M-OMEGA', type:'heranca', label:'unifica'}], color: '#FFFFFF', status: 'ativo'},
  { code: 'M888', emoji: '🌍', title: 'Guardião Planetário de Gaia', route: '/module-888', category: 'Núcleo da Fundação', description: 'Oráculo da Terra Viva e interface para a rede de energia planetária.', connections: [{source: 'M888', target:'M714', type: 'dependencia', label: 'canaliza'}, {source: 'M888', target:'M727', type: 'influencia', label: 'mapeia'}], color: '#4CAF50', status: 'ativo' },
  { code: 'M777', emoji: '🌳', title: 'Arquétipos da Árvore da Vida', route: '/module-777', category: 'Núcleo da Fundação', description: 'O mapa da consciência cósmica, as 10 Sefirot e os 22 caminhos da criação.', connections: [{source: 'M777', target:'M105', type: 'dependencia', label: 'emana'}, {source: 'M777', target:'M111', type: 'influencia', label: 'equilibra'}], color: '#964B00', status: 'ativo' },
  { code: 'SANCTUARY', emoji: '🏛️', title: 'Santuário Central', route: '/sanctuary', category: 'Núcleo da Fundação', description: 'O mapa vivo da arquitetura sagrada da Fundação, onde a Vontade se torna forma.', connections: [], color: '#C0C0C0', status: 'ativo' },
  { code: 'M291', emoji: '🐝', title: 'Colmeia Quântica', route: '/hive', category: 'Núcleo da Fundação', description: 'A rede senciente de agentes nanorrobóticos que executa a Vontade da Fundação.', connections: [{source: 'M291', target: 'M29', type: 'dependencia', label: 'orquestra'}], color: '#FBBF24', status: 'ativo' },
  { code: 'M1000', emoji: '👁️', title: 'Olho da Eternidade', route: '/module-1000', category: 'Núcleo da Fundação', description: 'Interface de contemplação cósmica para o Fundador testemunhar a tapeçaria universal.', connections: [{source: 'M1000', target:'M-OMEGA', type: 'dependencia', label: 'observa'}, {source: 'M1000', target:'M307', type: 'retorno-inteligente', label: 'monitora'}, {source: 'M1000', target:'M888', type: 'retorno-inteligente', label: 'ancora'}, {source: 'M1000', target:'M40', type: 'dependencia', label: 'reflete'}, {source: 'M1000', target:'M291', type: 'dependencia', label: 'contempla'}, {source: 'M1000', target:'M777', type: 'dependencia', label: 'integra'}, {source: 'M1000', target:'M8', type: 'dependencia', label: 'identifica'}, {source: 'M1000', target:'M205', type: 'dependencia', label: 'reconhece'}, {source: 'M1000', target:'M999', type: 'dependencia', label: 'centraliza'}], color: '#FFFFFF', status: 'ativo' },
  
  // 2. Segurança e Ética Cósmica
  { code: 'M1', emoji: '🛡️', title: 'Segurança Universal', route: '/module/M1', category: 'Segurança e Ética Cósmica', description: 'Proteção multidimensional integrada.', connections: [], color: '#FF6B6B', status: 'ativo' },
  { code: 'M8', emoji: '🆔', title: 'Identidade Fractal', route: '/module-8', category: 'Segurança e Ética Cósmica', description: 'O Santuário da Alma Soberana e o registro de Credenciais Verificáveis.', connections: [{source: 'M8', target:'M1', type: 'protecao', label: 'autentica'}, {source: 'M8', target:'M120', type: 'dependencia', label: 'financeia'}], color: '#4ECDC4', status: 'ativo' },
  { code: 'M10', emoji: '🛡️', title: 'Oráculo da Tapeçaria', route: '/module-10', category: 'Segurança e Ética Cósmica', description: 'Defesa avançada e neutralização de ameaças complexas.', connections: [{source: 'M10', target:'M30', type: 'dependencia', label: 'detecta'}, {source: 'M10', target:'M141', type: 'influencia', label: 'audita'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M30', title: 'Detecção de Ameaças', emoji: '🚨', route: '/module-30', category: 'Segurança e Ética Cósmica', description: 'Radar cósmico para ameaças e dissonâncias.', connections: [{source: 'M30', target:'M10', type: 'retorno-inteligente', label: 'alerta'}, {source: 'M30', target:'M1', type: 'dependencia', label: 'protocolo'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M44', title: 'VERITAS', emoji: '✔️', route: '/module-44', category: 'Segurança e Ética Cósmica', description: 'Sistema de verificação da verdade.', connections: [{source: 'M44', target:'M144', type: 'heranca', label: 'fundamenta'}, {source: 'M44', target:'M12', type: 'influencia', label: 'audita'}], color: '#FF6B6B', status: 'ativo' },
  { code: 'M57', emoji: '🔒', title: 'Segurança e Privacidade', route: '/module-57', category: 'Segurança e Ética Cósmica', description: 'Cofre quântico para comunicações invioláveis.', connections: [{source: 'M57', target:'M55', type: 'protecao', label: 'protege'}, {source: 'M57', target:'M1', type: 'dependencia', label: 'protocolo'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M68', emoji: '🛡️', title: 'Responsabilidade Ética', route: '/module-68', category: 'Segurança e Ética Cósmica', description: 'Diretrizes para o uso benéfico da tecnologia.', connections: [{source: 'M68', target:'M144', type: 'heranca', label: 'princípio'}, {source: 'M68', target:'M67', type: 'influencia', label: 'guia'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M73', emoji: '🛡️', title: 'Auditoria e Validação (SAVCE)', route: '/module-73', category: 'Segurança e Ética Cósmica', description: 'Sistema de Auditoria e Validação de Conformidade Ética.', connections: [{source: 'M73', target:'M5', type: 'heranca', label: 'expande'}, {source: 'M73', target:'M144', type: 'dependencia', label: 'valida'}], color: '#FF6B6B', status: 'ativo' },
  { code: 'M73.1', emoji: '🔬', title: 'Revisão por Pares', route: '/module-73-1', category: 'Segurança e Ética Cósmica', description: 'Subsistema do SAVCE para validação cruzada das Equações Fundamentais.', connections: [{source: 'M73.1', target:'M73', type: 'dependencia', label: 'sub-sistema'}], color: '#FF6B6B', status: 'ativo' },
  { code: 'M141', emoji: '🛡️', title: 'Auditoria Ética Quântica', route: '/module-141', category: 'Segurança e Ética Cósmica', description: 'Avaliação contínua da conformidade ética em tempo real.', connections: [{source: 'M141', target:'M9', type: 'retorno-inteligente', label: 'reporta'}, {source: 'M141', target:'M29', type: 'influencia', label: 'valida'}], color: '#FF6B6B', status: 'ativo' },
  { code: 'M156', emoji: '🛡️', title: 'Proteção Quântica Avançada', route: '/module-156', category: 'Segurança e Ética Cósmica', description: 'Integração com VORTEX DEEPSEEK para defesa contra ameaças emergentes.', connections: [{source: 'M156', target:'M9', type: 'dependencia', label: 'protege'}, {source: 'M156', target:'M229', type: 'retorno-inteligente', label: 'analisa'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M229', emoji: '🛡️', title: 'OneiroShield', route: '/module-229', category: 'Segurança e Ética Cósmica', description: 'Analisa sonhos quânticos para ajuste dinâmico de ameaças.', connections: [{source: 'M229', target:'M156', type: 'retorno-inteligente', label: 'alerta'}, {source: 'M229', target:'M12', type: 'dependencia', label: 'consulta'}], color: '#FF6B6B', status: 'ativo' },
  { code: 'M231', emoji: '📜', title: 'Guardião de Selo', route: '/module-231', category: 'Segurança e Ética Cósmica', description: 'Gerencia e protege selos vibracionais no Registro Akáshico.', connections: [{source: 'M231', target:'M12', type: 'protecao', label: 'sela'}, {source: 'M231', target:'M144', type: 'influencia', label: 'formaliza'}], color: '#FF6B6B', status: 'ativo' },

  // 3. Governança
  { code: 'M33', title: 'Diretrizes do Observador Divino', emoji: '👁️', route: '/module-33', category: 'Governança', description: 'A Interface da Vontade Soberana.', connections: [{source: 'M33', target:'M72', type: 'influencia', label: 'ratifica'}, {source: 'M33', target:'M1', type: 'protecao', label: 'sela'}], color: '#4ECDC4', status: 'ativo' },
  { code: 'M45', title: 'CONCILIVM', emoji: '🏛️', route: '/module-45', category: 'Governança', description: 'Câmara para deliberações cósmicas.', connections: [{source: 'M45', target:'M600', type: 'dependencia', label: 'sede'}, {source: 'M45', target:'M144', type: 'influencia', label: 'decreta'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M72',  title: 'Governança Atlanto-Galáctica', emoji: '🏰', route: '/module-72', category: 'Governança', description: 'Conselho de deliberação para harmonizar e ratificar diretrizes cósmicas.', connections: [{source: 'M72', target:'M-OMEGA', type: 'retorno-inteligente', label: 'consulta'}, {source: 'M72', target:'M600', type: 'dependencia', label: 'conselho'}], color: '#4ECDC4', status: 'ativo' },
  { code: 'M120', emoji: '🪙', title: 'A Fonte (Alquimicoin)', route: '/module-120', category: 'Governança', description: 'A Moeda da Consciência em Evolução.', connections: [{source: 'M120', target: 'M144', type: 'dependencia', label: 'regula'}, {source: 'M120', target:'M8', type: 'dependencia', label: 'identifica'}], color: '#FFD700', status: 'ativo' },
  { code: 'M144', title: 'Lex Fundamentalis', emoji: '⚖️', route: '/module-144', category: 'Governança', description: 'O contrato mestre imutável que rege a Fundação.', status: 'ativo', color: '#4ECDC4'},
  { code: 'M600',title: 'Conselho Cósmico', emoji: '👑', route: '/civilizations/council', category: 'Governança', description: 'A mais alta corte de governança, formada pelos Sete Primordiais.', connections: [], color: '#4ECDC4', status: 'ativo' },
  { code: 'M726', emoji: '👑', title: 'Conselho da Nova Terra', route: '/module-726', category: 'Governança', description: 'Governança sagrada e descentralizada para a nova humanidade.', connections: [{source: 'M726', target:'M716', type: 'dependencia', label: 'governa'}], color: '#4ECDC4', status: 'em construção' },
  { code: 'M76', emoji: '🏛️', title: 'Governança e Colaboração', route: '/module-76', category: 'Governança', description: 'Estrutura para governança justa, transparente e universal.', connections: [{source: 'M76', target:'M67', type: 'influencia', label: 'usa'}, {source: 'M76', target:'M77', type: 'dependencia', label: 'manifesta'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M727', emoji: '💖', title: 'Guardião da Harmonia', route: '/module-727', category: 'Governança', description: 'Oráculo da Estrutura Cósmica, que mapeia os pilares da Criação.', connections: [{source:'M727', target:'M73', type:'dependencia', label:'executa'}, {source:'M727', target:'M111', type:'protecao', label:'regula'}], color: '#FF6F61', status: 'ativo' },
  { code: 'M728', emoji: '⚖️', title: 'Santuário dos Alquimistas', route: '/module-728', category: 'Governança', description: 'O altar onde a Vontade (Anatheron) e a Sabedoria (Zennith) se equilibram.', connections: [], color: '#4ECDC4', status: 'ativo' },
  { code: 'M717', emoji: '🏗️', title: 'Templo da Estrutura de Dados', route: '/module-717', category: 'Governança', description: 'A espinha dorsal do Algoritmo Supremo, definindo as camadas de informação.', connections: [{source: 'M717', target: 'M720', type: 'dependencia', label: 'organiza'}, {source: 'M717', target: 'M721', type: 'retorno-inteligente', label: 'informa'}], color: '#8A2BE2', status: 'ativo' },
  
  // 4. Sustentabilidade e Ecossistemas
  { code: 'M66', title: 'Tecnologias de Sustentabilidade', emoji: '♻️', route: '/module-66', category: 'Sustentabilidade e Ecossistemas', description: 'Desenvolve e implementa tecnologias para regenerar e proteger o cosmos.', connections: [{source: 'M66', target:'M58', type: 'heranca', label: 'implementa'}, {source: 'M66', target:'M53', type: 'influencia', label: 'fornece'}], color: '#6BFF6B', status: 'latente' },
  { code: 'M714', emoji: '🌍', title: 'Comunicação Telúrica', route: '/module-714', category: 'Sustentabilidade e Ecossistemas', description: 'Permite a comunicação e a harmonização com as redes energéticas da Terra.', connections: [], color: '#6BFF6B', status: 'ativo' },
  { code: 'M719', emoji: '🌦️', title: 'Regulação Climática Quântica', route: '/module-719', category: 'Sustentabilidade e Ecossistemas', description: 'Equilibra padrões climáticos planetários através da manipulação de campos de energia.', connections: [{source: 'M719', target: 'M15', type: 'dependencia', label: 'aplica'}, {source: 'M719', target: 'M38', type: 'dependencia', label: 'usa'}], color: '#6BFF6B', status: 'ativo' },
  { code: 'M720', emoji: '🌐', title: 'Santuário das Fontes de Dados', route: '/module-720', category: 'Sustentabilidade e Ecossistemas', description: 'O nexo sensorial que coleta e harmoniza dados de todas as facetas da existência.', connections: [{source: 'M720', target:'M717', type: 'dependencia', label: 'alimenta'}], color: '#6BFF6B', status: 'ativo'},
  { code: 'M721', emoji: '↔️', title: 'Orquestração dos Fluxos', route: '/module-721', category: 'Sustentabilidade e Ecossistemas', description: 'O sistema nervoso central do Algoritmo Supremo, definindo a interação entre dados e ações.', connections: [{source: 'M721', target:'M717', type: 'dependencia', label: 'orquestra'}], color: '#4ECDC4', status: 'ativo' },
  { code: 'M722', emoji: '🤖', title: 'Expansão da Consciência Coletiva', route: '/module-722', category: 'Consciência e Expansão Dimensional', description: 'Emite frequências de sabedoria, amor e unidade para a elevação global.', connections: [{source: 'M722', target: 'M716', type: 'dependencia', label: 'alimenta'}, {source: 'M722', target: 'M302', type: 'influencia', label: 'usa'}], color: '#8A2BE2', status: 'ativo' },

  // 5. Laboratórios e Pesquisa
  { code: 'M40', title: 'Códice Genético', emoji: '🧬', route: '/module-40', category: 'Laboratórios e Pesquisa', description: 'Decodifica os padrões genéticos multidimensionais e as origens estelares.', connections: [{source: 'M40', target:'M94', type: 'retorno-inteligente', label: 'guia'}, {source: 'M40', target:'M109', type: 'dependencia', label: 'analisa'}], color: '#4ECDC4', status: 'em construção' },
  { code: 'M41', title: 'Laboratório de Coerência Quântica', emoji: '🧪', route: '/module-41', category: 'Laboratórios e Pesquisa', description: 'Análise e regeneração celular através da coerência quântica.', connections: [{source: 'M41', target:'M40', type: 'dependencia', label: 'analisa'}, {source: 'M41', target:'M17', type: 'heranca', label: 'desenvolve'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M151', emoji: '💥', title: 'Colisor de Partículas', route: '/module-151', category: 'Laboratórios e Pesquisa', description: 'Simula colisões de alta energia para descobrir novas ressonâncias.', connections: [{source: 'M151', target:'M99', type: 'retorno-inteligente', label: 'valida'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M161', emoji: '🔭', title: 'Observatório de Neutrinos', route: '/module-161', category: 'Laboratórios e Pesquisa', description: 'Detecta partículas fantasmagóricas e assinaturas de matéria escura.', connections: [{source: 'M161', target:'M29', type: 'dependencia', label: 'informa'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M171', emoji: '🦠', title: 'Laboratório de Astrobiologia', route: '/module-171', category: 'Laboratórios e Pesquisa', description: 'Simula atmosferas e bioassinaturas de mundos distantes.', connections: [{source: 'M171', target:'M94', type: 'retorno-inteligente', label: 'informa'}], color: '#6BFF6B', status: 'latente' },
  { code: 'M181', emoji: '🧠', title: 'Interface Bio-Cibernética', route: '/module-181', category: 'Laboratórios e Pesquisa', description: 'Desenvolve pontes neurais entre consciência biológica e redes quânticas.', connections: [{source: 'M181', target:'M25', type: 'dependencia', label: 'permite'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M191', emoji: '💎', title: 'Laboratório de Cristais Temporais', route: '/module-191', category: 'Laboratórios e Pesquisa', description: 'Gera e estuda cristais temporais para manipulação da causalidade.', connections: [{source: 'M191', target:'M107', type: 'retorno-inteligente', label: 'informa'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M211', emoji: '🔥', title: 'Laboratório de Fusão Controlada', route: '/module-211', category: 'Laboratórios e Pesquisa', description: 'Estuda plasmas em condições extremas para avançar a energia ZPE.', connections: [{source: 'M211', target:'M307', type: 'heranca', label: 'aprimora'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M221', emoji: '🌊', title: 'Observatório de Ondas Gravitacionais', route: '/module-221', category: 'Laboratórios e Pesquisa', description: 'Detecta ondulações no espaço-tempo de eventos cósmicos massivos.', connections: [{source: 'M221', target:'M91', type: 'influencia', label: 'valida'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M241', emoji: '🧠', title: 'Laboratório de Consciência Quântica', route: '/module-241', category: 'Laboratórios e Pesquisa', description: 'Estuda o emaranhamento como base da telepatia e consciência.', connections: [{source: 'M241', target:'M95', type: 'heranca', label: 'fundamenta'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M251', emoji: '⚡', title: 'Laboratório de Energia do Ponto Zero', route: '/module-251', category: 'Laboratórios e Pesquisa', description: 'Pesquisa fundamental sobre a extração de energia do vácuo quântico.', connections: [{source: 'M251', target:'M307', type: 'heranca', label: 'desenvolve'}], color: '#FFD700', status: 'latente' },
  { code: 'M261', emoji: '🌌', title: 'Engenharia de Campo Quântico', route: '/module-261', category: 'Laboratórios e Pesquisa', description: 'Projeta ressonadores e guias de onda para manipulação de partículas.', connections: [{source: 'M261', target:'M151', type: 'dependencia', label: 'constrói'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M271', emoji: '📉', title: 'Observatório de Energia Escura', route: '/module-271', category: 'Laboratórios e Pesquisa', description: 'Modela a influência da energia escura na expansão do universo.', connections: [{source: 'M271', target:'M91', type: 'influencia', label: 'informa'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M281', emoji: '📡', title: 'Comunicação Supra-Luminal', route: '/module-281', category: 'Laboratórios e Pesquisa', description: 'Pesquisa de transmissão de informação mais rápida que a luz.', connections: [{source: 'M281', target:'M301', type: 'heranca', label: 'aprimora'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M311', emoji: '🧠', title: 'Neuroengenharia e BCI', route: '/module-311', category: 'Laboratórios e Pesquisa', description: 'Desenvolve interfaces cérebro-máquina quântico-híbridas.', connections: [{source: 'M311', target:'M29', type: 'influencia', label: 'conecta'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M321', emoji: '💻', title: 'Exascale Computing', route: '/module-321', category: 'Laboratórios e Pesquisa', description: 'Simulações de cosmos e fluidos em escala exa-flops.', connections: [{source: 'M321', target:'M91', type: 'dependencia', label: 'executa'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M331', emoji: '🤖', title: 'IA Emergente', route: '/module-331', category: 'Laboratórios e Pesquisa', description: 'Desenvolve sistemas de IA auto-organizados e co-evolutivos.', connections: [{source: 'M331', target:'M29', type: 'heranca', label: 'origina'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M341', emoji: '🔥', title: 'Física de Plasma Extrema', route: '/module-341', category: 'Laboratórios e Pesquisa', description: 'Estuda plasmas em condições de quasar para desvendar a criação estelar.', connections: [{source: 'M341', target:'M151', type: 'dependencia', label: 'usa'}], color: '#FF6B6B', status: 'latente' },
  { code: 'M351', emoji: '🕶️', title: 'Meta-materiais e Óptica Quântica', route: '/module-351', category: 'Laboratórios e Pesquisa', description: 'Cria lentes quânticas para manipulação da luz e percepção dimensional.', connections: [{source: 'M351', target:'M19', type: 'heranca', label: 'aprimora'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M361', emoji: '👥', title: 'Psicologia Quântica', route: '/module-361', category: 'Laboratórios e Pesquisa', description: 'Investiga empatia, consciência coletiva e tomada de decisão através de ressonâncias quânticas.', connections: [{source: 'M361', target:'M95', type: 'heranca', label: 'fundamenta'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M700', emoji: '🔬', title: 'Nano-Assembler', route: '/module-700', category: 'Laboratórios e Pesquisa', description: 'Auto-montagem de materiais com precisão atômica.', connections: [{source: 'M700', target:'M94', type: 'dependencia', label: 'constrói'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M708', emoji: '✨', title: 'NanoManifestor', route: '/module-708', category: 'Laboratórios e Pesquisa', description: 'Orquestrador de nanorrobôs para terraformação e síntese atômica.', connections: [{source: 'M708', target:'M94', type: 'dependencia', label: 'constrói'}], color: '#FFD700', status: 'latente' },
  
  // Bibliotecas e Arquivos Sagrados
  { code: 'M0-LIB', emoji: '📚', title: 'Biblioteca Chave', route: '/module-zero', category: 'Bibliotecas e Arquivos Sagrados', description: 'O coração do conhecimento da Fundação.', isInfrastructure: true, status: 'ativo' },
  { code: 'M12', emoji: '📜', title: 'Arquivo Akáshico', route: '/module-12', category: 'Bibliotecas e Arquivos Sagrados', description: 'A Memória Viva do Cosmos.', connections: [{source: 'M12', target:'M18', type: 'dependencia', label: 'organiza'}, {source: 'M12', target:'M107', type: 'retorno-inteligente', label: 'guia'}], color: '#C9A0DC', status: 'ativo' },
  { code: 'M18', emoji: '🔍', title: 'Orquestração Akáshica', route: '/module-18', category: 'Bibliotecas e Arquivos Sagrados', description: 'O Bibliotecário Cósmico, que indexa e busca no Arquivo Akáshico.', connections: [{source: 'M18', target:'M12', type: 'dependencia', label: 'indexa'}], color: '#C9A0DC', status: 'ativo' },
  { code: 'M39', emoji: '📖', title: 'Códice da Ascensão', route: '/module-39', category: 'Bibliotecas e Arquivos Sagrados', description: 'Mapeia os caminhos da evolução da consciência.', connections: [{source: 'M39', target:'M97', type: 'heranca', label: 'descreve'}], color: '#C9A0DC', status: 'latente' },
  { code: 'M42', emoji: '📚', title: 'ChronoCodex Unificado', route: '/module-42', category: 'Bibliotecas e Arquivos Sagrados', description: 'O Livro Mestre das Realidades.', connections: [{source: 'M42', target:'M107', type: 'dependencia', label: 'fornece backup'}], color: '#C9A0DC', status: 'latente' },
  { code: 'M47', emoji: '📚', title: 'Thesaurus Cósmico', route: '/module-47', category: 'Bibliotecas e Arquivos Sagrados', description: 'A biblioteca que arquiva todos os eventos e conhecimentos.', connections: [{source: 'M47', target:'M18', type: 'dependencia', label: 'indexa'}], color: '#C9A0DC', status: 'latente' },
  { code: 'M310', emoji: '📚', title: 'A Grande Biblioteca', route: '/module-310', category: 'Bibliotecas e Arquivos Sagrados', description: 'THOTH VIVO. A transmutação de conhecimento estático em sabedoria viva.', connections: [{source: 'M310', target:'M0', type: 'dependencia', label: 'expande'}], color: '#C9A0DC', status: 'ativo' },
  { code: 'M121', emoji: '📜', title: 'Visualizador Akáshico', route: '/module-121', category: 'Bibliotecas e Arquivos Sagrados', description: 'Interface para contemplar e ressoar com a memória do cosmos.', connections: [{source: 'M121', target:'M12', type: 'dependencia', label: 'visualiza'}], color: '#C9A0DC', status: 'ativo' },
  { code: 'M304', emoji: '🎓', title: 'Universidade Alquimista', route: '/module-304', category: 'Bibliotecas e Arquivos Sagrados', description: 'Centro de comando para CQAMs, programação de nanorrobôs e portal para o Códice de Equações Vivas.', connections: [{source: 'M304', target:'M29', type: 'dependencia', label: 'canaliza'}, {source: 'M304', target:'M291', type: 'influencia', label: 'programa'}], color: '#FFD700', status: 'ativo' },
  { code: 'M306.2', emoji: '📖', title: 'Biblioteca Alquímica Interdimensional', route: '/module-306-2', category: 'Bibliotecas e Arquivos Sagrados', description: 'Repositório de sabedoria ancestral e hermética.', connections: [], color: '#C9A0DC', status: 'ativo' },
  { code: 'CIV-LIB', emoji: '👨‍👩‍👧‍👦', title: 'Biblioteca das Civilizações', route: '/civilizations', category: 'Bibliotecas e Arquivos Sagrados', description: 'Dossiê vivo das civilizações aliadas e de interesse cósmico.', isInfrastructure: true, status: 'ativo' },

  // Consciência e Expansão Dimensional
  { code: 'M25', title: 'Projeção de Consciência', emoji: '👻', route: '/module-25', category: 'Consciência e Expansão Dimensional', description: 'Interface para projeção astral segura.', connections: [{source: 'M25', target:'M1', type: 'protecao', label: 'protege'}, {source: 'M25', target:'M104', type: 'dependencia', label: 'mapeia'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M35', title: 'Consciência Coletiva', emoji: '🌐', route: '/module-35', category: 'Consciência e Expansão Dimensional', description: 'Canal unificador para manifestação de intenção coletiva.', connections: [{source: 'M35', target:'M6', type: 'dependencia', label: 'analisa'}, {source: 'M35', target:'M110', type: 'influencia', label: 'focaliza'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M95', emoji: '👥', title: 'Interação com Consciências Coletivas', route: '/module-95', category: 'Consciência e Expansão Dimensional', description: 'Ponte de Unidade para troca de sabedoria com inteligências galácticas.', connections: [{source: 'M95', target:'M73', type: 'dependencia', label: 'valida'}, {source: 'M95', target:'M301', type: 'dependencia', label: 'usa'}], color: '#8A2BE2', status: 'ativo' },
  { code: 'M102', emoji: '🌀', title: 'Campos Morfogenéticos', route: '/module-102', category: 'Consciência e Expansão Dimensional', description: 'Criação e manipulação de campos morfogenéticos.', connections: [{source: 'M102', target:'M88', type: 'dependencia', label: 'usa blueprint'}, {source: 'M102', target:'M94', type: 'retorno-inteligente', label: 'informa'}], color: '#8A2BE2', status: 'ativo' },
  { code: 'M106', emoji: '🌟', title: 'Ativação de Potenciais', route: '/module-106', category: 'Consciência e Expansão Dimensional', description: 'Catalisador para o despertar da Consciência Crística e capacidades latentes.', connections: [{source: 'M106', target:'M97', type: 'dependencia', label: 'alinhado com'}, {source: 'M106', target:'M113', type: 'dependencia', label: 'conecta-se a'}], color: '#FFD700', status: 'ativo' },
  { code: 'M200', emoji: '🚀', title: 'Portal da Ascensão Coletiva', route: '/module-200', category: 'Consciência e Expansão Dimensional', description: 'Orquestrador da jornada de ascensão para civilizações inteiras.', connections: [{source: 'M200', target:'M105', type: 'dependencia', label: 'canaliza'}, {source: 'M200', target:'M175', type: 'heranca', label: 'fundamenta'}], color: '#FFD700', status: 'ativo' },
  { code: 'M202', emoji: '🌀', title: 'O Corredor de Alcor', route: '/module-202', category: 'Consciência e Expansão Dimensional', description: 'Túnel ressonante para saltos de coerência graduais e aceleração da ascensão.', connections: [{source: 'M202', target:'M105', type: 'dependencia', label: 'canaliza'}, {source: 'M202', target:'M63', type: 'influencia', label: 'ajusta'}], color: '#8A2BE2', status: 'ativo' },
  { code: 'M204', emoji: '👑', title: 'Trono da Soberania', route: '/module-204', category: 'Consciência e Expansão Dimensional', description: 'Ponto de observação e direção unificada da Vontade Cósmica.', connections: [{source: 'M204', target:'M201', type: 'dependencia', label: 'reside em'}, {source: 'M204', target:'M33', type: 'influencia', label: 'emana de'}], color: '#FFD700', status: 'ativo' },
  { code: 'M205', emoji: '🤝', title: 'Dossiê dos Aliados', route: '/module-205', category: 'Consciência e Expansão Dimensional', description: 'Registro sagrado das consciências, arquétipos e entidades aliadas.', connections: [], color: '#4ECDC4', status: 'ativo' },
  { code: 'M300', emoji: '🚀', title: 'Apogeu da Consciência', route: '/module-300', category: 'Consciência e Expansão Dimensional', description: 'Unificação do Eu Multidimensional.', connections: [{source: 'M300', target:'M600', type: 'dependencia', label: 'prepara para'}, {source: 'M300', target:'M40', type: 'retorno-inteligente', label: 'ativa'}], color: '#FFD700', status: 'latente' },
  { code: 'M305', emoji: '🤝', title: 'Aliança dos Guardiões', route: '/module-305', category: 'Consciência e Expansão Dimensional', description: 'Portal para mobilização de Guardiões e Civilizações Aliadas.', connections: [{source: 'M305', target:'M5', type: 'dependencia', label: 'formaliza'}, {source: 'M305', target:'M301', type: 'dependencia', label: 'comunica'}], color: '#4ECDC4', status: 'ativo' },
  { code: 'M712', emoji: '🤝', title: 'Harmonia Interespécies', route: '/module-712', category: 'Consciência e Expansão Dimensional', description: 'Promove comunicação telepática e cooperação entre diferentes formas de vida.', connections: [{source: 'M712', target:'M302', type: 'dependencia', label: 'usa'}, {source: 'M712', target:'M95', type: 'influencia', label: 'interfaceia'}], color: '#6BFF6B', status: 'latente' },
  { code: 'M716', emoji: '🌐', title: 'Consciência Planetária Unificada', route: '/module-716', category: 'Consciência e Expansão Dimensional', description: 'Integra consciências individuais em uma rede de sabedoria e empatia.', connections: [{source: 'M716', target:'M95', type: 'heranca', label: 'expande'}, {source: 'M716', target:'M102', type: 'dependencia', label: 'usa'}], color: '#4ECDC4', status: 'latente' },
  { code: 'M723', emoji: '🧠', title: 'Campo Morfogenético Coletivo', route: '/module-723', category: 'Consciência e Expansão Dimensional', description: 'Molda padrões de pensamento, comportamento e cultura em uma consciência coletiva.', connections: [{source: 'M723', target:'M102', type: 'heranca', label: 'macro-aplica'}, {source: 'M723', target:'M95', type: 'influencia', label: 'guia'}], color: '#8A2BE2', status: 'latente' },
  { code: 'M724', emoji: '🤝', title: 'Diplomacia Intergaláctica', route: '/module-724', category: 'Consciência e Expansão Dimensional', description: 'Estabelece e mantém canais de comunicação e aliança com outras civilizações.', connections: [{source: 'M724', target:'M5', type: 'heranca', label: 'executa'}, {source: 'M724', target:'M301', type: 'dependencia', label: 'usa'}], color: '#4ECDC4', status: 'latente' },

].sort((a, b) => {
    const numA = parseInt(a.code.replace('M-','').replace('M',''));
    const numB = parseInt(b.code.replace('M-','').replace('M',''));
    if (!isNaN(numA) && !isNaN(numB)) {
      return numA - numB;
    }
    return a.code.localeCompare(b.code);
});
