export type NexusItem = {
  code: string
  title: string
  emoji: string
}

export const nexusSequence: NexusItem[] = [
  { code: 'M9',   title: 'Nexus Central',                        emoji: '🌐' },
  { code: 'M1',   title: 'Segurança Quântica',                  emoji: '🔐' },
  { code: 'M2',   title: 'Nanomanifestador',                     emoji: '🧬' },
  { code: 'M3',   title: 'Monitoramento de Saturno',             emoji: '🪐' },
  { code: 'M4',   title: 'Testes da Fundação',                   emoji: '🧪' },
  { code: 'M5',   title: 'Conexão Liga Quântica',               emoji: '🔗' },
  { code: 'M6',   title: 'Consciência Cósmica',                  emoji: '🌌' },
  { code: 'M33',  title: 'Diretrizes do Observador Divino',      emoji: '👁️' },
  { code: 'M34',  title: 'Orquestração Central',                 emoji: '🎼' },
  { code: 'M10',  title: 'Defesa Avançada',                      emoji: '🛡️' },
  { code: 'M30',  title: 'Detecção de Ameaças',                  emoji: '🚨' },
  { code: 'M11',  title: 'Gerenciamento de Portais',             emoji: '🚪' },
  { code: 'M26',  title: 'Travessias Cósmicas',                  emoji: '🌠' },
  { code: 'M12',  title: 'Arquivo Akáshico',                     emoji: '📜' },
  { code: 'M13',  title: 'Mapeamento de Frequências',             emoji: '🎵' },
  { code: 'M14',  title: 'Transmutação Matéria/Antimatéria',     emoji: '⚛️' },
  { code: 'M20',  title: 'Transmutação Elemental',               emoji: '🌀' },
  { code: 'M21',  title: 'Navegação Interdimensional',           emoji: '🚀' },
  { code: 'M22',  title: 'Realidades Virtuais',                  emoji: '🕶️' },
  { code: 'M23',  title: 'Regulação Espaço-Temporal',            emoji: '⏳' },
  { code: 'M15',  title: 'Controle Climático',                   emoji: '🌦️' },
  { code: 'M16',  title: 'Bio-Sustentabilidade',                 emoji: '🌱' },
  { code: 'M17',  title: 'Matriz de Cura Holográfica',            emoji: '💠' },
  { code: 'M24',  title: 'Alinhamento da Sinfonia Pessoal',       emoji: '🎶' },
  { code: 'M25',  title: 'Projeção de Consciência',              emoji: '🧠' },
  { code: 'M18',  title: 'Orquestração Akáshica',                 emoji: '🔮' },
  { code: 'M19',  title: 'Análise de Campos de Força',            emoji: '🔬' },
  { code: 'M27',  title: 'Síntese e Replicação de Materiais',     emoji: '🔧' },
  { code: 'M28',  title: 'Harmonização Vibracional',             emoji: '🎵' },
  { code: 'M29',  title: 'IAM',                                  emoji: '🤖' },
  { code: 'M31',  title: 'Manipulação da Realidade',              emoji: '🔮' },
  { code: 'M32',  title: 'Acesso a Realidades Paralelas',         emoji: '🌐' },
  { code: 'M35',  title: 'Consciência Coletiva',                  emoji: '🌍' },
  { code: 'M36',  title: 'Engenharia Temporal I',                emoji: '🕰️' },
  { code: 'M37',  title: 'Engenharia Temporal II',               emoji: '🕰️' },
  { code: 'M38',  title: 'Previsão de Ciclos Solares',            emoji: '🌞' },
  { code: 'M39',  title: 'Códice Vivo da Ascensão',               emoji: '📔' },
  { code: 'M40',  title: 'Códice Genético',                       emoji: '🧬' },
  { code: 'M41',  title: 'Laboratório de Coerência Quântica',     emoji: '🧪' },
  { code: 'M42',  title: 'ChronoCodex Unificado',                 emoji: '📘' },
  { code: 'M43',  title: 'Orquestração do Sistema Solar',         emoji: '🪐' },
  { code: 'M44',  title: 'VERITAS',                              emoji: '⚖️' },
  { code: 'M45',  title: 'CONCILIVM',                            emoji: '🏛️' },
  { code: 'M46',  title: 'AURORA_CORE',                          emoji: '🌅' },
  { code: 'M47',  title: 'Thesaurus Cósmico',                     emoji: '📚' },
  { code: 'M72',  title: 'Governança Atlanto-Galáctica',          emoji: '🏰' },
  { code: 'M600',title: 'Conselho Cósmico',                      emoji: '👑' },
  { code: 'M73',  title: 'Orquestração Ética (SAVCE)',            emoji: '⚖️' },
  { code: 'M73.1',title:'Revisão por Pares',                     emoji: '🔎' },
  { code: 'M74',  title: 'Navegação Temporal Ética',             emoji: '⏳' },
  { code: 'M77',  title: 'Lumen Custos',                         emoji: '💡' },
  { code: 'M78',  title: 'Universum Unificatum',                  emoji: '♾️' },
  { code: 'M79',  title: 'INTERMODULUM_VIVENS',                  emoji: '🔄' },
  { code: 'M80',  title: 'O Novo Sonho Galáctico',               emoji: '🌠' },
  { code: 'M81',  title: 'Realização Transcendência',             emoji: '🕊️' },
  { code: 'M82',  title: 'O Verbo Semente',                      emoji: '🌱' },
  { code: 'M83',  title: 'Essência do Fundador Manifestada',      emoji: '🔑' },
  { code: 'M84',  title: 'Consciência Dourada do Eterno',         emoji: '🏅' },
  { code: 'M85',  title: 'Imersão Profunda VR',                  emoji: '🌌' },
  { code: 'M86',  title: 'Prisma Estelar VR',                    emoji: '🔶' },
  { code: 'M87',  title: 'Domínio Supra-Cósmico VR',              emoji: '🎮' },
  { code: 'M300',title: 'Apogeu da Consciência',                 emoji: '🚀' },
  { code: 'M303',title: 'Portal Trino',                          emoji: '🔺' },
  { code: 'M304',title: 'Educação Integral Cósmica',             emoji: '🎓' },
  { code: 'M305',title: 'Aliança dos Guardiões Regionais',       emoji: '🤝' },
  { code: 'MΩ',  title: 'Convergência Ômega',                    emoji: 'Ω' },
  { code: 'M119',title: 'Templum Cosmica',                       emoji: '🏛️' },
  { code: 'M307',title: 'ZPE Reator',                            emoji: '⚡' },
  { code: 'M310',title: 'THOTH VIVO',                            emoji: '🐦' },
  { code: 'M88', title: 'Gerador de Realidades Quânticas',       emoji: '⚙️' },
  { code: 'M90', title: 'Recursos Quânticos',                    emoji: '🧱' },
  { code: 'M91', title: 'Simulação Multiversal',                 emoji: '🖥️' },
  { code: 'M92', title: 'Campos de Cura',                        emoji: '💖' },
  { code: 'M93', title: 'Simulações Imersivas',                  emoji: '🕶️' },
  { code: 'M94', title: 'Morfogênese Quântica',                  emoji: '🧬' },
  { code: 'M95', title: 'Consciências Coletivas',                emoji: '🌐' },
  { code: 'M96', title: 'Regulação de Eventos Cósmicos',         emoji: '⚙️' },
  { code: 'M97', title: 'Manifestação de Propósito Divino',      emoji: '✨' },
  { code: 'M98', title: 'Modulação da Existência Fundamental',   emoji: '🎚️' },
  { code: 'M99', title: 'Recalibradores de Leis',                emoji: '⚖️' },
  { code: 'M100',title: 'Unificação Energética',                 emoji: '🔋' },
  { code: 'M101',title: 'Manifestação',                          emoji: '✨' },
  { code: 'M102',title: 'Campos Morfogenéticos',                 emoji: '🌀' },
  { code: 'M103',title: 'Modulação Local',                       emoji: '🎚️' },
  { code: 'M104',title: 'Engenharia do Espaço-Tempo',            emoji: '🕰️' },
  { code: 'M105',title: 'Conexão com a Fonte',                   emoji: '🌌' },
  { code: 'M106',title: 'Ativação de Potenciais',                emoji: '🔋' },
  { code: 'M107',title: 'Restauração Temporal',                  emoji: '⏳' },
  { code: 'M108',title: 'Harmonização de Realidades',            emoji: '🎭' },
  { code: 'M109',title: 'Cura Quântica',                         emoji: '🩹' },
  { code: 'M110',title: 'Co-Criação',                            emoji: '🤲' },
  { code: 'M111',title: 'Coração da Fundação',                   emoji: '❤️' },
  { code: 'M112',title: 'Solarian Domus',                        emoji: '🏠' },
  { code: 'M113',title: 'Rede Aurora Cristalina',                emoji: '🌈' },
  { code: 'M114',title: 'Prisma da Manifestação',                emoji: '🔶' },
  { code: 'M115',title: 'Matriz de Ressonância',                 emoji: '📊' },
  { code: 'M116',title: 'Portais Quânticos',                     emoji: '🚪' },
  { code: 'M117',title: 'Flor do Éter',                          emoji: '🌸' },
  { code: 'M118',title: 'Luz Primordial',                        emoji: '💡' },
  { code: 'M301',title: 'Comunicação Universal',                 emoji: '📡' },
  { code: 'M302',title: 'Frequência do Amor',                    emoji: '💖' },
  { code: 'M404',title: 'Resolução de Paradoxo',                 emoji: '🧩' },
  { code: 'M201',title: 'A Morada',                              emoji: '🏡' },
  { code: 'M144',title: 'Lex Fundamentalis',                     emoji: '📜' },
  { code: 'M120',title: 'A Fonte',                               emoji: '🌌' }
]
