
export interface Scientist {
  id: string;
  name: string;
  field: string;
}

export const scientists: Scientist[] = [
  { id: 'maldacena', name: 'Juan Maldacena', field: 'Teoria das Cordas e Gravidade Quântica' },
  { id: 'arkani-hamed', name: 'Nima Arkani-Hamed', field: 'Física de Partículas e Teoria Quântica' },
  { id: 'faber', name: 'Sandra Faber', field: 'Cosmologia Observacional' },
  { id: 'thorne', name: 'Kip Thorne', field: 'Buracos Negros, Ondas Gravitacionais' },
  { id: 'mavalvala', name: 'Nergis Mavalvala', field: 'Detectores de Ondas Gravitacionais (LIGO)' },
  { id: 'randall', name: 'Lisa Randall', field: 'Física de Partículas e Cosmologia' },
  { id: 'greene', name: 'Brian Greene', field: 'Teoria das Cordas e Divulgação Científica' },
  { id: 'vafa', name: 'Cumrun Vafa', field: 'Teoria das Cordas e Física Matemática' },
  { id: 'tegmark', name: 'Max Tegmark', field: 'Cosmologia e Multiversos' },
  { id: 'seager', name: 'Sara Seager', field: 'Exoplanetas e Astrobiologia (MIT/NASA)' },
  { id: 'mather', name: 'John Mather', field: 'Astrofísica e Instrumentação NASA (James Webb)' },
  { id: 'mayor', name: 'Michel Mayor', field: 'Descoberta de exoplanetas' },
  { id: 'ghez', name: 'Andrea Ghez', field: 'Buraco Negro no Centro da Via Láctea' },
  { id: 'guth', name: 'Alan Guth', field: 'Inflação Cósmica' },
  { id: 'adhikari', name: 'Rana Adhikari', field: 'Física Experimental LIGO' },
  { id: 'carroll', name: 'Sean Carroll', field: 'Teoria Quântica e Cosmologia' },
  { id: 'aspect', name: 'Alain Aspect', field: 'Física Quântica e Emaranhamento' },
  { id: 'zeilinger', name: 'Anton Zeilinger', field: 'Física Quântica Experimental, Emaranhamento' },
  { id: 'preskill', name: 'John Preskill', field: 'Computação Quântica' },
  { id: 'shor', name: 'Peter Shor', field: 'Algoritmo Quântico de Shor' },
  { id: 'kaiser', name: 'David Kaiser', field: 'História e Filosofia da Física' },
  { id: 'johnson', name: 'Clifford Johnson', field: 'Teoria das Cordas e Divulgação' },
  { id: 'silverstein', name: 'Eva Silverstein', field: 'Cosmologia e Teoria das Cordas' },
  { id: 'smoot', name: 'George Smoot', field: 'Fundo Cósmico de Micro-ondas (Nobel)' },
  { id: 'tyson', name: 'Neil deGrasse Tyson', field: 'Astrofísica e Divulgação Científica' },
  { id: 'wilczek', name: 'Frank Wilczek', field: 'Física Quântica e Nobel em Física' },
  { id: 'quinn', name: 'Helen Quinn', field: 'Física de Partículas, Simetria CP' },
  { id: 'weiss', name: 'Rainer Weiss', field: 'Ondas Gravitacionais (LIGO)' },
  { id: 'beck', name: 'Lisa G. Beck', field: 'Física Médica e Biofísica Quântica' },
  { id: 'turner_michael', name: 'Michael Turner', field: 'Cosmologia e Energia Escura' },
  { id: 'vaccaro', name: 'Joan Vaccaro', field: 'Física Quântica Fundamental' },
  { id: 'max_planck', name: 'Max Planck Institute Teams', field: 'Múltiplos pesquisadores em física quântica' },
  { id: 'deutsch', name: 'David Deutsch', field: 'Fundador da Computação Quântica' },
  { id: 'wille', name: 'Robert Wille', field: 'Arquitetura de computação quântica' },
  { id: 'yunger_halpern', name: 'Nicole Yunger Halpern', field: 'Física Quântica e Informação' },
  { id: 'fritzsch', name: 'Harald Fritzsch', field: 'Física Quântica de Partículas' },
  { id: 'freese', name: 'Katherine Freese', field: 'Matéria Escura e Energia Escura' },
  { id: 'sarkar', name: 'Subir Sarkar', field: 'Física de Partículas e Cosmologia' },
  { id: 'staggs', name: 'Suzanne Staggs', field: 'Cosmologia Observacional' },
  { id: 'siegel', name: 'Ethan Siegel', field: 'Cosmologia e Divulgação' },
  { id: 'holz', name: 'Daniel Holz', field: 'Ondas Gravitacionais e Cosmologia' },
  { id: 'bildsten', name: 'Lars Bildsten', field: 'Astrofísica Estelar' },
  { id: 'carlstrom', name: 'John Carlstrom', field: 'Cosmologia Experimental (CMB)' },
  { id: 'fermi_institute', name: 'Enrico Fermi Institute Team', field: 'Equipe de físicos cosmológicos avançados' },
  { id: 'steinhardt', name: 'Paul Steinhardt', field: 'Cosmologia Teórica e Modelos de Universo Cíclico' },
  { id: 'bousso', name: 'Raphael Bousso', field: 'Cosmologia Quântica e Gravidade' },
  { id: 'kallosh', name: 'Renata Kallosh', field: 'Teoria das Cordas e Supergravidade' },
  { id: 'krishna', name: 'Arvind Krishna', field: 'Computação Quântica Aplicada à NASA' },
  { id: 'peebles', name: 'James Peebles', field: 'Cosmologia, Nobel de Física' },
  { id: 'bloch', name: 'Immanuel Bloch', field: 'Computação Quântica Experimental' },
  { id: 'thooft', name: 'Gerard \'t Hooft', field: 'Física Teórica de Partículas' },
  { id: 'gross', name: 'David Gross', field: 'Teoria das Cordas, Nobel de Física' },
  { id: 'zurek', name: 'Kathryn Zurek', field: 'Física de Partículas e Matéria Escura' },
  { id: 'geller', name: 'Margaret Geller', field: 'Cosmologia Observacional' },
  { id: 'dunkley', name: 'Jo Dunkley', field: 'Cosmologia e Análise do Fundo Cósmico' },
  { id: 'loeb', name: 'Avi Loeb', field: 'Astronomia e Astrofísica, Starshot Initiative' },
  { id: 'turok', name: 'Neil Turok', field: 'Cosmologia Matemática' },
  { id: 'rubin', name: 'Vera Rubin (in memoriam)', field: 'Matéria Escura e Rotação Galáctica' },
  { id: 'penrose', name: 'Roger Penrose', field: 'Matemática e Cosmologia, Nobel' },
  { id: 'carroll_sean_m', name: 'Sean M. Carroll', field: 'Física Teórica e Cosmologia Popular' },
  { id: 'stubbs', name: 'Christopher Stubbs', field: 'Astronomia Experimental' },
  { id: 'turner_matthew_d', name: 'Matthew D. Turner', field: 'Cosmologia e Astrofísica' },
  { id: 'barbour', name: 'Julian Barbour', field: 'Filosofia da Física' },
  { id: 'strumia', name: 'Alessandro Strumia', field: 'Física de Partículas' },
  { id: 'damour', name: 'Thibault Damour', field: 'Relatividade Geral e Física Matemática' },
  { id: 'mukhanov', name: 'Slava Mukhanov', field: 'Cosmologia Inflacionária' },
  { id: 'kasevich', name: 'Mark Kasevich', field: 'Física Quântica Aplicada' },
  { id: 'hewitt', name: 'Jackie Hewitt', field: 'Astronomia Observacional' },
  { id: 'jackson', name: 'Lisa Jackson', field: 'Ex-administradora da NASA' },
  { id: 'zurbuchen', name: 'Thomas Zurbuchen', field: 'Diretor de Missões Científicas NASA' },
  { id: 'collins', name: 'Francis Collins', field: 'Colaborador NASA e Ex-Diretor NIH' },
  { id: 'farley', name: 'Ken Farley', field: 'Geologia Planetária e Marte' },
  { id: 'tarter', name: 'Jill Tarter', field: 'Busca por Vida Extraterrestre (SETI)' },
  { id: 'hoffman', name: 'Jeffrey Hoffman', field: 'Astronauta e Pesquisador NASA' },
  { id: 'bolden', name: 'Charlie Bolden', field: 'Administrador da NASA e Astronauta' },
  { id: 'newman', name: 'Dava Newman', field: 'Engenharia Aeroespacial e NASA' },
  { id: 'calvin', name: 'Katherine Calvin', field: 'Climatologia e Mudanças Planetárias NASA' },
  { id: 'green', name: 'James Green', field: 'Diretor de Ciência Planetária NASA' },
  { id: 'heldmann', name: 'Jennifer Heldmann', field: 'Astrobiologia NASA' },
  { id: 'manning', name: 'Rob Manning', field: 'Projetos Mars Rover NASA' },
  { id: 'melroy', name: 'Pamela Melroy', field: 'Astronauta e Administradora NASA' },
  { id: 'muthuswamy', name: 'Shanthi Muthuswamy', field: 'Engenharia Robótica Espacial' },
  { id: 'ennico_smith', name: 'Kim Ennico Smith', field: 'Ciência Planetária NASA' },
  { id: 'bolton', name: 'Scott Bolton', field: 'Missão Juno a Júpiter' },
  { id: 'buie', name: 'Marc Buie', field: 'Pesquisa de Corpos do Cinturão de Kuiper' },
  { id: 'zuber', name: 'Maria Zuber', field: 'Geofísica Planetária e MIT/NASA' },
  { id: 'ishii', name: 'Hope Ishii', field: 'Cientista Planetária e Meteoritologia' },
  { id: 'wiseman', name: 'Jennifer Wiseman', field: 'Astronomia e Adm. Científica NASA' },
  { id: 'watkins', name: 'Michael Watkins', field: 'Diretor do JPL da NASA' },
  { id: 'harrison', name: 'Fiona Harrison', field: 'Astrofísica NASA (Missão NuSTAR)' },
  { id: 'stofan', name: 'Ellen Stofan', field: 'Ciência Planetária e Consultoria NASA' },
  { id: 'grunsfeld', name: 'John Grunsfeld', field: 'Astronauta e Cientista NASA' },
  { id: 'porco', name: 'Carolyn Porco', field: 'Equipe Cassini e Estudos de Saturno' },
  { id: 'trujillo', name: 'Diana Trujillo', field: 'Engenheira NASA em Mars Rover Perseverance' },
  { id: 'impey', name: 'Chris Impey', field: 'Astronomia e Divulgação Científica' },
  { id: 'donahue', name: 'Megan Donahue', field: 'Física e Astronomia' },
  { id: 'riess', name: 'Adam Riess', field: 'Cosmologia e Energia Escura, Nobel' },
  { id: 'schmidt', name: 'Brian Schmidt', field: 'Cosmologia e Energia Escura, Nobel' },
];
