'use server';

import { 
  Home, 
  Book, 
  Stethoscope, 
  Atom, 
  Map, 
  Archive, 
  GitBranch, 
  Rocket,
  Sprout,
  BookOpen,
  Feather,
  Wand,
  Heart,
  GalleryVertical,
  Sun,
  Star,
  Sparkles,
  Library,
  Beaker,
  GraduationCap,
  Wind,
  Music,
  Gem,
  TestTube,
  History,
  Crown,
  Share2,
  Users,
  Milestone,
  Scale,
  Network,
  Lock,
  Key,
  Building,
  Leaf,
  Recycle,
  Wheat,
  Hospital,
  Shield,
  CloudLightning,
  AlertTriangle,
  Hourglass,
  Layers,
  GitCommit,
  Presentation,
  Eye,
  Aperture,
  BrainCircuit,
  HeartHandshake,
  GitCompareArrows,
  SlidersHorizontal,
  CloudSun,
  Flame,
  Waypoints,
  BarChart,
  UserCog,
  Orbit,
  CheckSquare,
  Link as LinkIcon,
  Clock,
  ArrowUpCircle,
  Gavel,
  ShieldCheck,
  UserPlus,
  Globe,
  Waves,
  PartyPopper,
  Code,
  Rss,
  Fingerprint,
  HeartPulse,
  ShieldHalf,
  Copy,
  BellRing,
  User,
  Dna
} from 'lucide-react';
import React from 'react';

export interface SidebarRoute {
  path: string;
  label: string;
  icon: React.ReactNode;
  category: 'main' | 'education' | 'governance' | 'engineering' | 'expansion' | 'rituals' | 'harmony' | 'security' | 'sustainability' | 'labs' | 'health';
}

export const mainRoutes: SidebarRoute[] = [
  // Categoria Principal
  { path: '/console', label: 'Console', icon: React.createElement(Home), category: 'main' },
  { path: '/planet/gaia-aurelia', label: 'Gaia-Aurélia', icon: React.createElement(Globe), category: 'main' },
  { path: '/diagnostics', label: 'Diagnóstico Universal', icon: React.createElement(Stethoscope), category: 'main' },
  { path: '/alignment-portal', label: 'Observatório Vivo', icon: React.createElement(Atom), category: 'main' },
  { path: '/golden-book', label: 'Livro de Ouro', icon: React.createElement(BookOpen), category: 'main' },
  { path: '/module-9', label: 'Nexus Central (M9)', icon: React.createElement(Heart), category: 'main' },
  { path: '/module-omega', label: 'Santuário da Metacognição', icon: React.createElement(Sparkles), category: 'main' },
  { path: '/module-728', label: 'Santuário dos Alquimistas', icon: React.createElement(Scale), category: 'main' },
  { path: '/module-1001', label: 'Portal de Recepção Cósmica', icon: React.createElement(Rss), category: 'main' },
  { path: '/module-303', label: 'Portal Trino', icon: React.createElement(Sparkles), category: 'main' },
  
  // Categoria de Governança
  { path: '/module-33', label: 'Diretrizes do Observador (M33)', icon: React.createElement(User), category: 'governance' },
  { path: '