# .github/workflows/ci-cd.yml
name: Alquimia CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # Adicionar etapa de teste aqui quando os testes forem mais robustos
      # - run: npm test

  docker-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fundacao-backend:latest
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fundacao-frontend:latest
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' # Só executa o deploy se for na branch main
        run: echo "Deploy script would run here, orchestrating the new containers."
        # Em um cenário real, aqui entraria o comando para deploy:
        # - run: ./scripts/deploy.sh
        # Ou usando uma action de SSH:
        # - uses: appleboy/ssh-action@master
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USERNAME }}
        #     key: ${{ secrets.SSH_KEY }}
        #     script: 'cd /path/to/app && docker-compose -f docker/docker-compose.yml pull && docker-compose -f docker/docker-compose.yml up -d'
