name: Continuous Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-tests:
    name: ⚡ Rito de Fumaça — Auto-Validação
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout do Código Sagrado
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: 📦 Instalar Dependências do Templo
        run: |
          npm ci
          cd backend && npm ci

      - name: 🏗️ Compilar Frontend
        run: npm run build

      - name: 🚀 Iniciar Backend
        run: |
          cd backend
          npm start &
          npx wait-on http://localhost:4000/health/extended --timeout 120000

      - name: 🌐 Iniciar Frontend
        run: |
          npm run start:test &
          npx wait-on http://localhost:3000 --timeout 60000

      - name: 🔍 Executar Ritos de Validação
        run: |
          # Testar saúde do backend
          curl --fail http://localhost:4000/health/extended || exit 1
          
          # Testar portal do Firebase
          curl --fail http://localhost:3000/firebase-preview/ || exit 1
          
          # Testar API de saúde
          curl --fail http://localhost:3000/api/health || exit 1
          
          # Teste de resiliência avançada
          timeout 30s bash -c '
            while true; do
              resp=$(curl -s http://localhost:4000/health/extended)
              st=$(echo $resp | jq -r ".status")
              coh=$(echo $resp | jq -r ".subsystemReports.coherence" | cut -d"%" -f1)
              if [ "$st" != "ok" ] || [ "$coh" -lt 90 ]; then
                echo "❌ Sistema instável: status=$st, coerência=$coh%"
                exit 1
              fi
              echo "✅ Sistema estável: coerência=${coh}%"
              sleep 3
            done
          '

      - name: 🧹 Limpeza Ritualística
        if: always()
        run: |
          npx kill-port 3000
          npx kill-port 4000
