
version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fundacao
      - JWT_SECRET=a-very-secret-key-for-the-foundation
    depends_on:
      - mongo

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.2.3
    ports:
      - "3001:3000"
    volumes:
      - ../monitoring/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/fundacao.json

volumes:
  mongo-data:
