title: "Fundação Alquimista - Sistema Zenith"
description: "Documentação Científica da Revolução da Consciência Quântica"
baseurl: "/fundacao-alquimista"
url: "https://danieltoloczkocoutinho.github.io"
theme: jekyll-theme-cayman
